### ISSUE TITLE
preact example not working

### ISSUE THREAD

**Issue by vinaypuppal** [zeit/next.js#1006]
https://github.com/zeit/next.js/tree/master/examples/using-preact
Initially its rendering the content and immediately removing it from DOM. Same happening on every page refresh. No errors on browser console or terminal.

![screen shot 2017-02-05 at 10 51 16 pm](https://cloud.githubusercontent.com/assets/8843216/22628241/b2b869b0-ebf6-11e6-83f8-9250dde17108.png)

**Comment by bryanrsmith** [comment]
I think this is happening because Next.js is using a babel plugin to explicitly alias react imports: https://github.com/zeit/next.js/blob/ddd93e9865fe3b05ca5d8d473650c8265f3fb5c3/server/build/webpack.js#L176-L178

If I'm understanding correctly, it seems like the server is rendering with React and the client is trying to continue with Preact. If I remove those lines from Next.js the Preact example runs without error.

**Comment by bryanrsmith** [comment]
That was added in #963. @timneutkens what do you think?

**Comment by thangngoc89** [comment]
There is a PR for preact here https://github.com/zeit/next.js/pull/767 . But it isn't gonna be merged soon.

**Comment by vinaypuppal** [comment]
just checked with latest  version`2.0.0-beta.25` and the example seems working fine.
