### ISSUE TITLE
Add webpack-bundle-analyzer

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#1080]
https://github.com/th0r/webpack-bundle-analyzer

Possibly under a flag `--output-stats` or something similar. Already made a POC since I needed to check the bundle sizes. It's pretty neat for checking module / bundle sizes. Just wanted to discuss if we should implement it by default and in what way we want to expose it.

What I did was expose `.next/stats.json` to be consumed by the webpack-bundle-analyzer cli.
`webpack-bundle-analyzer .next/stats.json` inside of a project.

cc @arunoda @nkzawa

**Comment by samjbmason** [comment]
This would be awesome 👍

**Comment by timneutkens** [comment]
@samjbmason added an example instead #1110

**Comment by dizlexik** [comment]
This is great but it only displays stats for `main.js` and `common.js`, which is not very useful as far as I can tell. I'd be **much** more interested in seeing stats for each page bundle but I'm not sure how this example can be modified in order to accomplish that. In looking through `stats.json` it seems to me that what we really want to analyze are the `entrypoints` (which contain references to the chunks), but webpack-bundle-analyzer only processes `assets`. Any ideas? I don't have enough time to dig any deeper right now, sorry :/

By the way if I manually edit my `stats.json` assets to include the chunks from entrypoints I'm able to see exactly what I want to see, but this is a lame hack.

webpack-bundle-anylyzer's analyzer.js:
https://github.com/th0r/webpack-bundle-analyzer/blob/master/src/analyzer.js#L28

**Comment by damusnet** [comment]
Hi @dizlexik 
I see the exact opposite: only stats for each entrypoint, and no info about `app.js`. Do you know what change since your last entry, and how to get infos about the main bundle?

**Comment by timneutkens** [comment]
@damusnet Arunoda updated the example just yesterday 😄 cc @arunoda

**Comment by timneutkens** [comment]
@damusnet could you create a new issue to track this?

**Comment by damusnet** [comment]
Thanks @timneutkens for getting back to me so quickly!

Looking more closely at @arunoda [latest change](https://github.com/zeit/next.js/commit/23c2f02f56063d7cebf3940f0eb02b8acfadabb6#diff-f81807dfaab2849fde44d7b80f770951L18), I noticed the `delete compilation.assets[name]`. Making the same change in my Next.js version allows me to see all chunks perfectly! Problem solved.

👍

**Comment by timneutkens** [comment]
Awesome! Should this be default @damusnet?

**Comment by damusnet** [comment]
@timneutkens Yes. You get all chunks in the report, and can toggle them on/off in the web UI.

I was under the impression the change in #2393 was the new default, which would be a good thing.

**Comment by renancouto** [comment]
@timneutkens `app.js` is not shown on analyzer, and it can be the biggest file on the bundle. Is there a reason to do that? Is it possible to analyse it too?

**Comment by jonaswindey** [comment]
+1 on the question of @renancouto

**Comment by damusnet** [comment]
@renancouto @jonaswindey you should have common.js in your analyzer report. It is the biggest part of app.js, which also includes main.js and manifest.json. Really, common.js is all you need to look at. If you don't see it, check your Next.js version.

**Comment by timneutkens** [comment]
`app.js` shouldn't show up in reports because it's a concat of `main.js` `common.js` and `manifest.js`, nothing special is done there 👍

**Comment by timneutkens** [comment]
@renancouto @jonaswindey see my above answer 👍
