### ISSUE TITLE
Unit test can't resolve module next/<module>

### ISSUE THREAD

**Issue by jagreehal** [zeit/next.js#113]
Following the Jest example, testing components that import 'next/link', 'next/css' or 'next/head' fail because they can't resolve next/<module>.

How can this be resolved?

**Comment by michaelhelvey** [comment]
I'm having this problem too.  Besides Jest failing, ESLint complains.  The reason is because when the Node module resolver sees `import Head from 'next/head'`, it expects the `next` package in `node_modules` to have a `head.js` file in the root directory of the package.  The `next` package itself doesn't have this problem because it's requiring the modules directly from `dist/lib/*` directory.

You can fix this (temporarily at least) by just adding a file in your `node_modules/next` directory that requires the corresponding file in `dist/lib`.  For example, to get `import Head from 'next/head'` working for both Next and Jest you can just add a file:`node_modules/next/head.js`, that contains just `require('./dist/lib/head.js')`.   Then ESLint and Jest will stop complaining.

This is super hacky, though and it seems like the gulp build process for this package should write out these files to begin with, to support Jest and other test runners. I'd be interested in submitting a PR for this, if maintainers are interested.  @nkzawa ?

**Comment by nkzawa** [comment]
@michaelhelvey It seems great to fix. I think it'd be nice to put files like `next/head.js` (no gulp tasks).
