### ISSUE TITLE
Component template based on JSON data

### ISSUE THREAD

**Issue by OutThisLife** [zeit/next.js#1220]
Wasn't able to find anything, but if an example exists please share!

So I'm consuming an API on the Node.js server that will pass a "template" variable, and I'd like this variable to decide which component to render despite the slug. IE custom routing, but I'm not sure of the best way to go about it.

Was trying to use some custom Layout component to determine it but I get errors if I don't use `<Main />` from document.

**Comment by timneutkens** [comment]
@OutThisLife just came across this ticket. Is it still valid?
You can't use `_document.js` here since it will only render server side. 
This example might help you:
https://github.com/zeit/next.js/tree/master/examples/layout-component

I'm closing this for now, since it's not related to a bug/feature in Next.js.

**Comment by OutThisLife** [comment]
Yeah I figured out the proper way to do it. Thanks!
