### ISSUE TITLE
Running Jest with getInitialProps

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1277]
The with-jest example doesn't illustrate how to instantiate a page which has a `getInitialProps`. In my own project, when testing with 
```js
import Home from '../pages/index';
const home = shallow(<Home />);
```

the constructor gets called with an empty props object. So basically I don't know how to test any of my Next.js pages.

**Comment by sedubois** [comment]
Maybe the only option is to run as integration test, as is done within Next.js' test folder? In that case should the helpers like [next-test-utils](https://github.com/zeit/next.js/blob/master/test/lib/next-test-utils.js), etc be made public?

**Comment by arunoda** [comment]
@sedubois since getInitialProps passes a set of props, you could simply send those props to the component when initializing. Since it's a static function in the React class, you can unit test if needed.

About integration testing, yep we have to open `next-test-utils` as a new repo.
Tracking here: https://github.com/zeit/next.js/issues/1289
