### ISSUE TITLE
Production deployment on AWS EC2

### ISSUE THREAD

**Issue by 416serg** [zeit/next.js#1323]
I was developing the app on the remote EC2 server. So I have something like `ec2-user/nextjsapp/` and spinning up localhost:3000 was no problem, I'd listen on the remote IP at port 3000.

Now I would like to publish it at a subdomain, without using a port (setting up port 80 to listen) but I am having trouble running `next start -p 80` after I do `next build` within that folder. 

What is the process to get the bundled, production ready nextjs app running? 

Thanks 😃

**Comment by jamo** [comment]
Similar to hosting pretty much any node program.

The basic setup for any node app would be along the lines of:
Set up `nginx` that listens for 80 (and 443) with correct `server_name` (subdomain) and proxy passes to next.js (or any node) application running on a custom port, like 3000.

And then to make sure the next.js (or any node) app remains up, throw in a `systemd` service that runs the `next start` or `npm run start` and set it to restart it in case the process dies. and when the ec2 server restarts.

You might even want to wrap the node process to docker but to keep this short and simplified :D

**Comment by 416serg** [comment]
any related links/resources off the top of your head @jamo ? this is some great info though, thanks!

**Comment by 416serg** [comment]
also do I keep the app at `home/ec2-user/nextjsapp` or move it somewhere else? I am not super at setting stuff like this up. Do I keep the bundle as is or does `next build` do something that I don't know about to minify everything and get rid of all dev dependencies.

**Comment by jamo** [comment]
I had hard time finding a great tutorial but combining these two (or just going with the digital ocean one) should guide you thru similar setup that I described in short:

- How to make sure the next app keeps running: https://nodesource.com/blog/running-your-node-js-app-with-systemd-part-1/
- How to setup nginx and make it to listen for the subdomain: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04#set-up-nginx-as-a-reverse-proxy-server
For some reason, I'd skip the pm2 and just go with the systemd...

And you probably want to keep the dev version and deployed/production version in different folders so that they could co-exist

**Comment by 416serg** [comment]
Also, using Amazon Linux, and can't seem to find `systemd`, is https://www.npmjs.com/package/pm2 a good way to go?

**Comment by 416serg** [comment]
was about to use `forever` and configure application load balancing to proxy requests to port 3000. 

Thanks for the help!
