### ISSUE TITLE
Share values from server rendered pages to client rendered pages

### ISSUE THREAD

**Issue by possibilities** [zeit/next.js#1409]
I find myself doing some gymnastics to share values from server to client. E.g. read in an environment variable and send the value to every page as a prop. One idea that would solve this would be if in `./pages/_document.js` you could pass props to `<Main />` and have them injected for you in every page (or `getInitialProps`?).

The approach I'm using now is to wrap every page in a decorator that does the work of passing the values from the server rendered page to client rendered pages by passing the values via an object on `window`.

**Comment by arunoda** [comment]
I think you did it correctly. Here's the recommended approach.

* Just like create you create, use a decorator to write a getInitialProp and send down data to the client.
* Then with that data initialize the redux-store or any client side store. (What you did is exactly the same)

On the other side, you can use the `_document` as well. You can create a custom script tag which holds data. And you can make it dynamic too, because the `getInitialProps` of `_document` also getting the HTTP `req` object.

**Comment by possibilities** [comment]
Great thanks for spelling it all out for me. I had a hard time groking it but it seemed like `__NEXT_DATA__` might be being used for a similar purpose, right? Thanks again!

**Comment by sergiodxa** [comment]
@possibilities `__NEXT_DATA__` is used to avoid refetching the initial props and speed up the client-side load time writing both the server fetched data and the page component in that variable
