### ISSUE TITLE
Feature Request: Absolute import paths

### ISSUE THREAD

**Issue by tashburn** [zeit/next.js#1469]
Please implement absolute paths for imports, in addition to the current relative paths. It's simpler and cleaner to write

> // :-)
> import NavBar from 'components/NavBar'
>
> // :-(
> import NavBar from '../components/NavBar'

Not to mention, it's more scalable for big projects that have more nesting --

> import BaseButton from '../../base/Button'

> // :-)
> import BaseButton from 'components/base/Button'
>
> // :-(
> import BaseButton from '../../base/Button'

Also, it's more consistent because it follows the same form as imports from node_modules, which are absolute not relative imports.

Aaaand, you can move a file up or down a folder without having to update the imports in that file -- so it's more refactorable.

**Comment by sergiodxa** [comment]
You can do It yourself with the babel plugin module resolver, I don't think this is going to be implemented in the core because maybe you don't have a component directory in your root folder and use feature folders, and next let you have any directory structure beyond the pages folder.

**Comment by tashburn** [comment]
I'm suggesting that the root of the absolute hierarchy be the folder containing `pages`. So, if you have a `features` folder instead of a `components` folder, you'd `import Button from 'features/button'`. Does that solve your concerns about making it part of core?

**Comment by tashburn** [comment]
I just tried `babel-plugin-module-resolver`, but it seems to require the presence of .babelrc, which seems to conflict with Next. It wrecks my build (prevents jsx from being considered valid syntax).

Is there another way that `babel-plugin-module-resolver` can be used?

**Comment by arunoda** [comment]
This is how you could use custom babel configs.
Also, you can use this babel plugin too: https://github.com/entwicklerstube/babel-plugin-root-import

We discussed this earlier and we are not going to take this in.
Simply because it's easy to do it in the user-land.

**Comment by sergiodxa** [comment]
@tashburn check this example https://github.com/zeit/next.js/tree/master/examples/with-custom-babel-config on how to use a custom babel config.

BTW I think you can also set `NODE_PATH=.` when running your app to use absolute imports

**Comment by tashburn** [comment]
Thank you for the solutions. I'm loving Next so far.

**Comment by krazyjakee** [comment]
@sergiodxa applying the example babelrc along with the babel-plugin-root-import loses the ability for next to compile sass.

@arunoda following the instructions at https://github.com/entwicklerstube/babel-plugin-root-import loses the ability for next to compile jsx when running `next build`.

The bottom line is that when I run 'npm run dev' from the root of the project and relative imports work, then I run 'npm run build' and it can't locate based on the same relative imports then it's a bug. Since it's a universal, harmless and development-only addition, babel-plugin-root-import **should** come preconfigured in the next core.
