### ISSUE TITLE
Need polypill for Object.assign 

### ISSUE THREAD

**Issue by xdamman** [zeit/next.js#1506]
Firefox 28 (you can download it from https://ftp.mozilla.org/pub/firefox/releases/28.0/ if you need to test it)

Steps to reproduce (nothing fancy, just a fresh install): 

```
mkdir nextpolyfill
cd nextpolyfill
npm install next react react-dom --save
mkdir pages
echo "export default () => (<div>Welcome to next.js!</div>)" > pages/index.js
next
open http://localhost:3000
```
![](https://cl.ly/1y25180s3e0n/Screen%20Shot%202017-03-25%20at%202.12.38%20PM.png)

For reference: 
![](https://cl.ly/2B380e2y0v2U/Screen%20Shot%202017-03-25%20at%202.17.10%20PM.png)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by xdamman** [comment]
This is solved in the latest 2.0.0-beta

npm install still install the 1.2.3 version by default.

**Comment by rwieruch** [comment]
I was running into this issue for IE11 and Next.js 2.4.9. Do I still need a polyfill when upgrading to the recent Next.js version (3.2.2 at this time)? Otherwise I would include the polyfill like this https://github.com/zeit/next.js/issues/453 I am not able to test it right now and didn't find anything in the release notes.

**Comment by getsetbro** [comment]
#polypill
