### ISSUE TITLE
Automatic code splitting doesn't work

### ISSUE THREAD

**Issue by berdof** [zeit/next.js#1533]
I am using next@2.0.  And have the following project structure http://take.ms/1ETxA. There are 5 different page components, where I use containers which are placed in the views directory. But instead of having several js files in dist I have only 1 which size is about 1.7mb. Maybe that's because of custom config webpack, babel or server config?

**Comment by sergiodxa** [comment]
@berdof what's the content of bundles and dist?

**Comment by arunoda** [comment]
@berdof this is working pretty well.

You app.js contains ~200KB. See:
<img width="869" alt="screen shot 2017-03-29 at 5 11 19 am" src="https://cloud.githubusercontent.com/assets/50838/24432247/81847396-143e-11e7-858a-8c1f0096ffaf.png">

You 'user' page take ~200KB because it contains moment module. But not other pages. See:
<img width="869" alt="screen shot 2017-03-29 at 5 11 38 am" src="https://cloud.githubusercontent.com/assets/50838/24432260/9c5ea9de-143e-11e7-966e-bfdd81cc0da9.png">

You need to use `npm run build` for this.

We've only core bundle `.next/app.js` and others are located in `.next/bundles/pages`.
