### ISSUE TITLE
with-universal-configuration, local development .babelrc will not run transform-define's env-config.js if there are cache in node_module/.cache

### ISSUE THREAD

**Issue by pencilcheck** [zeit/next.js#1666]
I'm using env-config.js to run dotenv to load variables into process.env

Right now if an application has been run before, this script will not be run thus application error out.

Right now this script will only run if the cache is cleared. Is there a way to disable this behavior so we don't need clean up the .cache manually before every run?

**Comment by arunoda** [comment]
Yes. This is true.
That's because there is no change in the code.

Frankly I'm quite not sure how exactly we can fix this. I welcome for ideas.

If you remove the webpack babel-loader cache, it'll slow app-rebuilding time a lot. (factor of 2-3x)
There's no public API to disable the cache.
Here's how we do it: https://github.com/zeit/next.js/blob/master/server/build/webpack.js#L148

**Comment by pungggi** [comment]
not sure if this is something useful? https://github.com/yosuke-furukawa/active-cache-babel-register

**Comment by arunoda** [comment]
@pungggi thanks. But we don't (and can't) use babel-register.
This is the cache of `babel-loader`

**Comment by pencilcheck** [comment]
How should we disable the cache manually for now just in case?

**Comment by pencilcheck** [comment]
Seems like this doesn't work in production either, since yarn build and yarn start is a separate command, therefore if yarn build already created the cache, yarn start will spit out the error

**Comment by sedubois** [comment]
Is this answered by https://github.com/zeit/next.js/pull/1747?

**Comment by arunoda** [comment]
@sedubois I guess so. 
As we don't have a planned feature for this now.
