### ISSUE TITLE
Next.js eject

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#1691]
Similar to create-react-app, it would be very helpful if Next.js offered an "eject" functionality. This would reassure users who would otherwise fear being "locked" in Next.js once their project outgrows what Next.js can do for them, or e.g in the sad even that Next.js wouldn't be maintained or in favor any more. Paradoxically having an "eject" could help Next.js attract more interest.

Also see [this discussion](https://github.com/reactql/cli/issues/2#issuecomment-293310171) for longer context.

**Comment by arunoda** [comment]
@sedubois sorry. That's not our goal.

We wanted a way expose a better way to run React without any config.
For CRA, it's seems doable because it's basically a thin wrapper around Webpack.
But Next.js is more to that.

Our way to customizing it based on custom babel and webpack config. We can keep improve them.

If you feel, Next.js is not enough after you've build a big app. You can either custom it via babel or webpack. Otherwise, fork Next.js and use it as you like.

**Comment by kunokdev** [comment]
Maybe it would be good to have a convenient approach upon customization since at some point it is unavoidable.

**Comment by sergiodxa** [comment]
@kunokdev you can customize the [webpack](https://github.com/zeit/next.js#customizing-webpack-config) and [babel](https://github.com/zeit/next.js#customizing-babel-config) configuration easily. Many examples use that to support Flowtype, TypeScript, etc. and customize Next.js

**Comment by kunokdev** [comment]
How I see it, Next.js could be a convenient framework that abstracts many build issues from very start of the project, thus making it great for creating prototypes (still following one-command-to-start mindset) and yet a framework that allows you further customization on top of convenience, therefore allowing your application to grow into any direction without  need to at some point replace the core, Next.js itself. Maybe even considering making Next functionalities as modular and replaceable as possible. And as I see it, that is very important in frontend world because of constant changes, allowing framework to constantly replace features without constant need to rewrite applications. 
For example, if framework adopts new features which would replace old ones, upgrading application from one version to other would be painful. However, as modular, it would be known which module needs to be replaced. And that scenario is unavoidable at some point since Next.js actually covers a lot of ideas and automating them. 

I think it is very known at this point that one of biggest problems in frontend world is that as new techniques come, we constantly change frameworks or ideas we follow. We constantly build new frameworks for new ideas. Then community learns new frameworks and evolves, dropping old frameworks behind. That is not ecological and we should consider how do we make our tools adopt new environment rather than building new tools so often.
