### ISSUE TITLE
es2017  can  not build

### ISSUE THREAD

**Issue by foxundermoon** [zeit/next.js#1733]
```
> 279 |                         <button onClick={ ::this.handleOrder} >
      |                                            ^
   280 |                         </button>

```

**Comment by kandros** [comment]
It does require a specific babel transform that is not included in the next's babel preset, you can add it yourself following intructions [here](https://github.com/zeit/next.js#customizing-babel-config)
however using the bind operator inside render is considered an anti-pattern because of performance reasons, more info [here](https://medium.com/@housecor/react-binding-patterns-5-approaches-for-handling-this-92c651b5af56).

**Comment by arunoda** [comment]
Thanks @kandros for the help.
