### ISSUE TITLE
pseudo ":after": doesnt work

### ISSUE THREAD

**Issue by conor909** [zeit/next.js#179]
I cant seem to get this to work, I'v been looking for examples in glamour and next.js but cant find anything.
````
ul: css({
        textAlign: "justify",
        ":after": {
            content: "",
            display: "inline-block",
            width: "100%"
        }
    }),
````

The Glamor github page's api has this example but this also doesnt work, am I suppose to import the `after` from somewhere?
````
<div {...after({ content: '"hello "' })}>
  world!
</div>
````

**Comment by impronunciable** [comment]
@conor909 good news:

1 - You can `import { after } from 'next/css'`

2 - You were almost right in your code. The issue is `content: ""` is not valid. You should use `content: '""'` I know if hard to read but is double quotes `"` wrapped by single quotes `'`.

Feel free to reopen if the issue persist :)
