### ISSUE TITLE
TypeError: _jquery2.default.get(...).bind is not a function

### ISSUE THREAD

**Issue by sunnixx** [zeit/next.js#1823]
This is somewhat strange problem for me. 
When ever I am trying to use Ajax methods in a Jquery call I get the above error. Meanwhile any other JQuery function / method works fine. 

My code snippet is like this: 
```
componentDidMount(){
    $.get('/allstudents',function(response){
        this.setState({data:response});
    }).bind(this);
}
```
Any solutions will be really helpful.
Thanks !

**Comment by spencersmb** [comment]
First guess is it doesn't like the fact you are binding "this" to the GET function. If that is the case - I might try wrapping the get request in a different function inside the class so you can bind "this" to that function instead of the get request. Then I would try using es6 arrow function to automatically bind this and see if it works with jquery. If either of those don't work - the basic problem is I think, assigning "this" properly so you have access to it inside the GET request.

```
componentDidMount(){
    this.getAllStudents();
}
getAllStudents(){
  $.get('/allstudents', (response) => {
        this.setState({data:response});
    });
}
```

**Comment by arunoda** [comment]
Thanks @spencersmb for the answer.

**Comment by sunnixx** [comment]
Thanks @spencersmb, this did the trick.
