### ISSUE TITLE
Loading clientside-only data with getInitialProps

### ISSUE THREAD

**Issue by timoxley** [zeit/next.js#183]
Currently `getInitialProps` will execute **on the server only** for the initial page load.
`getInitialProps` will execute on the clientside only when navigating to a different page via the next `url` api.

I believe this prevents `getInitialProps` from populating props using any clientside-only data sources such as localStorage or indexedDB.

Not sure what the solution is other than executing it on both ends for the initial page load, and subsequently only on the client.

Perhaps the clientside `getInitialProps` could be passed the server-side generated data (if it exists). This then gives the clientside the option to ignore, forward or expand on that data.

e.g.

```js
import React from 'react'

export default class extends React.Component {
  static async getInitialProps ({ req }, serverProps) {
    if (!process.browser) await getServerProps(req) // serverside only
    if (serverProps) return serverProps // if has data from server, just use that
    return await getClientProps() // otherwise get clientside data
  }

  render () {
    return <div />
  }
}
```

**Comment by nkzawa** [comment]
I think you can use `componentDidMount` or other React life cycle methods to retrieve client only data.

**Comment by sedubois** [comment]
I learned from other discussions that `getInitialProps` also runs client-side, but I was quite confused because I didn't see that behaviour when loading the page when printing some `console.log`s. Thanks to this issue I better understand what's going on.

Even if there's a way to load client-only data with `componentWill/DidMount`, making sure `getInitialProps` is called client-side even on page load might help reduce confusion by providing a more coherent API?

**Comment by nkzawa** [comment]
Basically, `getInitialProps` shouldn't be called on client on initial page load, because rendering results of React can be different on server and client if you return different `props` values on each side.

**Comment by dstreet** [comment]
@sedubois I believe `getInitialProps` will only be called on the client-side during client-side routing.

**Comment by nkzawa** [comment]
Closed. Feel free to reopen if you still have the problem.

**Comment by timoxley** [comment]
@nkzawa this issue was really a feature request for something with the simplicity & async-friendliness of `getInitialProps`, except it only runs on the client. Though… perhaps that is a little tricky since to get around the checksum issue it would require injecting magic into `componentDidMount`.

**Comment by manishbalyan** [comment]
got localstorage not found error when calling localstorage.getItem() in getInitialProps method even localstorage is set.

**Comment by sedubois** [comment]
@manishbalyan `getInitialProps` is also executed server-side, but there's no `localStorage` on the server. 
As pointed above, if you want to access the browser's local storage, you should do so in `componentDidMount`.

**Comment by manishbalyan** [comment]
hey @sedubois thanks for reply, but how i get server side rendering if i call for data in componentDidMount. What i am doing is i am making a rest call to fetch data and for that i need some value to be set in headers every time i call so i want that to be stored in localstorage and use it while i set my headers so that i need not to pass that value in every call. Also for authentication purpose i need to set auth token in localstorage so that i can send it every time in content headers to fetch data. 

If you have some other way please help me i am stuck in it from last 5 days.

**Comment by sedubois** [comment]
@manishbalyan I suggest to check this thread: https://github.com/zeit/next.js/issues/153
