### ISSUE TITLE
`getInitialProps` should be exposed as a decorator

### ISSUE THREAD

**Issue by amccloud** [zeit/next.js#186]
If you wrap your page component in a HOC you end up masking `getInitialProps`. Using a decorator would make it easier to define `getInitialProps` on the highest component.

```js
function connectProps(getInitialProps) {
  return (WrappedComponent) => {
    WrappedComponent.getInitialProps = getInitialProps
    return WrappedComponent;
  };
};

function Index() {
  return (
    <div>
      Hello World {this.props.userAgent}
    </div>
  );
}

export default connectProps(({req}) => {
  return req
    ? { userAgent: req.headers['user-agent'] }
    : { userAgent: navigator.userAgent }
})(someOtherHOC(Index));
```

**Comment by amccloud** [comment]
Another example, but a bit cleaner and shows off how this can potentially compose.

```js
import {connectProps} from 'next';
import {someOtherHOC} from 'other-library';

function Index() {
  return (
    <div>
      Hello World {this.props.userAgent}
    </div>
  );
}

const connectUserAgent = connectProps(({req}) => {
  return req
    ? {userAgent: req.headers['user-agent']}
    : {userAgent: navigator.userAgent}
})

export default connectUserAgent(someOtherHOC(Index));
```

**Comment by nkzawa** [comment]
@amccloud I like the idea but am wondering if we should support this in next.js, or creating an external library might be enough.

**Comment by amccloud** [comment]
I think this should become the canonical way for injecting data into a page component. To avoid shadowing getInitialProps, It's easy to explain to always wrap your export. The design also aligns with redux and the likes.

**Comment by nkzawa** [comment]
yep, but actually you'd have to explain to always wrap the _outermost_ component.
that's kind of similar to do to always add `getInitialProps` to the outermost component.

Another idea is to support exporting `getInitialProps` like:

```js
export function getInitialProps () {
  return { name: 'foo' }
}

export default (props) => <div>hi, {props.name}</div>
```

**Comment by sedubois** [comment]
@nkzawa that wouldn't address the problem that the component isn't self-encapsulating. Systems such as Redux allow to `export default connect(...)(Comp)`, i.e a single export suffices and then outside of it, no need to do any special wiring.

It still seems to me like some kind of tree scanning would be needed (https://github.com/zeit/next.js/issues/192), until the day React supports async lifecycle methods (https://github.com/facebook/react/issues/1739)...

**Comment by mikecardwell** [comment]
Just to add another data point: this suggestion is similar to how the Meteor framework does things too and it works well. They call them containers:

```javascript
import { createContainer } from 'meteor/react-meteor-data';

function SomeComponent () {
  return (
    <div>
      Hello World {this.props.userAgent}
    </div>
  );
}

export default createContainer(props => {
  return {
    userAgent: whatever,
  };
}, SomeComponent);
```

It's *slightly* different in that a Meteor container passes the props as arguments, rather than req/res etc, and the returned value of the container is merged in to the props. The return value of a createContainer call is "just another component"

**Comment by amccloud** [comment]
@sedubois why would tree scanning be necessary? Btw, I arrived at this issue when trying to implement authentication also.

```js
export default connectProps([...])(requireAuth(Index));
```

The component returned by `requireAuth` never touches `getInitialProps`.

@nkzawa maybe it can be called `connectPage` and every page component must export wrapped. Next could warn if it doesn't detect the `connectPage` HOC.

**Comment by sedubois** [comment]
@amccloud I might just have misunderstood, but it sounds like this `connect` should still be used on every parent of components which make use of `getInitialProps`? For example: (see [here](https://github.com/sedubois/realate) for something complete)

```js
// pages/index.js
import page from '../hocs/page';
import Child1 from '../components/Child1';

const Home = () => (
  <div>
    <div>Welcome!</div>
    <Child1 />
  </div>
);

export default page(Home);
```

```js
// components/Child1.js
import Users from '../components/Users';

const Child1 = (
  <div>
    <div>something fancy</div>
    <Users />
  </div>
);

export default Child1;
```
```js
// components/Users.js
import apollo from '../hocs/apollo';
import UserPreview from './UserPreview';

const Users = (props) => (props.data.allUsers
      .map(u => <UserPreview key={u.id} user={UserPreview.fragments.user.filter(u)} />);
const query = gql`{ allUsers { id, ...UserPreview } }`;
const options = { options: { fragments: UserPreview.fragments.user.fragments() } };

export default apollo(query, options)(Users);
```

In the above, `apollo` is a HOC which has a `getInitialProps`. If I understood right, you'd still need to add some kind of `connect` e.g. on `Child1`, and inside the `page` HOC, i.e they all get "polluted" just because of the single `getInitialProps` defined inside `apollo`. If this were Redux, this AFAIK wouldn't be necessary. A `connect` used within children does not not force a `connect` in the parents.

Or maybe you meant to pull all the `getInitialProps` logic outside of the `apollo` HOC and into the root component? But that would defeat the purpose of components, which is to have self-encapsulated pieces of code.

Maybe I'd better understand if there were an example with several levels of child components each in their separate file.

**Comment by sedubois** [comment]
@amccloud I think you need to compose the components instead of modifying the original, otherwise this example won't work (prints `Child2` twice):

```js
const Child = ({ name }) => <div>{name}</div>;
const Child1 = connectProps(() => ({ name: 'Child1' }))(Child);
const Child2 = connectProps(() => ({ name: 'Child2' }))(Child);

export default class extends React.Component {
  static getInitialProps(ctx) {
    return {
      child1: Child1.getInitialProps(ctx),
      child2: Child2.getInitialProps(ctx),
    };
  }
  render() {
    return (
      <div>
        <Child1 name={this.props.child1.name} />
        <Child2 name={this.props.child2.name} />
      </div>
    );
  }
}
```

**Comment by sedubois** [comment]
Something like this:
```js
// connectInitialProps.js
import React from 'react';

export default function connectInitialProps(getInitialProps) {
  return (WrappedComponent) => {
    function WithGetInitialProps(props) {
      return <WrappedComponent {...props} />;
    }
    WithGetInitialProps.getInitialProps = getInitialProps;
    return WithGetInitialProps;
  };
}
```

**Comment by amccloud** [comment]
@sedubois good catch. I actually started off with a wrapped component but didn't catch this scenario.

**Comment by timneutkens** [comment]
I'm going to close this. It's a cool idea, but has been open for about 6 months 😄
