### ISSUE TITLE
Link to external URL from next app returns 404 when using back button

### ISSUE THREAD

**Issue by freecates** [zeit/next.js#1872]
Hi, when I follow a link to external URL from next app, it returns 404 when using browser back button. You can try it here:
https://hello-next-fiabinrzin.now.sh/ > Inrernal post link > External link from content > Back button > 404
Is this a nextjs issue or am I doing something wrong?

**Comment by vinaypuppal** [comment]
@freecates I think the problem is in this line https://zeit.co/freecates/hello-next/fiabinrzin/source?h=222%3B34
Since you have custom server setup you need to have start script as 
```
"start": "NODE_ENV=production node server.js"
```
As you did not start custom server It gives a 404 error. That's because there is no such page `https://hello-next-fiabinrzin.now.sh/p/101236` to load from pages folder.

**Comment by freecates** [comment]
@vinaypuppal Thanks a lot. So obvious that I din't pay attention that the start script must be modified in order to take care of the custom routes.

Again, thanks a lot.
