### ISSUE TITLE
Silently replacing a URL

### ISSUE THREAD

**Issue by SBoudrias** [zeit/next.js#1938]
When calling `Router.replace()`, I'd like to update the URL without reloading the page (or call `getInitialProps` again).

When rendering on the server, we're sometime fetching defaults parameters. Once the page reach the browser, we'd like to update the query to match the default parameters that were selected in order to ensure reloading/sharing the page will use the same parameters.

Allowing silent url change would allow us to skip server-side redirect to the final URL improving load time.

**Comment by timneutkens** [comment]
Please see https://github.com/zeit/next.js#shallow-routing 👍

**Comment by SBoudrias** [comment]
That works, thanks a lot!

**Comment by vladka** [comment]
But shallow routing still calls render method on the page.
And the second problem, that shallow routing restricted only to the same page.

**Comment by mschinis** [comment]
@vladka did you end up finding a solution for your use case? I have the exact same problem

**Comment by vladka** [comment]
@mschinis . It is working, but NOT in a DEVelopment mode. If you run your app in a production mode ("npm run build" and "npm start"), then everything is OK (pages' shouldComponentUpdate is called properly). See https://github.com/zeit/next.js/issues/2935
```
 shouldComponentUpdate (nextProps, nextState) {
    //Issue:  this not called in  dev mode , see https://github.com/zeit/next.js/issues/2935
    console.log('comparing app');
    return false;
  }
```
So, in my case I dont' care about it.

**Comment by mschinis** [comment]
thanks @vladka. the above should ideally run the same on both development and production though.

**Comment by devmetal** [comment]
Guys, pls help me! :( The shallow router push is simply not working in production! When i run it in dev mode, its fine. 

```javascript
handleChange = (value) => {
    const href = `/?feed=${value}`;
    const as = href;
    Router.push(href, as, { shallow: true });
  };
```

In the render method, i use a material ui controlled component, that has a "value" based on the router.query.feed variable. When i stand on / route, and i start the switching links via handleChange event handler method, its fine, but, if i stand on /?feed=1, and i reload, and i click some link (who trigger the handleChange), the render method, the componentWillReceiveProps, the shouldComponentUpdate never run again! No errors, no feedback, its simply not working :( I use nextjs likely, i loved it, but i don't know, i try to figure out what happens by 3 days :/ Pls, pls help :( 

And oh yes, when i play with it on dev environment, its totally working fine :/

**Comment by SBoudrias** [comment]
@devmetal looks like an issue with `shouldComponentUpdate`. Important thing to know is that in dev mode these functions aren't called because of limitations of the hot reloading functionality.

I'd say run in production mode locally and add some logging to your functions.

**Comment by devmetal** [comment]
@SBoudrias Hi, i tried of course, i log evry move, but in production, the shouldComponentUpdate runs 1 time, and after never again. (Also in the chrome the react developer tool are red, because its say: This page includes an extra development build of React, but i build and run it with NODE_ENV=production) Anyway, i use withRouter, if its help but i checked the code of this HOC, and don't see any special thing. Just dont get it, why the route change in the browser, but the component not updating in prod :( Thank you for help

**Comment by devmetal** [comment]
@SBoudrias Hi, i found a workaround. I don't know what cause my original problem, but i find a solution that may help us to further investigations. Maybe i was wrong a whole time and this is the actually behavior that we expect.

So, the child component, call now for example <Foo> isn't a root level component, so the <Foo> not in the pages. It just wrapped a HOC, withRouter. Also in the <Home> component is wrapped the withData HOC from apollo example. The <Home> has a url property by default from the server, and when somewhere in the hierarchy, i call the Router.push(..., ..., { shallow: true }), actually nothing else, but the Home component updating. This led me to workaround, i have to propagate the query parameter from <Home> to <Foo> and now the thing is working as i expect, but the solution is not 100% for me. 

So, this is the expected behavior or its some strange issue with next?
