### ISSUE TITLE
[Question] styled components or styled jsx

### ISSUE THREAD

**Issue by MarcMagnin** [zeit/next.js#1952]
Hi,

I'v started to investigate around styling but I can't figure out which one to use.
Any recommendation is welcome!

Regards,
Marc

**Comment by timneutkens** [comment]
@MarcMagnin https://github.com/zeit/next.js#built-in-css-support obviously we recommend styled-jsx 😄  github.com/zeit/styled-jsx

**Comment by sedubois** [comment]
@timneutkens styled-jsx doesn't seem to be maintained very actively. Do you know what are the plans behind? And what are the pros/cons between styled-jsx and styled-components v2?

**Comment by MarcMagnin** [comment]
Cheers guys, good question @sedubois cheers!

**Comment by thierryc** [comment]
I use styled-jsx. It is very well integrated into Next. styled-components can be a good alternative too. More complexe. I like the styled-jsx simplicity. Good Code.

**Comment by jaydenseric** [comment]
Styled Components can handle single element components such as `img` easy-peasy, but styled-jsx always needs a container that is capable of holding children for the style element. See https://github.com/zeit/styled-jsx/issues/169. If you are fine with that limitation, styled-jsx is easier to add to existing components, is much less complex and therefore easier on bundle size.

**Comment by arunoda** [comment]
Closing this since this is not exactly a question. But feel free to discuss more :)

**Comment by skumblue** [comment]
What do you think about that used both together? 🤔

**Comment by julmot** [comment]
@MarcMagnin For those of you deciding this today: I'm going to use styled-components. Here are my reasons:

1. Nesting isn't supported by styled-jsx:
![nesting-styled-jsx](https://user-images.githubusercontent.com/8310677/35672759-cb9fec2c-073f-11e8-98fc-0c27037341f6.png)
The workaround would be to use the [styled-jsx-plugin](https://github.com/giuseppeg/styled-jsx-plugin-sass). However, as the description states:
![proof-of-concept](https://user-images.githubusercontent.com/8310677/35672848-148ce58e-0740-11e8-8a31-772a5786c120.png)
And due to the fact that there are only 23 stars, it's likely that they are bugs. So I would not use this in production.
2. There's no PHPStorm/Webstorm syntax support. Either you'd have to say the editor that things inside `<style>` is CSS every time or add comments above: `{ /*language=CSS*/ }` ([ref](https://github.com/zeit/styled-jsx#webstormidea)).
3. Either you need to blow up your render function by the large `<style>` contents or you can separate it using [this technique](https://github.com/zeit/styled-jsx#keeping-css-in-separate-files):
![topic](https://user-images.githubusercontent.com/8310677/35673059-a8f3514a-0740-11e8-904d-153d062d6318.png)
However, this also means you need to declare your styles somewhere and always create the element AND the styled in the JSX. With styled-components you just need to declare your styled and the component, not declare `<style>` once again

**Comment by MarcMagnin** [comment]
@julmot I've parked it a bit and I'll come back to it soon so I'm very grateful you gave your feedback!!
I've look around and heard about [JSS](https://github.com/cssinjs/jss), any thought on that one?

**Comment by julmot** [comment]
@MarcMagnin Yes I though about it but won't use it as it's basically JSON and not really for this use case.
