### ISSUE TITLE
Can't use console.log and have duplicate script tags since upgrading to 2.3.1

### ISSUE THREAD

**Issue by mannyreds11** [zeit/next.js#2040]
I can’t see any console.log placed on my component methods after upgrading to 2.3.1 when using npm run dev.

We’re using a custom `_document.js` and previously included `<NextScript />`.
We removed `<NextScript />` because we noticed it was duplicating the inclusion of Next scripts (e.g. app.js) on the page. After removing it I can’t do console.log on client side when running in development mode.

**Comment by khrome83** [comment]
I work with @mannyreds11 - Remove `<NextScript />` does more than just impact `console.log()`, it also does not run any code that was present in our page or `app.js` files. In other words, we really need it.

Looking at `view source`, we do see two sets of <link as="script"> tags though. One set in the head that is added without having `<NextScript />`, other other set is in the body before the close body tag because that is where `<NextScript />` is used.

**Comment by arunoda** [comment]
@khrome83 first one is a way to preload scripts. It's not duplicate. Check the type of the tags.
You must use `<NextScript />`

**Comment by khrome83** [comment]
@arunoda - yeah i miss read it. Thank you for the reply. That did solve our problem.
