### ISSUE TITLE
Example with-jest chokes on JSX syntax

### ISSUE THREAD

**Issue by bryandowning** [zeit/next.js#2052]
I'm running into a similar problem described in #1273. Jest does run, but it fails on the JSX syntax as if it isn't passing through babel.

From the `examples/with-jest` directory, I ran `yarn`, then `yarn test`. This is the output I'm getting:

```
$ yarn test
yarn test v0.24.5
$ jest
 FAIL  __tests__/index.test.js
  ● Test suite failed to run

    /bryan.lo/test/next-js-framework/examples/with-jest/__tests__/index.test.js: Unexpected token (11:24)
         9 | describe('With Enzyme', () => {

        10 |   it('App shows "Hello world!"', () => {
      > 11 |     const app = shallow(<App />)
           |                         ^
        12 |
        13 |     expect(app.find('p').text()).toEqual('Hello World!')
        14 |   })
```

Running `sudo yarn test` works.

I also ran `brew uninstall watchman` (as suggested in #1273), but that didn't help.

I'm using node version 6.10.3 with `n` and have verified that my user owns `/usr/local/bin/node`

I have no idea what's going on here, as this seemed to be working a few days ago. The only thing I can think of that might have impacted this is that I just updated macOS to version 10.12.5 yesterday.

Note that also `yarn build` fails with similar errors.

Later that day...

I finally found a fix for this. I changed the `.babelrc` in the example to:
```
{
  "presets": [
    ["env", { "modules": "commonjs" }],
    "next/babel"
  ]
}
```

Then everything started working again without needing `sudo`. Any ideas what's going on here?

**Comment by arunoda** [comment]
With this, when your app is running you don't get the webpack's tree shaking support. But I really can't reproduce this issue.

**Comment by manovotny** [comment]
I got bit by this yesterday when trying out the `with-jest` example, which gave me the major sads. 😢 

What's somewhat helpful in this situation is that my work machine ***does not*** work, but my personal machine ***does*** work. If I can figure out the difference between the two machines, perhaps we can fix this issue for good.

So I began some troubleshooting...

### Environment 

Both machines are using:

* macOS Sierra 10.12.6
* node v6.11.1 (using [nvm](https://github.com/creationix/nvm) to install)
* zsh via [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh)
* [watchman](https://facebook.github.io/watchman/) is ***not*** installed
* `npm` as the installer / runner (I prefer `yarn`, but trying to eliminate points of failure)
* the latest from `v3-beta` (technically 65ff72aadaa67b6280b376eaea770c562b825389)

### Steps to Reproduce

1. `git clone git@github.com:zeit/next.js.git`
1. `cd next.js/examples/with-jest`
1. `npm i`
1. `npm test`

```
❯ npm test

> with-jest@1.0.0 test /Users/mnovotny/Developer/next.js/examples/with-jest
> jest

 FAIL  __tests__/index.test.js
  ● Test suite failed to run

    /Users/mnovotny/Developer/next.js/examples/with-jest/__tests__/index.test.js: Unexpected token (11:24)
         9 | describe('With Enzyme', () => {
        10 |   it('App shows "Hello world!"', () => {
      > 11 |     const app = shallow(<App />)
           |                         ^
        12 | 
        13 |     expect(app.find('p').text()).toEqual('Hello World!')
        14 |   })

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.228s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

### Attempted Fixes

I've tried the following things to fix the problem without success:

* Again, [watchman](https://facebook.github.io/watchman/) is ***not*** installed
* Deleting the babel cache, ie. `.babel.json`, from my home directory
* Run `sudo npm test` as @bryandowning mentioned above, which does work, but is not what I'd consider a fix

Since I have one working machine and one "broke machine, I am totally open to suggestions of other things to try if someone has some more ideas...

**Comment by manovotny** [comment]
Welp... I figured out my problem!

A coworker had me put `export NODE_ENV="localhost"` in my `.bash_profile` when working around  an auth issue a few months back and I never removed it. 

Since the `.babelrc` looks for a `NODE_ENV` of `test` when running Jest, it was failing because `NODE_ENV` was getting overridden with `localhost`. 

🤦‍♂️ 

My apologies for the false alarm. Perhaps my boneheadedness can help someone else if they experience the same problem.
