### ISSUE TITLE
next export - more options

### ISSUE THREAD

**Issue by floydprice** [zeit/next.js#2111]
next export is an awesome extension to the toolchain, however id love to see some more options added:

- Option to set the '_next' folder - would make integration with Cordova easier
- Option to force the output to copy when exporting to another folder (rather than the default 'out' folder).

Excellent work so far though!

**Comment by frol** [comment]
You can use `assetPrefix` config (in the `next.config.js`) to specify the folder in which `_next` will be searched, e.g. `assetPrefix: '/assets/'`, and manually move the `build/_next` folder to the `build/assets/_next`.

**Comment by floydprice** [comment]
Its not the location of the '_next' folder i was keen to configure it was the '_next' folder itself, Cordova for Android ignores folder with a prefix of underscore (see bug [here](https://issuetracker.google.com/issues/36911326)) and while this is relitivly easy to overcome with some hacks its not ideal.

**Comment by arunoda** [comment]
Actually, it's hard to change at this moment.
Basically using `_` is not a bad idea at all. We use `_` to mention it's something internal for Next.js.
We can't use /next because, it might be a URL where the user want to put an actual page.

Since that's a bug in Cordova/Android you need to go for hacks.
