### ISSUE TITLE
deferred external javascript run twice.

### ISSUE THREAD

**Issue by hckrmoon** [zeit/next.js#2165]
Hello. 

My code is like this

```javascript
render() {
  return (
    <div>
      <Head>
        <script defer src="/lib/js/external.js"></script>
      </Head>

       { ... }
    </div>
  );
}
```

let's say the code `console.log('external')` is in it external.js. And the console says 'external' twice.
Without defer attribute it never run twice.

**Comment by arunoda** [comment]
This is not a place to do this.
Do this in our custom document or use pure JS loader like https://www.npmjs.com/package/load-script
And even if you are doing that make sure to cache the output. Otherwise it'll keep loading every time you load the ^^^ page.

Always try to import these modules via NPM `import`
