### ISSUE TITLE
iframe example

### ISSUE THREAD

**Issue by moroshko** [zeit/next.js#2295]
Can we have an example of rendering a component into an `iframe`, styling it, and including a script?

**Comment by serle** [comment]
I'm using styled-components
Here is my content page component

```
const Content = styled.iframe`
    width: 100%;
    height: calc(100% - 100px);
    border: none;
    backgroundColor: transparent;
    overflow: hidden;
`;
```
Then I render the iframe based on a dynamic page state variable:

`<Content src={`/${this.state.page}`}/>`

So my main menu changes the state variable, when different options are clicked. I found this better than the using next/link which caused the top menu bar to flicker on each page load.

**Comment by moroshko** [comment]
Is `this.state.page` a real page that resides in the `pages` directory?
I don't want users to go directly to this page.

**Comment by serle** [comment]
Its a string which is used to set the iframe src attribute on the client, which then causes the page to re-render and the new iframe to load. You can execute any logic on the client side state change, does not need to change the iframe source. Since I assume you want the iframe to load a "next" page component, the page would need to be in your pages directory.

**Comment by timneutkens** [comment]
@moroshko feel free to send a PR ❤️
