### ISSUE TITLE
Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "StringLiteral" when i config  with-universal-configuration

### ISSUE THREAD

**Issue by kenshero** [zeit/next.js#2297]
I follow this. https://github.com/zeit/next.js/tree/v3-beta/examples/with-universal-configuration

but i use custom server. when i run node server.js 
error this. 
Module build failed: TypeError: path/to/xxx
Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "StringLiteral"

**Comment by BijayRai** [comment]
I followed this : [https://gist.github.com/ledfusion/7854fdc440300d162f7759a5a5c1e04a#file-config-default-js](Example of a dev/production/env config system for NodeJS
Raw)

and run : `npm run dev`
then i got same error like : 
` property of MemberExpression expected node to be of a type ["Identifier"] but instead got "StringLiteral"`

@kenshero  How did you solve your problem ? And why this issue is closed without any answers?

**Comment by kenshero** [comment]
@BijayRai i still cannot solve. I don't know why this issue is closed.

Now I go declare enviroment variable on server.js

**Comment by BijayRai** [comment]
@kenshero ohh so sorry to know... :( 
following  https://github.com/zeit/next.js/tree/v3-beta/examples/with-universal-configuration
i can do something like this only

```
const prod = 'production' === process.env.NODE_ENV

module.exports = {
    'process.env.API_URL': prod ? 'http://api.server.com' : 'http://api.local.com/web',
}
```

This solve only cases for production and development . 
What if i want more  custom production mode env!?
 _just eg_(QATEST) . custom development mode
For this how to write config for this? 

Do you ve any idea @kenshero ?

**Comment by kenshero** [comment]
@BijayRai I no idea. I use code something like 
```
const prod = 'production' === process.env.NODE_ENV
process.env.API_URL: prod ? 'http://api.server.com' : 'window.location.hostname'
```
on server.js But problem I found . process.env not work when client side render. I use window.location.hostname instead when process.env is undefined
