### ISSUE TITLE
Document `next-prefetch`

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#24]
`next-prefetch` is a substitute for `<Link />` (builds on top of it) that:
- By default prefetches the given component using a `ServiceWorker`
- It would have an option `prefetch={false}` if you want to turn it off
- It would have an option `fallbackWorker={true}` to fallback to a web worker if the browser doesn't support service workers.

This is the technique that we use at ▲ZEIT to make everything really speedy.
We need to extract it out of our impl or someone can write this from scratch.

Installing a service worker is pretty intrusive, so I don't think this is something we want in core. We can write it as a separate module.

**Comment by pranaygp** [comment]
I'd like to help with this. Has there been a decision on whether it's going to be rewritten or if it's gonna be extracted from the zeit.co implementation? If it needs to be written from scratch, we should create a new repo for this to start working on this implementation.

**Comment by sedubois** [comment]
That would be fantastic!

React-boilerplate seems to be doing [similar](https://github.com/mxstbr/react-boilerplate/blob/3fdad6a888b68e2c538dfcd52f4594fea7b9e4d4/docs/general/README.md#offline-first), and it falls back to AppCache on older browsers. It seems to rely on Webpack [`offline-plugin`](https://github.com/NekR/offline-plugin), would it help here?

It seems like page prefetching and caching can be a great feature to not only provide speedier page loads, but even provide offline availability? I think offering "offline" and "low-bandwidth" abilities could make Next.js quite attractive, especially with the huge amount of users in emerging markets. In combination with e.g GraphQL, it could compete against Firebase which has an offline feature.

To make things straightforward to the user, could prefetching be offered out of the box so that users can see its full potential right away, like offline-plugin does? (If necessary, allow to disable through configuration.)

**Comment by sedubois** [comment]
Also see [Create React PWA](https://github.com/jeffposnick/create-react-pwa) based on Create-React-App, to create progressive web apps. It also features an "add to home screen" link (see [blog post](https://medium.com/dev-channel/create-react-pwa-7b69425ffa86#.g8rhbn9mt) with short demo video).

Not saying all of this should be implemented right away, but definitely prefetching/caching would help with all of that.

**Comment by pranaygp** [comment]
@sedubois that makes sense. Let me go through those and start a new repo on my personal GitHub. We can migrate that repo into the Zeit organisation once it looks good. I'll definitely like to that repo here once I start it so we can keep everyone working on it up to date :)

**Comment by pranaygp** [comment]
@sedubois That sounds perfect. Let me go through those resources and begin working on this. **Anyone else who wants to help, that'd be awesome**

**Comment by ugiacoman** [comment]
Exactly what is being discussed right now at https://developer.chrome.com/devsummit/

**Comment by sedubois** [comment]
Thanks @ugiacoman, is there any way to view the talk or related article?

**Comment by ugiacoman** [comment]
It looks like they haven't archived the stream yet. A few good pieces that I have read involves service workers. It seems incredibly easy, and it would be incredible if `next` allowed you to select assets and URLs to store via the service workers. The benefits are 💯  awesome. Here are the links below:

[Pre-fetching with Service Workers](https://developers.google.com/web/fundamentals/getting-started/primers/service-workers)
[Push Notifications](https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web)
[PWA Checklist](https://developers.google.com/web/progressive-web-apps/checklist)

**Comment by pranaygp** [comment]
This definitely seems like an exciting way forward in terms af setting a standard for future JS frameworks to implement.

**Comment by jbaxleyiii** [comment]
@rauchg how can I help with this? It's a big want for my team 😉

**Comment by arunoda** [comment]
Guys, I did a PR implementing page prefetching.
Have a look at here: https://github.com/zeit/next.js/pull/375

**Comment by sedubois** [comment]
@arunoda any future plan for fallback to AppCache?

**Comment by arunoda** [comment]
@sedubois we will add some fallback support with AppCache or something similar.

**Comment by philcockfield** [comment]
Any idea on whether this will make it into a release of next.js anytime soon?

**Comment by rauchg** [comment]
It's already in master
