### ISSUE TITLE
[Question] How do I configure a different root directory?

### ISSUE THREAD

**Issue by Industrial** [zeit/next.js#2415]
Hi!

I am using a compile-to-js language and I always have a gulp setup with a `src/` and `build/` directory for a node project.

Since `src/` contains my non-js code, the `build/` dir should be the root directory of next.js to start out at.

How do I configure that and, if it's not possible now, would this be an option for next.js in the future?

**Comment by kachkaev** [comment]
Hi @Industrial. What was the solution?

**Comment by Industrial** [comment]
I rewrote my stack to ES6.

**Comment by kachkaev** [comment]
Right, so I guess you keep your source files in the project root dir now. I've moved to ES6 some time ago, but am still trying to keep the sources in the `src` subdir, even in node.js apps that require no transpilation. This makes it easier to configure linters, Dockerfiles or CI, because the sources do not mix up with other project stuff (e.g. markdowns, linter configs, gitignore files etc.).

Just started with Next.js and found your issue via google :–)
