### ISSUE TITLE
Why split the Next server and a websocket server in a production environment?

### ISSUE THREAD

**Issue by tashburn** [zeit/next.js#2457]
If there's a better place to ask this question, please let me know.

In [this example](https://github.com/zeit/next.js/tree/v3-beta/examples/with-socket.io), it says 

> "The example combine the WebSocket server with the Next server, in a production application you should split them as different services."

Why?

**Comment by sergiodxa** [comment]
Because React render synchronously server side, if you have both services in the same app every time a user access to your app it's going to use the whole node app to render and the websocket it's not going to work in real time.

Also if you have your next app, your api and your websocket server as different services you can scale them individually as you need.

**Comment by tashburn** [comment]
@sergiodxa thanks
