### ISSUE TITLE
Can't get protocol in server-side rendering

### ISSUE THREAD

**Issue by hank7444** [zeit/next.js#2469]
Hi All!

My question is i need to get origin dynamically, 
I try `req.headers` and I got:

![image](https://user-images.githubusercontent.com/4727090/27859338-043917ba-61ab-11e7-88e0-507b09f612c8.png)

Yes!,  I got host, but I also need the protocol, which needs to concat with host to create new api path. I browsed All req properties but I got nothing. Have any good idea? thx a lot!

**Comment by quentin-sommer** [comment]
I think next use the express request so you should find it here: http://expressjs.com/fr/api.html#req.protocol

**Comment by timneutkens** [comment]
@quentin-sommer we don't use express.

**Comment by quentin-sommer** [comment]
Well that's my bad!

**Comment by quentin-sommer** [comment]
@hank7444 I dug in the req object, it has `_parsedOriginalUrl` and `_parsedUrl` fields which are both of type `Url`. The structure is as follows:
```
{
     protocol: null,
     slashes: null,
     auth: null,
     host: null,
     port: null,
     hostname: null,
     hash: null,
     search: null,
     query: null,
     pathname: '/page',
     path: '/page',
     href: '/page',
     _raw: '/page'
 }
```

I tested it only on localhost and as you see most of the fields are blank... I don't know if it's because I use a wrapper Expressjs server that calls next or if it's because of the localhost. Maybe you'll get what you want here

**Comment by timneutkens** [comment]
It's safe to assume it's always `http` and the SSL termination has to be done by a reverse proxy like Nginx. These set the `X-Forwarded-Proto` header which you could use.

**Comment by franciscopuyo** [comment]
I managed to do that with following line 
`const protocol = req.headers.referer.split('://')[0]`

It looks dirty anyway
