### ISSUE TITLE
Very slow initial page rendering and after app inactivity

### ISSUE THREAD

**Issue by jackmatrix** [zeit/next.js#2568]
I am in dev mode and have noticed that the initial rendering of each page was quite slow. When i click on Link to navigate to another page. It may take several seconds. But after a page has been visited once, the app become fluid a quite reactive. Also, i've noticed it become slow agin after a certain period of inactivity, and need to visit each page again to get the app fluid and fast.

Is this normal ?

**Comment by supra28** [comment]
please see #2487

**Comment by sergiodxa** [comment]
In dev mode next only build the currently active page, if you navigate to another page it would build it before the page change, that's way us slow. And about the inactivity is because the same reason, it needs to build the page again because if a page is not active Next erase the built files.

This allow you to have a big app with a lot of pages and reduce the initial build time when running `next` and the amount of memory consumed by webpack while building because it will only watch the files required in the current page.

**Comment by timneutkens** [comment]
Tracking this in #2487.

**Comment by agionfriddo** [comment]
I had been looking for this solution for weeks!!!
