### ISSUE TITLE
Next.js still requires too much RAM for huge sites

### ISSUE THREAD

**Issue by leo** [zeit/next.js#2574]
As you can see in [this issue](https://github.com/leo/site/issues/30), the package still needs to much RAM when doing a full cold build of a huge site (like [mine](https://github.com/leo/site)). We need to improve this! 😊 

You can use [these](https://github.com/leo/site) steps and `npm run build` instead of `npm run dev`.

**Comment by arunoda** [comment]
I tested. It's not Next.js

You've used babili plugin and it's causing a lot of issues (CPU, mem and time)
Try commenting that and build it again.

You can't use uglify because some of your code uses ES6. So, try to find that module(s) replace them with some other alternatives. Then you can use uglify too.

**Comment by leo** [comment]
Looks like we'll have to switch to the latest uglify 😊
