### ISSUE TITLE
using toLocaleString in markup throws checksum error

### ISSUE THREAD

**Issue by iamsoorena** [zeit/next.js#2590]
Here is the problem I have a piece of code inside one of my components:
`                      <span>{info.minPrice.toLocaleString('fa')} تومان به بالا </span>
`

when I run the application I get this error:
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. 
This generally means that you are using server rendering and the markup generated on 
the server was not what the client was expecting. React injected new markup to compensate
 which works but you have lost many of the benefits of server rendering. Instead, figure out 
why the markup being generated is different on the client or server:
 (client) react-text: 1921 -->۲٬۵۳۴٬۹۰۰<!-- /react
 (server) react-text: 1921 -->2,534,900<!-- /react
```
nothing else is involved in this problem if I simply remove .toLocaleString function It will work without any errors.

**Comment by timneutkens** [comment]
Can you please provide a way to reproduce?

**Comment by iamsoorena** [comment]
sure, just make a new page in a next js project and drop this code:
```import React from 'react'
export default class extends React.Component {

  render () {
    return <div>
      <span>{(16).toLocaleString('fa')}</span>
    </div>
  }
}
```

you will see the error I'm talking about.

**Comment by iamsoorena** [comment]
@timneutkens I would be glad to hear back from you.

**Comment by Blistok** [comment]
@iamsoorena This is not Next.js related bug. It has to do with Node's poor internationalization support (node had intl issues since always); so what's going on in your case is that server side you render number `16`:
<img width="350" alt="node-fa" src="https://user-images.githubusercontent.com/9505695/28487043-765d5398-6e57-11e7-858d-5682679200c0.png">
while client side you render ۱۶.

Assuming you are dealing only with Farsi, I think your best bet would be to use [persianjs](https://www.npmjs.com/package/persianjs) package, and then you can have something like:
```
import React from 'react';
import persianJs from 'persianjs';

export default () => (
  <div>
    <span>{persianJs('16').englishNumber().toString()}</span>
  </div>
);
```

**Comment by iamsoorena** [comment]
Thanks a lot @Blistok .
