### ISSUE TITLE
Unable to retrieve value passed by getInitialProps() in a NextJS functional component

### ISSUE THREAD

**Issue by amitsch666** [zeit/next.js#2723]
I have a stateless, functional component in NextJS where I'm trying to initialize some data upon load using `getInitialProps()`:

```
const LoginModal = props => (
  <p>{props.testdata}</p>
);

LoginModal.getInitialProps = () => ({ testdata: 'Some string value' });

export default LoginModal;
```
However, no matter what I do, the modal always renders with a blank `<p></p>`. Why isn't the value returned by `getInitialProps()` being read by the component?

**Comment by maxbeatty** [comment]
I know sometimes when posting sample code typos creep in, but did you mean `testdata` in `getInitialProps` and then just `test` instead of `testdata` in the `<p>`?

[This test](https://github.com/zeit/next.js/blob/v3-beta/test/integration/static/pages/get-initial-props-with-no-query.js) is almost identical to what you're trying to do so hopefully that helps.

**Comment by sergiodxa** [comment]
Is that component a page or a simple component used inside a page?

**Comment by amitsch666** [comment]
Oops, thanks for pointing out the typo. Corrected.

**Comment by amitsch666** [comment]
@sergiodxa: It's a plain stateless component. A modal to be precise.

**Comment by timneutkens** [comment]
Only top level pages support `getInitialProps`, so you'll have to pass the data down.

**Comment by amitsch666** [comment]
@timneutkens: Ahh, suspected that. Thanks for confirming.

**Comment by timneutkens** [comment]
❤️
