### ISSUE TITLE
Example Firebase Hosting: Package.json should use "postinstall" hock to make installs in sub directories 

### ISSUE THREAD

**Issue by D1no** [zeit/next.js#2763]
@jthegedus 
https://github.com/zeit/next.js/blob/ba65b07dffd02a8fe23e22b2ceda6771efd4d129/examples/with-firebase-hosting/package.json#L6

Re-Installs on every run is really quite a design flaw that obfuscates the actually quite straight forward example. In that case, a simply `npm install` in the root would take care of everything if the install script would be aggregated there: https://docs.npmjs.com/misc/scripts#examples

**Comment by jthegedus** [comment]
Interesting point. I'll clean the `package.json` up a bit.

**Comment by D1no** [comment]
just fyi, I set everything to use yarn and renamed the `app` folder to `src`. Now it looks like this

```json
  "scripts": {
    "postinstall": "cd src && yarn install && cd ../functions && yarn install && cd ..",
    "next": "cd src && yarn run dev",
    "build": "cd src && yarn run build",
    "serve": "firebase serve",
    "deploy": "firebase deploy"
  },
```

Currently I am looking how to still include a static folder inside the public folder, that does not get rewritten. Resources (such as simple HTML & files) that i.e. the native app can consume.

Do you have an idea, how to exclude i.e. `/static/` from the rewrite rules?

**Comment by D1no** [comment]
ah, found it already ([source](https://firebase.google.com/docs/hosting/url-redirects-rewrites))
> A rewrite rule is only applied if a file or folder does not exist at the specified source, and returns the actual content of the file at the destination instead of an HTTP redirect.

God I love firebase. Great work on figuring out the redirect handling!

**Comment by jthegedus** [comment]
I do personally use Yarn (as you can tell from the associated blog post) and a different folder structure, but all examples in this repo and https://github.com/firebase/functions-samples use npm and a more flat structure so I just changed that for consistency.

Re your `package.json`:
`firebase serve` and `firebase deploy` always require the Next.js app to be built beforehand hence why I had `build` run in `pre` scripts. If a fresh build is not created each time you'll end up using an old build output.

Another caveat about building the Next.js site not in a Firebase functions sub-dir is that they use separate `package.json` files and any dependencies used in the Next.js site will need to be added to the Firebase functions `package.json` too. Using Yarn workspaces should solve this, but again, I didn't want to impose a different package manager in the examples.

**Comment by D1no** [comment]
No the windows reference was referencing to our project, so that the snippet I posted would have to be checked/addressed. Meanwhile, after running a few performance tests, the issue of firebase cold function starts and that functions are only hosted on google servers in the US, lead us to chose to go for next.js static site export (before that, we used create-react-app to achieve the same).

Further down the road we need to enrich sub pages with dynamic content for which we may go with an hybrid approach... but than serve the next app from a server suited; potentially leveraging firebase rewrites. Also, rendering via functions is quite a money burner to the firebase pricing as it seems 😶

**Comment by jthegedus** [comment]
A right, I thought you were referring to a PR updating the npm scripts to what you suggested.

It is an important note that Cloud Functions are still in Beta. I'm not sure of the implementation, but I believe the idea is that  Google servers will monitor usage patterns and pre-warm the Function for use at those times, so I expect even after Cloud Functions leaves Beta that the cold start times would improve after the app gets regular usage. It's also important to note here that since the app is on a single Cloud Function it's only cold once per visit to the page if it's not already warm.

That aside, I too have been using Next.js statis export over CRA for my projects, it's easier to know one framework for both static and SSR. Not to mention that Babel and Webpack are extendible.

On pricing, I'm also intending on writing about the usage of the Google CDN caching with an SSR app on Cloud Functions. I imagine even caching common (not user specific) pages would reduce the cost a lot.

All that said, thanks for the feedback on the npm scripts. I'll look into simplifying the examples here and on other repos with your suggestions.

**Comment by D1no** [comment]
I look forward on your caching idea :)
