### ISSUE TITLE
Can i server normal react application with nextjs

### ISSUE THREAD

**Issue by MBehtemam** [zeit/next.js#2813]
Hi, i have an normal react application that created with `create-react-app` and now i serve it with express js. my question is can i server my react application with next js inside of express?

**Comment by sergiodxa** [comment]
You can use Next.js [inside a Express app](https://github.com/zeit/next.js/tree/master/examples/custom-server-express) but you probably will need to change things in your React app because Next.js have his own router (if you used React Router you need to drop it) also if you don't used a CSS in JS solution you need to configure Next.js to support it or migrate to some CSS in JS (check https://github.com/zeit/next.js#faq).

**Comment by timneutkens** [comment]
👌
