### ISSUE TITLE
Query always empty on static exports

### ISSUE THREAD

**Issue by lucasconstantino** [zeit/next.js#2910]
When using static export, `__NEXT_DATA__` is injected on each page's _html_. This object contains a predefined _pathname_ and _query object_. When pages use query strings to fetch data on page load, the query string is never provided to the page on first load.

## Expected Behavior
Next should probably check on the URL on page load to grab any query strings and update the _url_ object provided to page components.

## Current Behavior
Next provides only the query parameters described in the _next.config.js_ via `exportPathMap`, ignoring any additional parameters present in the URL.

## Steps to Reproduce (for bugs)
1. Create a page that prints the _url.query_ object;
2. Add your page to `exportPathMap` (i.e. `'/': { page: '/' }`);
3. Make a static export;
4. Serve the static directory with a static server such as [http-server](https://www.npmjs.com/package/http-server)
5. Access your page, but add an additional query string to the URL.

## Context
I'm trying to fetch some data based on the values provided in the query string, but the query object comes empty.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    ^3.2.1     |

**Comment by timneutkens** [comment]
This is the expected behaviour. you need to pass the querystring beforehand to render correctly. On the client side you can use `componentDidMount()` and just read `window.location` for the value.

**Comment by thmsmlr** [comment]
@timneutkens is there a rationale for this behavior? `window.location` totally works for my purposes. I'm just curious

**Comment by hofnarwillie** [comment]
@timneutkens is this expected behaviour documented anywhere?

**Comment by PetrSnobelt** [comment]
It is surprising and confusing that `params.url.asPath` works correctly, but `params.url.query` don't

**Comment by timneutkens** [comment]
When using `next export` you are **exporting HTML at build time**. Meaning all variables, including the querystring, pathname and asPath have to be predefined in `exportPathMap`, and `next export` will turn those into HTML files, by calling `getInitialProps` and writing the output of a server render to `<file>.html` " 

First render" as mentioned in the issue means: serving the HTML, and `getInitialProps` is not executed because it's a HTML file, not a dynamic Node.js server that can execute getInitialProps on the server side.

If you want that kind of behavior you're going to want to use a custom server + lru cache.

**Comment by NathanielHill** [comment]
@timneutkens This seems impossible using "route masking" in Now v2.

So, if you're doing something along the lines of `{ "src": "^/path/(.+)$", "dest": "/path?id=$1" }` then you don't get the querystring in `window.location`.

My solution is actually doing a `301` redirect to the path with the querystring and then using the History API in `componentDidMount()` to hide the querystring.

Is there a better way to handle this?
