### ISSUE TITLE
The role of NODE_ENV when starting next server for an export

### ISSUE THREAD

**Issue by herschel666** [zeit/next.js#2918]
Hi.

I struggled spawning the next server in the background & then running the export, because `./.next/BUILD_ID` was missing. Setting `NODE_ENV=production` fixed this. Is this a coincidence?

If not, I'd open a PR and add this info to the `## Static HTML export`-section of the `README.md`. :-)

Cheers.

**Comment by timneutkens** [comment]
What happens here is:

1. you do `next build`
2. you do `next` (or `node index.js`) without `NODE_ENV=production`
3. you do `next export`

What happens when you start Next in dev mode is that it clears `.next`.
So you should always `next build` and then `next export` after that. As documented in the readme.
