### ISSUE TITLE
How about React's license reform?

### ISSUE THREAD

**Issue by farebord** [zeit/next.js#2956]
Is react license reform affects nextjs?

**Comment by sergiodxa** [comment]
React license is the same as always, is just that Apache Foundation made some new statements about it and it becomes popular again (it actually was a talk issue sometime ago)

About if it affects Next.js, it doesn't, the license affect you if you demand FB for any patent and you use React, then you lose the React license and can't use it anymore. Since Next.js is a framework is not affected, even if ZEIT is affected the framework could continue to use React.
