### ISSUE TITLE
How to use with-external-scoped-css example with SCSS

### ISSUE THREAD

**Issue by aviramga** [zeit/next.js#3053]
Hi,

I'm working with the with-external-scoped-css example and would like to covert the sass to scss. I've updated the .bablerc file to include scss but the bundle.css appears to be empty.

Could someone please help me with the exact steps to convert it to scss?
I've already looked at the other css related examples (including the global one) but I would really like to keep the scoped css solution.

Im using Next v4-beta.4
Thanks for the help!

**Comment by timneutkens** [comment]
cc @guidiego

**Comment by guidiego** [comment]
@aviramga did you change the `pre-processor.js`?? 

https://github.com/zeit/next.js/blob/7c908633cbdfcd158bf50c60cee16474948efdbd/examples/with-external-scoped-css/.babelrc#L3:L12

You can remove this line: `"preprocessCss": "./pre-processor.js"` or change the `indentedSyntax: true` to false!

**Comment by aviramga** [comment]
Works!!! THANK YOU! @guidiego !

Can you please explain why this works? I hate it to stay in the "magic" level :)

**Comment by timneutkens** [comment]
Going to close this, but @guidiego can most likely explain 😄

**Comment by aviramga** [comment]
Cool thanks! @guidiego please help :)

**Comment by timneutkens** [comment]
@aviramga Also be sure to join https://zeit.chat 😄

**Comment by guidiego** [comment]
@aviramga  Gonna go in parts: 

This example works with **any** pre-processor, the `pre-processor.js` file is used as a parser for you `.anything` files :)

The babel-plugin used to make this example works fine with **SCSS** and **LESS** without a necessity to create/use the `pre-processor.js` file, at least, I prefer to create this example to illustrate the possibility to make complex things. So this works because SCSS is the base language (as less) of this plugin :D When you remove the pre-processor and add the .scss files in pattern this will work as you expect. The other approach (indentedSyntax: true), is because the sass-core use it to understand if you want to work with a processor based on indent (sass) or the default (scss).

> Also, I cannot use fixed class names? (i.e className="some-class" ) and just use the same class name in my scss file?

Yeap, for what I remember (I use some plugins) you can add a `:global{ ... }` in it and add it to the processor to be appended with the other stuff 🤔  

CC: @timneutkens I opened a PR for link this issue in my example with a better explanation :)

**Comment by aviramga** [comment]
Thanks @guidiego for the amazing explanation! 

Where did you get the :global tip from?

**Comment by chhuang** [comment]
@aviramga `:global` is from [CSS Modules](https://github.com/css-modules/css-modules#exceptions).

> :global switches to global scope for the current selector respective identifier.

Maybe we need an example without CSS Modules.
