### ISSUE TITLE
Too many open issues to be taken seriously by enterprise

### ISSUE THREAD

**Issue by wesharehoodies** [zeit/next.js#3212]
Hello, big fan of Next. 

But-- there are too many issues open for any big company to adapt to Next.

Can we close some of the issues?  Also, can we close some of the PR's as well--limiting to around 15 open PR's max?

Yours truly,

Indrek

**Comment by sergiodxa** [comment]
I also think we have many issues open but if you check they are more about doubts or feature requests than bugs.

**Comment by wesharehoodies** [comment]
Wow that was quick!

Yep indeed, everything is fine and I'm not blaming anyone. But imo it's kinda bad press to see this many open issues. That was the first thing popped in my mind. 

Some of these are more than a year old. https://github.com/zeit/next.js/issues?page=10&q=is%3Aissue+is%3Aopen 

Let's get to work.

Indrek

**Comment by sergiodxa** [comment]
Personally I think is the opposite, a lot of issues means a lot of people using it or interested in a project. Check VSCode, they have more than 5000 issues, GH even show +5000 instead of the real amount!

![image](https://user-images.githubusercontent.com/1312018/32194214-bdd951c0-bd87-11e7-8807-577b9800e53f.png)

**Comment by wesharehoodies** [comment]
Fair point.

**Comment by jorge-autogravity** [comment]
I think this NextJS is too cool and advanced for Enterprise

**Comment by mattbrunetti** [comment]
@wesharehoodies Consider how active these issues and PRs are though.. (make sure you're "watch"ing the repo) 

Also, many of the issues are feature requests, and many are "help me with this please", which are much more positive that bug reports.

**Comment by timneutkens** [comment]
> we close some of the PR's as well--limiting to around 15 open PR's max?

It's not that simple. All open PRs are either things we still have to look into or things we have to work on to improve / expand 😄 

> But-- there are too many issues open for any big company to adapt to Next.

Like @sergiodxa mentioned most projects have at least 3 times more issues at this scale (almost 19K stars). Also note that github issues are an endless lifecycle which can't be tamed. There will always be issues popping up 😄. Most are feature requests like @mattbrunetti said.

I do agree that we should do a run through all issues to see if they're still relevant.

> there are too many issues open for any big company to adapt to Next.

To expand on this. On the contrary to what you're saying we're seeing great adoption across many different types of companies, from startups to large enterprises. People are even creating ecommerce experiences using Next 💯

Some examples:

npm - https://www.npmjs.com/search?q=next
Open Collective - https://opencollective.com
Netflix - https://jobs.netflix.com
Scale API - https://scaleapi.com
Avocode - https://avocode.com/
Institchu - https://www.institchu.com/design/shirt
Nike - tba
Deliveroo - tba

A while ago, before the v2 release, I made a list in this issue: https://github.com/zeit/next.js/issues/1458

**Comment by timneutkens** [comment]
In light of closing issues, feel free to close this one if your question is answered 😄 🙌

**Comment by cjhowe7** [comment]
Anyone else enjoying the irony of this issue? 🤣

**Comment by wesharehoodies** [comment]
Alright, fair ball play. Love you guys <3

**Comment by arunoda** [comment]
Just joining to the conversion.

I think measuring the project by the number of open issues is hard (when deciding good or bad). In our case, we have a higher number of open issues because of the following reasons.

* This is the only discussion forum other than Slack
* We also manage issues for examples 

Next.js is very crucial for us since we use it for our [web app](https://zeit.co) and for our[ Desktop client](https://github.com/zeit/now-desktop).

So, we are seriously serious about Next.js for sure :)

**Comment by timneutkens** [comment]
@wesharehoodies ❤️
