### ISSUE TITLE
With Apollo: Fetching client-side when using router.pathname

### ISSUE THREAD

**Issue by f2net** [zeit/next.js#3236]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
I expected the data fetching to happen server-side on first load and be cached

## Current Behavior
Data is fetched by the client (I see the network request) on first load

## Steps to Reproduce (for bugs)
1. Decorate an inner component (in my case, the header) with "withRouter"
2. Use router.pathname.
In my case `const activeItem = router.pathname` to set active item on menu
3. Now, using the lib of the with-apollo example (initApollo and withData) data is fetched client-side.

If I remove that line everything is ok and I don't see any client-side fetching.

Thank you,
Matteo

**Comment by timneutkens** [comment]
@ads1018

**Comment by simenbrekken** [comment]
If you're following the [with-apollo example](https://github.com/zeit/next.js/blob/canary/examples/with-apollo/lib/withData.js#L34) you'll need to include router in the context of `getDataFromTree` otherwise `withRouter` won't find the router in the context when rendering on the server.

I got it working using:

```js

**Comment by f2net** [comment]
Thank you! It works! :)

**Comment by ads1018** [comment]
@simenbrekken that's neat, I didn't know getDataFromTree accepted a second argument.
