### ISSUE TITLE
Canary idea: use whatwg-url instead of url

### ISSUE THREAD

**Issue by brikou** [zeit/next.js#3306]
https://github.com/defunctzombie/node-url has not been updated since 2 years and a standard is emerging with https://url.spec.whatwg.org/

We can already use this module https://github.com/jsdom/whatwg-url

WDYT ?

:)

**Comment by brikou** [comment]
The lib is quite fat, and ugligy behaviour broke as far as I tried

**Comment by alubbe** [comment]
In addition to https://github.com/zeit/next.js/issues/3056#issuecomment-346964213, it would be great if we could use window.URL instead of any dependency. That would help to bring the entire cost of using next down to something that is comparable to react-router (+ lazy loading + head.js).

I had a look at the source code and the two main use cases are
1) building urls out of utf8 strings (punycode) - window.URL supports this
2) extracting the query params - window.URL supports this (URL.searchParams)

Any reason not to use it in modern browsers and have babel select a polyfill depending on the build target?

**Comment by timneutkens** [comment]
`jsdom/whatwg-url` is about 10x bigger than `url` according to bundlephobia. 

I do agree that dropping the dependency would be neat, in favor of a browser native solution. Which we'll most likely do in the long term 👍
