### ISSUE TITLE
Android  webview  onCLick  is  no  work 

### ISSUE THREAD

**Issue by ckken** [zeit/next.js#335]
In  wechat  webview  js  alert  and  many  method  is no  work

**Comment by rauchg** [comment]
Please provide an example, more details, potentially a demo URL (you can use [now](https://now.sh) and re-open the issue.

**Comment by elgubenis** [comment]
I'm experiencing the same issue, on desktop chrome everything works as expected (json gets fetched 1st time (if no prefetch Link), but on android mobile chrome clicking a <Link> does always fetch the href url as if the default was not prevented, I guess it might be because next.js is listening on the click event of the generated a-tag, but not on touchstart, could that be it?

you can test that here: https://bitsafe.at just open it in chrome on android and you see the chrome progress bar on top when navigating

whats interesting though, on zeit.co that does not happen, not sure but that might be because you push to the router instead of using the <Link> component?

**Comment by elgubenis** [comment]
i tried with adding onTouchStart to https://github.com/zeit/next.js/blob/master/lib/link.js#L116 and that fixes the issue.
