### ISSUE TITLE
[SW-Precache] Total precache size is about 0 B for 0 resources.

### ISSUE THREAD

**Issue by Tuizi** [zeit/next.js#3387]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

The SW-Precache demo should precache all .next folder's ressources?

## Current Behavior

The SW-Precache demo cache nothing.

## Steps to Reproduce (for bugs)

1. Clone the repo
2. Go in the demo's folder **with-sw-precache**
3. Run `npm build`
4. The result is:
```
Using "webpack" config function defined in next.config.js.
Total precache size is about 0 B for 0 resources.
```

## Context

I would like to use sw-precache with NextJS

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |    4.1.4     |
| React  |  16.2  |
| node    |   8.9.0      |
| OS      |    MacOSX     |
| browser |    Chrome     |
| etc     |         |

**Comment by OrangeXC** [comment]
@Tuizi 

Have you solved the problem?

I have the same problem

It's work fine in my localhost, but when I use [now](https://zeit.co/now) deploy my project

```
> Initializing…
> Building
> ✓ Installed 864 modules [8s]
> ▲ npm run build
> > gank@1.0.0 build /home/nowuser/src
> > next build
> > Using external babel configuration
> > Location: "/home/nowuser/src/.babelrc"
> Total precache size is about 0 B for 0 resources.
```

Has been building until 10 minutes after throw the error

```
> Error! The build step of your project failed. To retry, run `now --force`.
```

I have try again but error again

Search on github，I find a repo [next-offline](https://github.com/hanford/next-offline)

Use the repo have the same problem, because the source code is basically the same

So I think where is wrong?

Tech | Version
-- | --
next | 5.0.0
React | 16.2
node | 8.9.4
OS | MacOSX
browser | Chrome
etc

**Comment by hanford** [comment]
@OrangeXC @Tuizi 

I left some feedback in the `next-offline` repo around this issue. https://github.com/hanford/next-offline/issues/1

Probably makes sense to continue any conversation about `next-offline` in that repo so others can easily find

**Comment by gerhardsletten** [comment]
This is totally expected because because the `SWPrecacheWebpackPlugin` config is saying:

* Don't use `sw-precache` (ignoring all next-assets)
* Instead use `sw-toolbox` and cache all assets after service-worker is installed.

```
new SWPrecacheWebpackPlugin({
  verbose: true,
  staticFileGlobsIgnorePatterns: [/\.next\//],
  runtimeCaching: [
    {
      handler: 'networkFirst',
      urlPattern: /^https?.*/
    }
  ]
})
```

The effect of this is that a user will need to visit your site twice in order for it to work offline, because on the first visit the service-worker is installed, and on the second it will cache all the assets on the pages he visit.

So the example is kind of a naive approach, and maybe gives false impressions of how easy it is to add offline-support to next

**Comment by arunoda** [comment]
@gerhardsletten 

> first visit the service-worker is installed, and on the second it will cache all the assets on the pages he visit.

This is not true. 
On the first visit, it'll install the service worker and it'll cache the current page. Then you can control caching other pages via Next.js prefetching.

With `runtimeCaching` we have better control of caching with the `handler`. I'm also working on a project to enable service workers for https://zeit.co/docs

Once it's done, I'll send changes to `next-offline`.

**Comment by gerhardsletten** [comment]
@arunoda Are really sure?

I have a page mush like 

[hanford/personal-website](https://github.com/hanford/personal-website)
Live at [jackhanford.com](https://jackhanford.com/)

An if I visit is "as a new user" (service-worker not installed, and empty cache) the service-worker will install while it loads, and in Cache -> Toolbox-cache will only contain stuff loaded after the service-worker has installed.

![image](https://user-images.githubusercontent.com/63344/36078510-9f25008e-0f77-11e8-9d31-94e06d78be79.png)

So if this was my only visit to the page, it will not work offline.

If I do a new reload the toolbox-cache will contain everything I need to load the homepage and it will work offline:

![image](https://user-images.githubusercontent.com/63344/36078537-13da6ca2-0f78-11e8-899d-ceb3c9261509.png)
