### ISSUE TITLE
Dotenv example doesn't work in production

### ISSUE THREAD

**Issue by kanjielu** [zeit/next.js#3412]
The variable is not displayed on the page in production. I've cleared `babel-loader` cache.

Steps to Reproduce:
```bash
1. curl https://codeload.github.com/zeit/next.js/tar.gz/master | tar -xz --strip=2 next.js-master/examples/with-dotenv
2. cd with-dotenv
3. npm install
4. npm run build
5. npm run start
```

**Comment by zenflow** [comment]
That example is configured to use dotenv only in development. You can easily change the configuration [here](https://github.com/zeit/next.js/blob/c9bc471d3a0b8d10556be73c657694a06b10c745/examples/with-dotenv/.babelrc)

Maybe the example *should* use dotenv in production? I am using dotenv for production, and I'm not sure if there's any reason for not doing this. And there has been confusion about this (i.e. someone else thought the example would use dotenv in production) at least once before (PR #3244).

**Comment by maxbeatty** [comment]
dotenv can be used in "production". _How_ it is used depends on what "production" is to you. 

If your "production" is a Digital Ocean Droplet, AWS EC2 Instance, or some other cloud server then you'll need a `.env` file on that host in a known place that your code can reference.

```diff
1. curl https://codeload.github.com/zeit/next.js/tar.gz/master | tar -xz --strip=2 next.js-master/examples/with-dotenv
2. cd with-dotenv
+2.1 cp /home/username/.env.production .env
3. npm install
4. npm run build
5. npm run start
```

If your "production" is ZEIT Now 👀 , Heroku, or some other more managed service, they probably offer [managed secrets](https://zeit.co/docs/getting-started/secrets) where you can store your environment variables. dotenv will fail silently because a .env file does not exist in those environments (which is totally fine) and your `process.env` will be populated by the service instead.

Your code doesn't need to change no matter what hosting solution you choose 🎉

**Comment by acao** [comment]
storing your secrets in memory (managed secrets, exported to process environment variables) vs on disk is always preferrable from a production security standpoint. just an FYI if you are looking to be HIPAA compliant or are otherwise handing PI.

**Comment by kanjielu** [comment]
Thanks. I'm closing the issue.
