### ISSUE TITLE
Example for styled-components breaks the support of styled-jsx

### ISSUE THREAD

**Issue by Mikhail-Fiadosenka** [zeit/next.js#3422]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Using the code from the [example for styled-components](https://github.com/zeit/next.js/tree/master/examples/with-styled-components) should not remove the support of SSR of styled-jsx.

## Current Behavior
When using the code from the [example](https://github.com/zeit/next.js/tree/master/examples/with-styled-components) SSR of styled-jsx stop working.

## Steps to Reproduce (for bugs)
1. Use `_document.js` from the [example](https://github.com/zeit/next.js/tree/master/examples/with-styled-components).
2. Write a page that uses styled-jsx styles.
3. Fetch the page source from NextJS server - there is no style tags from styled-jsx.

## Context
Application that uses both styled-components and styled-jsx (weird use case, but we did this because styled-components didn't work for us in one situation...).

## Root cause
`flush()` method from `styled-jsx/server` is not called in `getInitialProps` method in `_document.js`

**Comment by arunoda** [comment]
It's not updated as mentioned it here: https://github.com/zeit/next.js#custom-document
Could you send a PR for that?

Thanks.

**Comment by NathanielHill** [comment]
For anyone else looking, the solution is found in #2593. I ran into this problem, but it was hard to figure out. Everything working in development, and it worked in production if you started at the '/' route. However, if you refreshed a page on the client or requested a different route, the styled-jsx styles would not load. For some reason, client side routing was also broken at that point (would love to know why @arunoda). I've decided to switch entirely to styled-components to use media-queries for responsive design over react-media/react-responsive, since having different markup for different clients introduces an entire host of rendering/seo issues. But for reference here is what fixed it for me: 

```
import { ServerStyleSheet } from 'styled-components'
import Document, { Head, Main, NextScript } from 'next/document'
import flush from 'styled-jsx/server'

export default class MyDocument extends Document {
  static getInitialProps({ renderPage }) {
    const sheet = new ServerStyleSheet()
    const page = renderPage(App => props => sheet.collectStyles(<App {...props} />))
    const stylesSC = sheet.getStyleElement()
    const stylesJSX = flush()
    return { ...page, stylesSC, stylesJSX }
  }

  render() {
    return (
      <html>
        <Head>
          {this.props.stylesSC}
          {this.props.stylesJSX}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

And of course this `.babelrc` from the offical example:

```
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    ["styled-components", { "ssr": true, "displayName": true, "preprocess": false } ]
  ]
}

```
