### ISSUE TITLE
How keep component Portal when redirect page?

### ISSUE THREAD

**Issue by nghiepit** [zeit/next.js#3436]
Hi guys,
I have seen the example https://github.com/zeit/next.js/tree/canary/examples/with-portals
But, I want to keep component **Modal** when redirect to new page.

**For example:** After I successfully logined then A message will appear. Next, it redirects to **/profile** page. But at the time  The Message component has been unmounted.

Thanks in advance.

**Comment by cuining** [comment]
maybe you can use 
```
setTimeout(Router.push(' /profile', ' /profile', { shallow: true }), 2000)
```

**Comment by tronghiep92** [comment]
Thanks, @cuining, 
But I'm don't understand your code how to help my problem.

**Comment by sergiodxa** [comment]
@nghiepit I think that's expected because after the page change the portal component is no rendered anymore, you will need to keep the component rendered.

I added this page on `pages/a.js`:
```js
import Link from "next/link";
import dynamic from "next/dynamic";

// we import and render the modal only client side (because we need a DOM)
const Modal = dynamic(import("../components/modal"), {
  ssr: false
});

export default function() {
  return (
    <main>
      <h1>test!</h1>
      <Modal title="My Modal Portal">
        <p>This is a portal rendered from Next.js</p>
        <Link href="/">
          <a>Go to /</a>
        </Link>
      </Modal>
    </main>
  );
}
```

And in the model rendered inside `pages/index.js` I added a Link to `/a`. When I open the model in `/` and navigate to `/a` the model keep open (with a change in the internal content). When I go back to `/` the modal is closed because the state of the homepage component start as off. If you save that state somewhere else you can keep it open.
