### ISSUE TITLE
Modularize next.js

### ISSUE THREAD

**Issue by nmaro** [zeit/next.js#349]
Hey guys, what you are doing is amazing, a lot of good architectural choices!

Coming from meteorland I'd like to contribute with a big lesson learned: **buy-in is real and consequential**. You have a framework that magically does everything for you, and then when you want to move on to the next better approach (and you will, because it's javascript-land) you have to give up on the good parts as well as the bad.

The next.js community has the opportunity to do this right, but there is already a somewhat bad sign: next.js has all the code in the main repository, and _no_ other zeit dependency! I think it should be the opposite. next.js should only be wiring things together.

I'd suggest this approach: ask yourself - how would it be if there was no next.js repo but only partial modules, and I had to pick and wire everything together in the app directly? **<- make this as easy as possible**

I know you, like me, like the unix philosophy (do one thing and do it well), and from how I see it next.js does already too many. At the very least

* A files-based router
* A react-component-module-based SSR+front-end-rendering solution
* A build tool

Now you think "but these are all entangled together". Well, that's exactly the problem. That's what happened with meteor. My recommendation is that you start decoupling these things from each other early enough, or in a year people will face real problems when they want to replace one or more bits of the stack with something else.

**Comment by MoOx** [comment]
A monorepo could make this not as painful as an org + multi-repos to keep in sync.

**Comment by nmaro** [comment]
A monorepo is exactly what locks one into the whole stack, which is what one should avoid.

**Comment by MoOx** [comment]
What I call a monorepo is a single git repo with multiple packages in it. I don't see how this can lock you and make it unable to use a package or a fork for something specific.
The real thing to work on is to make those packages not relying on each others when possible.

**Comment by nmaro** [comment]
Ok I didn't know the term. Basically it's one repository containing many separate npm packages, which then get published to npm independently? Sounds interesting, I agree, such a setup might favor the right architectural choices.

**Comment by MoOx** [comment]
See https://github.com/babel/babel/blob/219f6292679bd040f9cb7e5725c18ddaa805b816/doc/design/monorepo.md

**Comment by foxhound87** [comment]
This sounds cool! 

[Lerna](https://github.com/lerna/lerna) can manage monorepo with multi packages.

**Comment by MoOx** [comment]
Let me add a list from my search in https://github.com/MoOx/phenomic/issues/598#issuecomment-242748971

- http://lernajs.io/ (I saw a bad feedback: slow https://github.com/pouchdb/pouchdb/issues/5545)
- https://formidable.com/open-source/builder/ (maybe a bit weird)
- https://github.com/northbrookjs/northbrook (inspired by cyclejs monorepo)
- https://github.com/knitjs/knit (use yarn and don't have the "bootstrap" step that lerna requires)

some infos

  - https://github.com/pouchdb/pouchdb/pull/5178
  - https://github.com/boennemann/alle#readme

**Comment by avindra** [comment]
Big ➕  for this one

I'm currently looking to use `<Head>`, love [how you guys implemented it](https://github.com/zeit/next.js/blob/master/lib/head.js).

Would be nice if I could just import `@zeit/next-head` or something like that, instead of `next`, which is quite heavy altogether.

**Comment by rauchg** [comment]
Thanks for your comments.

I'm in complete agreement with you, and this is already our approach. 

Some general comments:

1. The framework is a result of building https://zeit.co. We're not a framework company, we're a [cloud hosting](https://now.sh) company. We'll continue to make the best tool to solve our problem, and share it with the community. Others take the approach of start with the framework, then build the products.
2. We have no intention of adding more features. Instead, we are expanding your ability to customize and override:
   - Custom config to override babel and webpack #222
   - Custom server logic and manual programmatic initialization #291 
   - Custom <Document /> wrapping #251 
3. Our main priority is fast loading times and small code footprint
4. Whenever we see the opportunity to make something reusable, we do. This is the approach I took with [styled-jsx](https://github.com/zeit/styled-jsx).
5. To address your points:
    - "A files-based router" is [serve-static](https://github.com/expressjs/serve-static), [list](https://github.com/zeit/list), …
    - "A react-component-module-based SSR+front-end-rendering solution" is what Next.js is. 
    - "A build tool" is Webpack and Babel, both not of our creation

Finally, modularization for the sake of modularization is not useful. I think modularization is useful when it _serves a mechanism for module substitution_. In this case, modularizing webpack is important because then you can extend it and learn it independently.

My goal is to provide a good foundation for _stability_ in making high performant websites and web applications with a focus on lightweightness and flexibility.

APIs like `getInitialProps`, custom server, custom `<Document />` are all about that :)

**Comment by rauchg** [comment]
Oh by the way, I completely agree that `<Head>` should be its own module

**Comment by nmaro** [comment]
Sounds awesome. In particular #291 is what does it for me.
