### ISSUE TITLE
How do I access window.WebSocket?

### ISSUE THREAD

**Issue by OKNoah** [zeit/next.js#3500]
```js
if (window !== 'undefined') {
  const ws = new window.WebSocket('...')
}
```

Why doesn't this work?

Also, what is the `isServer` prop? Always says `true`.

**Comment by sergiodxa** [comment]
You need to check `typeof window !== 'undefined'` instead of `window !== 'undefined'`, specially because you're comparing with a String and `window` can be an object (in the browser) or `undefined` in the server but never a String.

Also you can avoid the check using `new WebSocket` inside `componentDidMount`, that way you're sure it's going to work only client side.
