### ISSUE TITLE
Necessity of split app into 2 div containers (e.g. `__next-error` and `__next`)

### ISSUE THREAD

**Issue by vanesyan** [zeit/next.js#3503]
As an continue of trying remove extra div elements from next.js output, I found that there's no strict necessity of spliting errors and app into different containers, we can just conditionally put output of error, or app into the single `__next` container.

**Comment by arunoda** [comment]
@vanesyan this will help us in hot module reloading (with errors) and clean up the DOM in that case.
So, that's a design decision.

**Comment by ruslansavenok** [comment]
@arunoda do u have any suggestion for my corner case?

I need to do something like `sticky footer`, which require me to set `#__next { height: 100%; }` in order for children to grow for 100% viewport height. (100vh has know issues on android mobile devices)

With next5 update, `#__next-error` will not be in view port because there's empty `#__next` div with `height: 100%`.

Also, why dev errors are appended to `#__next` but 500 on prod is appended to `#__next-error`? And why same error component `_error.js` with 404 is appended to `#__next` and not to `#__next-error`?
