### ISSUE TITLE
suport IE9

### ISSUE THREAD

**Issue by Nickynodejs** [zeit/next.js#3505]
Excuse me, my project is to support IE9, I need to join babel-ployfill. and I should add to which file to add.
I added the error in the index.js file

**Comment by catuskeeper** [comment]
I have the same issue.
React requires `Set`, `Map` and `Object.assign` to fit for IE 9 and IE 10, but in a Next.js project I can't find a proper place to import these polyfills from core-js. Adding them in the `clientBootstrap` config does not solve this problem because the `Set`, `Map` is used before these injected `clientBootstrap`.
If there is any solution to inject some local modules BEFORE React is executed in Next.js plz tell me.

**Comment by arunoda** [comment]
We can't support IE9 due to a technical problem in routing: https://github.com/zeit/next.js/issues/1936

@catuskeeper in production `clientBootstrap` runs before everything.
But I'd like to move `clientBootstrap` to the top of the list [here](https://github.com/zeit/next.js/blob/canary/server/build/webpack.js#L48).

(PR welcome)
