### ISSUE TITLE
Google Bot fails to render website

### ISSUE THREAD

**Issue by sinosoidal** [zeit/next.js#3529]
Google Bot is failing to render my website which has been built on top of nextjs. Google bot uses Chrome 41 engine to render the websites it crawls. I have decided to install Chrome 41 to see how I would the see the website. It happens that I see exactly the same as  Google Bot sees. I still don't know exactly what is happening but opening the javascript console I can see a 404 error for a resource from nextjs. I was wondering if you could help me understand what is going on. My website is www.imaginando.pt and the page you see below is www.imaginando.pt/products/ubridge and www.imaginando.pt/contact-us

The resource that fails is **isPlainObject.js.map**

The navigation bar and the images fails to on Google Chrome 41 and on Google bot

![screen shot 2018-01-02 at 16 33 01](https://user-images.githubusercontent.com/1700060/34518223-6a4d2758-f076-11e7-96e4-aa16a2ce32fe.png)
![screen shot 2018-01-02 at 12 32 31](https://user-images.githubusercontent.com/1700060/34518224-6a77bcde-f076-11e7-8137-0c6df0881469.png)
![screen shot 2018-01-02 at 16 32 13](https://user-images.githubusercontent.com/1700060/34518225-6a9211c4-f076-11e7-8214-9633abb06ab5.png)

**Comment by jatsrt** [comment]
Any luck trying to troubleshoot this issue?

**Comment by sinosoidal** [comment]
The first thing you should try is to get Chromium 41 and debug on it.

**Comment by timneutkens** [comment]
This is not related to next.js but to a dependency of your project that's probably using newer javascript syntax. See https://github.com/zeit/next.js/issues/3546 as reference

**Comment by jatsrt** [comment]
So, finally figured this one out, and it's not due to a 3-rd party, but due to example code.

For us, in the getInitialProps, we check cookies for authentication.  Specifically we started using the with-apollo-auth example.

The logic is: 
```
return cookie.parse(
    context.req && context.req.headers.cookie
      ? context.req.headers.cookie
      : document.cookie,
    options
  )
```

Server side with a completely new client, incognito window, or a google bot fetch, this will throw an error.  The example does nothing with that error, so it was not obvious it was happening and it only happens once per clean client.

Instead the example should be something like:
```
return cookie.parse(
    context.req && context.req.headers.cookie
      ? context.req.headers.cookie
      : typeof document !== "undefined" ? document.cookie : "",
    options
  )
```
The reason is that there is no cookies in the initial server side context, but you are also still server side, so "document" us undefined.

So, I would suggest that maybe this gets reopened as a request to modify any cookie based examples that may fall into this trap.

**Comment by jatsrt** [comment]
Also to note, this is non-obvious to see testing with chrome 41 or anything else as it still renders the page client side.
