### ISSUE TITLE
Fetch as google doesn't work

### ISSUE THREAD

**Issue by Ahmtdnz** [zeit/next.js#3546]
I read and apply related issues but fetch as google returned unexpected error.

<img width="570" alt="screenshot at jan 07 17-05-27" src="https://user-images.githubusercontent.com/17492688/34650148-09f7f46e-f3cd-11e7-9be0-9062d3830daf.png">

As you can see some error was displayed. 

## Environment

| Tech    | Version |
|---------|---------|
| next    |   4.2.1  |
| node    |    8.7.0   |
| OS      |         |
| browser |     Googlebot    |
| etc     |         |

**Comment by arunoda** [comment]
Actually, this can be due to a few reasons.
He had an issue but we fixed it. (The version you've should work fine).
See it's working well for zeit.co 

<img width="955" alt="screen shot 2018-01-08 at 8 32 04 pm" src="https://user-images.githubusercontent.com/50838/34676509-05d36cf6-f4b3-11e7-9540-291ce8937344.png">

But this error could happen due to a some NPM module you use in your app which is not working well inside the Googlebot.
I'm not sure how to debug it. Is there any error messages on the Google's end. (Not on the screenshot).

**Comment by arunoda** [comment]
@leo just did a "Fetch as Google" for our https://zeit.co. It's working pretty well.
<img width="969" alt="screen shot 2018-01-08 at 18 09 41" src="https://user-images.githubusercontent.com/50838/34682574-4a54a0ae-f4c5-11e7-85a3-e8992de2fc7d.png">

So, I'm gonna close this.
But feel free to discuss.

**Comment by aksharbonu** [comment]
This is also happening for me. Did you manage to find out if it was NextJS related?

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.nomzplz.com
