### ISSUE TITLE
Is there examples using next.js with react-dnd?  label:"help wanted" 

### ISSUE THREAD

**Issue by qmeteor** [zeit/next.js#3592]
I'm trying to experiment with next.js boilerplate with react-dnd. But I don't know where to begin or if there is some wrapper like next-redux-wrapper for use with react-dnd. I'm not sure how to frame the question because I just don't know what to ask or what considerations there are for using it with react-dnd. Can someone point me in the right direction? 

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

**Comment by babenzele** [comment]
`next-redux-wrapper` makes it so that the component is automatically connected to `redux` and wrapped with `react-redux` `Provider` ([example](https://github.com/zeit/next.js/tree/canary/examples/with-redux)). 

`react-dnd`, and most other libraries, don't need a wrapper since they don't need to exist globally.

**Comment by timneutkens** [comment]
Going to close this as @babenzele gave an answer
