### ISSUE TITLE
gzip compress

### ISSUE THREAD

**Issue by lightj** [zeit/next.js#3604]
I'm using Koa custom server and Nginx. how can I apply gzip compression to .next build files? (static files already applied through nginx)
scripts that serving through the _next directory are not gzip compression
## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     4.2.3    |
| node    |    9.3.0     |
| OS      |     ubuntu 14.04 & os x high sierra     |
| browser |     chrome    |
| etc     |         |

**Comment by timneutkens** [comment]
You can apply the gzip on the `_next` route

**Comment by phaistonian** [comment]
@timneutkens Elaborate on how this can be done?:)

**Comment by timneutkens** [comment]
Go to google and search for `gzip nginx` or `gzip node.js`

https://www.techrepublic.com/article/how-to-configure-gzip-compression-with-nginx/

https://github.com/expressjs/compression when you're not hosting using now.sh / nginx/

**Comment by phaistonian** [comment]
Well, I tried using `koa-compress` and then I noticed [this](https://github.com/zeit/next.js/blob/f2e56609cd61e2c3501ba867c0e9a70edcc5aba4/examples/custom-server-koa/README.md#side-note-enabling-gzip-compression).

Tried the suggestion and thought it worked fine on dev, it did not work properly on production.

Not sure what the issue is, but I presume something related to memory since the more the production server stays up, the slower the response

After a couple of hours, the average response time went from 100ms to 15s

Pretty sure this is not relevant to nextjs, per se, I am just "dumping" this finding here just in case it can come in handy.
