### ISSUE TITLE
pluggin a CRA app to NextJS

### ISSUE THREAD

**Issue by ndao** [zeit/next.js#3620]
I've been working on an SPA built with Create React App. I'm near a point where I need a server for it. I'm exploring SSR and found NextJS to be pretty cool. I googled and haven't found any documentation/examples on plugging my CRA app onto a NextJS server. How much of a change would that be if I were to do so? What are the implications on the current CRA app? My environment is consisted of

CRA, React Router, Redux, Reselect

**Comment by zenflow** [comment]
I'm no expert, but I think there is no way to "plug in" your CRA app to Next.js. I think you will have to basically rewrite your app (mostly copying and pasting in your business logic) to use Next.js's router instead of React Router. I would start with the [with-redux-reselect-recompose example](https://github.com/zeit/next.js/tree/canary/examples/with-redux-reselect-recompose) and also take a look at the other with-redux examples.

Someone should come along with a more authoritative answer though : )

**Comment by sergiodxa** [comment]
It's complicated but not impossible and you will lose a lot of Next.js features, specially because of React Router. This is because at least for the moment Next.js doesn't use RR so you will need to change all your pages to use Next.js router insteda of React Router, or you need to have a sinlge Next.js page rendering your React Router app inside which will cause you more troubles than it helps.
