### ISSUE TITLE
next export: copy files to root level of export folder - "out"

### ISSUE THREAD

**Issue by divyenduz** [zeit/next.js#3668]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
I should have a way to copy files to root of `out` folder while doing `next export`. I thought about doing this in `exportPathMap` in `next.config.js` but I am not sure when `out` folder will be created for me to copy files. 

## Current Behavior
I could not find how to do this in docs, so, I am not sure if it is possible. Is there a standard way of doing this?

## Steps to Reproduce (for bugs)
NA

## Context
I was trying to setup [netlify redirect](https://www.netlify.com/docs/redirects/) and that requires me to place a `_redirects` file in the `out` folder. I am not clear yet on how to achieve that in the build step. 

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   v4.2.3      |
| node    |   v8.4.0      |
| OS      |    MacOS high sierra 10.13.3  |
| browser |    63.0.3239.132     |
| etc     |         |

**Comment by lfades** [comment]
Next is moving `.next` + `static` + the pages defined in `exportPathMap ` as html files to the `out` folder, so `_redirects` is ignored :c

A nice solution: you can add an `script` in your `package.json` that will move it for you!
```
{
  "scripts": {
    "export": "next export",
    "postexport": "node moveMyRedirects.js"
  }
}
```
Use FS or any tool you want: D
Note: Changes made to `out` should be made after the export, because Next clears the folder before starting

**Comment by divyenduz** [comment]
Sounds like a plan. I think this would be the recommended way as well. 

Closing the issue, Thanks.
