### ISSUE TITLE
Update using-preact example to use next-preact

### ISSUE THREAD

**Issue by sergiodxa** [zeit/next.js#3695]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Use new Next.js plugin for Preact.

## Current Behavior
Manually change React for Preact.

## Context
With the release of Next.js v5 the current example with Preact is outdated and can be simplified with the new [next-preact](https://github.com/zeit/next-plugins/tree/master/packages/next-preact) plugin.

**Comment by damianfrizzi** [comment]
The example was already updated.

However I've several issues when using next-preact. It works fine in production mode but it uses preact also in dev mode which leads to the following error `Warning: Failed prop type: Link: unknown props found: __source` and it tries to fetch common.js `GET http://localhost:3000/_next/-/commons.js net::ERR_ABORTED`. How can I disable Preact in dev mode? I also had to add React/React-Dom as direct dependency because I was getting this error when building `next@5.0.0" has unmet peer dependency "react@^16.0.0`

**Comment by hellsan631** [comment]
I can also confirm the example doesn't work while in dev mode.

**Comment by enyce12** [comment]
@sergiodxa I think this issue should be closed. See https://github.com/zeit/next.js/issues/3774

**Comment by programbo** [comment]
This [simple fix](https://github.com/zeit/next-plugins/pull/44) worked for me. @enyce12 can you try it out to see if I have missed a bigger problem?

**Comment by sergiodxa** [comment]
Closed since the example is already using the plugin.
