### ISSUE TITLE
Untranspiled modules are consumed over transpiled ones in Next5

### ISSUE THREAD

**Issue by kenips** [zeit/next.js#3782]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
When consuming packages with both transpiled and untranspiled modules, as defined in their `package.json` with `main:` pointing to the transpiled version and `module:` pointing to the untranspiled one, Next5 picks up the `module:` entry. I'm expecting Next to pick the `main` entry.

## Current Behavior
Next5 picks up the `module:` entry.

## Steps to Reproduce (for bugs)

1. Install a package that has both `main:` and `module:` defined in a `package.json`. For example:
```
main: 'dist/index.js'
module: `src/index.js`
```
2. Check that Next.js picks up `src/index.js` instead of `dist/index.js`

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |     5.0.0    |
| node    |     8.9.4    |
| OS      |    macOS 10.13.2     |
| browser |    Firefox 58.0.2     |
| etc     |         |

**Comment by timneutkens** [comment]
Sounds like an issue with webpack rather than with Next. We don't resolve modules in package.json, webpack / Node's `require` does.

**Comment by jaydenseric** [comment]
@kenips What you are describing is how it is meant to work. Webpack and other bundlers prefer a `module` entry because ESM allows far more efficient bundling with tree shaking, etc.

Note that **a `module` entry is not meant to point to untranspilled source**. It is meant to point to distribution files, transpiled to have ESM syntax instead of CJS.

If a package incorrectly has `module: `src/index.js` you should raise an issue with that project.

**Comment by timneutkens** [comment]
@jaydenseric thanks for explaining 🙏
