### ISSUE TITLE
Firefox loses query string after a Router.replace shallow

### ISSUE THREAD

**Issue by ptomasroos** [zeit/next.js#3817]
We have a very strange edge case only happening in Firefox but its def causing some problems.

This is whats happening is I navigate to the root http://localhost:3000, get redirected on the server to /about2

I click I button which Router.replace shallow:true which replaces the url to /about2?key=value

I refresh the browser at the current state, url is /about2, I expect it to be /about2=key=value

Here a video recording of the scenario.
https://drive.google.com/file/d/1c0oN-UZIVuG5lt6oZiJOlwZSzAM98gSX/view?usp=sharing

To be a friendly guest here's the repro repo, examples/hello-world
npm install && npm run dev

https://github.com/ptomasroos/next.js/tree/firefox-loses-querystrings

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

Firefox 58 (latest)

**Comment by iggyfisk** [comment]
To clarify, if you start the test by navigating to `/about2`, so there's no 302 redirect, this problem doesn't occur. It has to be 302 -> `Router.replace` -> refresh.

No other browser we tested has been affected. Firefox 56 (pre-quantum) showed the same broken behavior.

**Comment by lfades** [comment]
I can confirm this is an issue more with `Firefox` than with `Next.js`. Basically the issue is this: After a SSR redirect inside `getInitialProps` with the following code:

```js
res.writeHead(302, { Location: path })
res.end()
res.finished = true
```

The client behaves as expected but then if you change the query params with `Link` or `Router` in Firefox or use the following code and then refresh the page (F5) it will go back to the initial url:

```js
const url = '/about2?key=value'
window.history.replaceState({ url, options: { shallow: true } }, null, url)
```

I was unable to find why is this happening but here is a quick fix: after using `Router.replace` or doing a redirect with `Link` do this:

```js
window.location.href = YOUR_URL
```

**Comment by ptomasroos** [comment]
If this is a Firefox issue perhaps we should add this bugreport to mozilla, what do you think @lfades ?

**Comment by iggyfisk** [comment]
Whoops, I forgot to mention here:

This issue is reported to Mozilla, https://bugzilla.mozilla.org/show_bug.cgi?id=1422334
