### ISSUE TITLE
Already display component even when getInitialProps hasn't returned yet

### ISSUE THREAD

**Issue by nmaro** [zeit/next.js#388]
Imagine you click on a `<Link/>` that leads to this page:

```
export default class extends React.Component {
  static async getInitialProps() {
    await new Promise(resolve => setTimeout(resolve, 5000)) // or any long operation
    return {}
  }
  render() {
    return <span>done</span>
  }
}
```

right now next.js just waits.
Wouldn't it be better to be able to show the component already, with a loading flag of some kind?

**Comment by christiannwamba** [comment]
@nmaro I have a related situation. Clicking `<Link />` when the component makes a network request throws a network error but if the page is visited directly it doesn't throw the error but completes the request as expected:

```js
export default class extends React.Component {
  static async getInitialProps() {
    const res = await axios.get('http://example.com/path/endpoint');
    return {data: res.data}
  }
  render() {
    return <span>{this.props.data.value}</span>
  }
}
```
<img width="970" alt="screen shot 2016-12-14 at 8 04 35 am" src="https://cloud.githubusercontent.com/assets/8108337/21172745/0663b846-c1d4-11e6-9d74-fe76b95c50bc.png">

The other thing though is that the network tab suggests something CORS related which seems weird because the request completes when __not__ accessing via `<Link />`:

```
XMLHttpRequest cannot load http://example.com/path/endpoint. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```

This is not the case if the page is __not__ accessed with `<Link />`. Everything works as expected when the page is just visited directly.

**Comment by nkzawa** [comment]
@nmaro You can do it by using `componentDidMount`.

```js
export default class extends React.Component {
  constructor(props) {
    super(props)
    this.state = { done: false }
  }
  componentDidMount () {
    setTimeout(() => {
     this.setState({ done: true })
    }, 5000))
  }
  render() {
    return <span>{this.state.done ? 'done' : 'loading'}</span>
  }
}
```

@christiannwamba That is not a hack but something we expect. `getInitialProps` has to be isomorphic.

**Comment by christiannwamba** [comment]
Awesome. Thank you!

**Comment by nmaro** [comment]
@nkzawa I'm sorry I gave a bad example, I don't think componentDidMount can solve what I mean.

What I mean is: imagine having a getInitialProps that takes a somewhat long time to load data. When you end on that page from the client (i.e. no server-rendering involved), next.js just hangs.

**Comment by nkzawa** [comment]
@nmaro I think you mean https://github.com/zeit/next.js/issues/238. We're exploring how to achieve it.

**Comment by nmaro** [comment]
Yes, thanks

**Comment by luisrudge** [comment]
@christiannwamba your problem is that the endpoint you're using doesn't support CORS. It's not related to nextjs at all
