### ISSUE TITLE
Route.js is missing error while building next.js

### ISSUE THREAD

**Issue by nargesdadashi** [zeit/next.js#3986]
Next.js build command throws a 'route.js' is not exist in the path while route.js path is correct and file is not corrupt. Everything works just fine in Mac and Windows with Node.js command prompt but problem is happening when it comes to Ubuntu.

**Comment by timneutkens** [comment]
Please try upgrading to `next@canary` first. 

If that doesn't help please create a new issue that follow the issue template (the big comment block you removed when creating this issue) so that we get all the details needed to investigate your issue. Also 

Note that saying `It doesn't work` is not enough for us to investigate on.
It's like searching for a needle in a haystack, but the haystack is located on someone else's computer on the other side of the world 😄 

We're happy to help you when you can provide a reproduction.
