### ISSUE TITLE
how to cache pages error on client side?

### ISSUE THREAD

**Issue by hank7444** [zeit/next.js#4075]
I can cache component error from page's from "componentDidCatch"

![image](https://user-images.githubusercontent.com/4727090/38086447-f6bbbe2c-3386-11e8-9500-91897fd61d52.png)

![image](https://user-images.githubusercontent.com/4727090/38086466-0d0dadde-3387-11e8-96b3-158b31235f09.png)

![image](https://user-images.githubusercontent.com/4727090/38086460-06036538-3387-11e8-921c-546d6f85d8e7.png)

but if I put some error on pages, I don't know where I can catch errors...

Does anyone has a good idea? thx!

**Comment by timneutkens** [comment]
`componentDidCatch` doesn't work server side. Either way there's not really anything we can do on the Next side, since it's not clear what you are trying to do exactly.
In the future please follow the issue template (that big chunk of text you removed before writing the issue). Otherwise it's really hard to help you.
