### ISSUE TITLE
Suggestion: mention canary/master branch system in the readme

### ISSUE THREAD

**Issue by callumlocke** [zeit/next.js#4173]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

Next.js breaks from GitHub convention by using `canary` as the default branch. I'm sure there are great reasons for this, but I think it's important to flag it up in the readme, and perhaps even add navigation-style links at the top to switch between the 'master' and 'canary' readmes. I'd be happy to add this if you're open to it.

This would help new users to avoid getting confused reading the wrong docs. It would also help users like me who want to get involved but who get put off by not being able to answer simple questions quickly and confidently, like which branch should I pull from, or PR into, etc.

**Comment by lauroaraujo** [comment]
I second that. Spent the whole afternoon trying to make a custom `<App />` work, because I read it in the documentation, only to find that it's not out yet, despite being properly documented on the readme file.

Only after seeing `canary` mentioned in one of the issues related to the feature I understood what was going on. :disappointed:

**Comment by kudos** [comment]
I would like to know what pattern is being applied here just so I can better follow the project. For example, how is 6.1.1-canary.0 a pre-release that shipped after 6.1.1? Was 6.1.0-canary.0 not marked as a pre-release by accident, or do they sometimes get rull releases?

@timneutkens sorry for the tag, just trying to make sure someone who likely has an answer sees this old issue.

**Comment by timneutkens** [comment]
> Was 6.1.0-canary.0 not marked as a pre-release by accident

Yes, it was, I just corrected this.

> 6.1.1-canary.0 a pre-release that shipped after 6.1.1

This was a mistake in semver versioning which we've corrected later on, hence why canary is now called `7.0.0-canary.x` instead of `6.1.1-canary.x`

We release prerelease versions under the canary tag. For the stable documentation, you can refer to nextjs.org/docs, which at the time of writing this issue was not released yet, it was released at ZEIT day on April 28th.

**Comment by kudos** [comment]
Ah ok, so `7.0.0` final will come after the `7.0.0-canary.x` releases? I guess once that happens things will be less confusing.

**Comment by timneutkens** [comment]
Exactly, the upcoming stable release will be 7.0.0 as we've upgraded webpack and there are a few other breaking changes.
