### ISSUE TITLE
getInitialProps is called multiple times using Express/Fastify

### ISSUE THREAD

**Issue by approots** [zeit/next.js#4174]
- [ x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
A page's `getInitialProps` should only be called once per page load.

## Current Behavior
Sometimes `getInitialProps` is called multiple times in one page load.

## Steps to Reproduce (for bugs)

Minimal example app (almost identical to the next example app "custom-server-express"): https://github.com/approots/next-express-issue

To reproduce:

1. Run `npm run dev` and check the terminal console for multiple outputs of the console.log statement in the `getInitialProps` function of `pages/index.js` ("getInitialProps index").
2. Or click the link to "post 2", refresh the page, then load the index page again (localhost:3000/), and check the terminal and see multiple console.logs of "getInitialProps index". This also happens in production.

## Context
This means that API calls are being duplicated.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |       ^5.1.0  |
| node    |     8.9.4    |
| OS      |      Windows   |
| browser |    Chrome     |
| express     |    ^4.16.3     |

**Comment by approots** [comment]
![next](https://user-images.githubusercontent.com/235342/38973539-32f6cbe6-435b-11e8-9a66-b3c029c42c1e.png)

**Comment by timneutkens** [comment]
`getInitialProps` is only ran once per render. The only thing that I could see is that sometimes HMR kicks in and reloads the page really fast while booting up. But that's not unexpected.

Here's the code: https://github.com/zeit/next.js/blob/canary/server/render.js#L79

Note that the correct way to test per-render is to do `curl http://localhost:3000`, since then there are no other factors.

**Comment by timneutkens** [comment]
@expandrew I'm pretty sure your issue is something else. Please create a new and complete issue (including example repository). Thanks.

**Comment by AjayPoshak** [comment]
@approots I think that your issue is in middlewares. So when I load `page a`, middleware for `a` gets called, but then this middleware `server.get('*', (req, res) ` also gets called because it catches all URLs.  So your page is being caught by two middlewares.

I think that returning from first middleware that matches your route pattern, will solve your issue.
