### ISSUE TITLE
Safari not caching images and 404 source maps 

### ISSUE THREAD

**Issue by Devhound** [zeit/next.js#4244]
I have a header component with a logo image and on chrome visiting other pages does not force the logo image to reload. But on safari, every time I visit a new page all the images including the logo image reload. 

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior
For safari to behave the same as chrome. 

## Current Behavior
Safari will reload the image instead of caching it.
I also get these two errors in the console. Only in safari and not chrome. 

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (_error.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (_app.js.map, line 0)
```

## Steps to Reproduce (for bugs)
Set up simple next hello world
Create a index.js and about.js
Create a component named header.js with links to index and about and an image
Include header component in index and about pages
Start dev server
Compare between chrome and safari

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   6.0.0      |
| node    |   9.8.0      |
| OS      |     MacOS 10.13.4  |
| browser |    Safari 11.1     |
| etc     |         |

**Comment by timneutkens** [comment]
In development everything served by Next.js gets a no-cache header. The sourcemaps not showing up is normal I guess, not sure how Safari handles them.

**Comment by Devhound** [comment]
Then why does chrome cache the images?
![screen shot 2018-05-01 at 3 05 43 pm](https://user-images.githubusercontent.com/17565159/39491225-32555716-4d51-11e8-9a32-be5e1a20ba8e.png)

I clicked back and forth from the home and about page and chrome never reloaded the image.


Safari on the other hand reloads it everytime.

![screen shot 2018-05-01 at 3 03 01 pm](https://user-images.githubusercontent.com/17565159/39491261-50bea612-4d51-11e8-8592-26ef4695977b.png)

this happens outside of development too.

**Comment by Devhound** [comment]
I'm still having the same problem running next build and next start

**Comment by Devhound** [comment]
@timneutkens Can you please re-open this issue. The same problem exists on zeit.co with some images never getting cached on safari but are cached on chrome. Is this intended behavior?

**Comment by Devhound** [comment]
@timneutkens  Please re-open this issue. Images on safari act totally different than on chrome. Doesn't matter if it is development or not. 

Here's a demo
https://www.youtube.com/watch?v=gJQkOHzW1qo

Is this intended? why does the image jar around like that on Safari?

**Comment by didiself** [comment]
So am I.

**Comment by fivepluss** [comment]
@d3vhound Do you use next component Link around menu links?
`import Link from 'next/link'`
...
`<Link href="/about">
      <a>About</a>
    </Link>`

**Comment by spencermefford** [comment]
I think Safari is caching your images just fine. The render issue must be something else. I tested this out on Google.com to see what it looked like when Safari returns images from cache vs server fetch.

The first time I hit Google.com it should have already been cached. I checked the network tab and noticed the `Transfer Size` column says `(memory)` for most files. See this screenshot:
![screen shot 2018-10-29 at 3 10 41 pm](https://user-images.githubusercontent.com/1268629/47680684-24daf080-db8d-11e8-8685-798062ee26bd.png)

Then I cleared my cache and reloaded. Now you can see that `Transfer Size` shows the actual size of the file transferred. See this screenshot…
![screen shot 2018-10-29 at 3 10 51 pm](https://user-images.githubusercontent.com/1268629/47680666-1a205b80-db8d-11e8-84f7-13e51cf28263.png)

I reloaded again, and things resembled the first screenshot again, meaning `(memory)` must be referring to images that are cached. I see `(memory)` in your YouTube video @d3vhound, so I don't think the issue is caching related.

**Comment by Skyentific** [comment]
I having this problem also.
Works fine on Chrome but Safari requests images on each link click.

![image](https://user-images.githubusercontent.com/32698710/56454573-90a45600-6385-11e9-9329-ce2420db6bd0.png)

In this case, the 'sarah.svg' image is enclosed in a Next/link tag

![image](https://user-images.githubusercontent.com/32698710/56454594-c5181200-6385-11e9-87ca-5201d2af30de.png)

In Chrome, the images are only loaded once
