### ISSUE TITLE
How to get cookie in example "with-redux"

### ISSUE THREAD

**Issue by yanranxiaoxiaoshu** [zeit/next.js#4304]
In my project,I used Redux Example - "width redux". I want get cookie data to init my project. but in server-side, I can not get cookie data,the result is undefined. But in client-side,i can get de cookie data .  

![image](https://user-images.githubusercontent.com/21351375/39741870-06f10926-52ce-11e8-9d69-1b8feef99958.png)

How can i get cookie data to init my project?

**Comment by thomhos** [comment]
I believe the above screenshot shows a reducer, right?

If so, I think you want to remove the side effects (reading and writing cookies), and do that either with thunk or sagas.

Secondly, the above code runs both client and server side. When it's running client side you have access to the cookies, because you're in a browser. However when it's server side you don't have a browser, hence no cookies. The way to access them is by accessing the req object (you find that in 'getInitialProps'). 

So I guess you should remove the cookies logic and put it somewhere where you have access to the request, and let that send actions in to redux. 

Cheers!
