### ISSUE TITLE
Bundling issue with CommonsChunkPlugin

### ISSUE THREAD

**Issue by stramel** [zeit/next.js#4323]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Expected Behavior

When building my app using `NODE_ENV=production next build`, it should only count the actual pages.

## Current Behavior

When building my app using `NODE_ENV=production next build`, it is grabbing any file that is `.js` under `/pages` folder.

This includes:

- test files (in my case, *.test.js)
- page specific components, containers, and views

## Context

This results in, the pre-defined `webpack.js`, having "104 total pages" of which, I really have 12-ish pages. So when it goes to try to bundle "common" modules (ie. lodash, momentjs) they end up not getting bundled because the defined plugin looks for count to be greater than or equal to 1/2 the pages. Lodash usage count is 9-54x and Moment.js usage count is ~24x. These should easily get bundled based on usage and actual pages.

Another option would be to allow a way to define our own bundling methods. Currently, I couldn't figure out a way to accomplish that.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |   v6    |
| node    | v9.11.1 |
| OS      | Win 10  |
| browser | Chrome 66 |
| etc     |         |

**Comment by timneutkens** [comment]
This is expected behaviour. Anything in pages is a page and handled as such. Every page is also a webpack entrypoint. So if you put all the code inside pages you’ll end up with every component being exposes to the outside as a page. Also long build/rebuild times etc. So what we’ve always recommended is to only put pages into pages, and the rest in another directory like components.
