### ISSUE TITLE
Setting up elastic apm with nextjs

### ISSUE THREAD

**Issue by sagartalla** [zeit/next.js#4348]
Im trying to integrate elastic APM (https://www.elastic.co/solutions/apm). 
When I import elastic-apm-node (https://github.com/elastic/apm-agent-nodejs)  package inside my pages/index.js it throws following error.
```
These dependencies were not found:
* async_hooks in ./node_modules/elastic-apm-node/lib/instrumentation/async-hooks.js
* child_process in ./node_modules/elastic-apm-node/lib/instrumentation/patch-async.js
* dns in ./node_modules/elastic-apm-node/lib/instrumentation/patch-async.js
* module in ./node_modules/require-in-the-middle/index.js
* net in ./node_modules/elastic-apm-node/lib/instrumentation/patch-async.js
```
 
When I import elastic-apm-js-base (https://github.com/elastic/apm-agent-js-base) It works but it  tracks only on the browser and doesn't track anything running on serverside.

Example Code : https://github.com/sagartalla/elastic-apm-nextjs

- [x] I have searched the [issues](https://github.com/zeit/next.js/issues?q=is%3Aissue) of this repository and believe that this is not a duplicate.

## Your Environment

| Tech    | Version |
|---------|---------|
| next    |  6.0.1 |
| node    |     10.1.0    |

**Comment by timneutkens** [comment]
Sounds like you're trying to implement it at the wrong location. It shouldn't be inside pages, pages are bundled for the server and client side. 

In your case, you'll want to use this:
https://www.elastic.co/guide/en/apm/agent/nodejs/current/express.html

In combination with:

https://github.com/zeit/next.js/tree/canary/examples/custom-server-express

One thing I saw is that it catches uncaught errors, which are not that likely to happen with Next since we catch errors and render the 500 page.

Currently we don't expose a hook for this. But it's tracked in #1852

**Comment by sagartalla** [comment]
@timneutkens Lets say I want to track api calls made on server side using elastic api then writing those api calls in custom server.js is the only way?

**Comment by timneutkens** [comment]
`getInitialProps` is also ran on the client when using `<Link>` to navigate. So you can't use a Node.js only solution, like the one you want to implement.
