### ISSUE TITLE
Typescript examples are broken

### ISSUE THREAD

**Issue by EugeneDraitsev** [zeit/next.js#4528]
# Bug report

## Describe the bug
I tried to launch `with-jest-typescript` example, but seems like it's broken.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. run `yarn create next-app --example with-jest-typescript with-jest-typescript-app`
2. cd with-jest-typescript-app
3. yarn dev
4. go to `http://localhost:3000/` and try to updated the page
You will able to see error: ` TypeError: Cannot read property 'extensions' of null`

Also `yarn test` is broken too.  It fails with error
```
 Test suite failed to run
```
 
## Expected behavior
All works fine

## Screenshots
![image](https://user-images.githubusercontent.com/16540432/40889807-11f70600-676d-11e8-96f4-73b79935e99c.png)
![image](https://user-images.githubusercontent.com/16540432/40889811-1f00d326-676d-11e8-87ba-99ef243f2b75.png)

## System information
 - OS: macOS 10.13,4
 - Browser chrome 66.0.4
 - Version of Next.js: 6.0.3

Updated:

Same for `with-typescript-app`
1. run `yarn create next-app --example with-typescript with-typescript-app`
2. cd with-jest-typescript-app
3. yarn dev
4. go to `http://localhost:3000/` and try to updated the page

You will able to see another error: 
```
Error: [BABEL] /Users/eudr1/environment/with-typescript-app/pages/index.tsx: .overrides is not allowed in preset options
```

**Comment by CarloPalinckx** [comment]
I'll have a look 👍

**Comment by programbo** [comment]
@timneutkens This issue was fixed by https://github.com/zeit/next.js/commit/de6bf4e75f89a672ecd41d91b7a7aac3381e4fe9...

### HOWEVER

I did just learn that I needed to update `create-next-app` in order for it to install the latest version of the example. Not sure if the example `package.json` not bumping the version from `1.0.0` has anything to do with CNA happily installing a months old version of the example.
