### ISSUE TITLE
Using the fs module?

### ISSUE THREAD

**Issue by grundhoeferj** [zeit/next.js#4552]
Hey everybody 😊👋

I have a question about using the `fs` module.
Let's say we have a directory called `posts` and inside of that directory we have multiple sub-directories which each of them represents a post.
It looks like that:
```
./posts/
  first-post/
  second-post/
  third-post/
  ...
```
Now I want to read all these sub-directories dynamically (e.g. with the `fs` module) and pass them to a page (inside of the `./pages/` directory). After that the page will render each post.
I hoped that I can use the `getInitialProps` function for that, but it seems like the function will also be called on the client-side, where the `fs` module is not available...(Error: `ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in ...`)

Does anybody have an idea how to solve this problem? 🤔

**Comment by timneutkens** [comment]
Next.js is universal. After the initial render every `next/link` you click does a client-side transition. Because of this, you can't use `fs` as it's not available in browsers.

The solution here is to create a simple JSON API using for example github.com/zeit/micro. And then fetching the data from the microservice in `getInitialProps`.


Please post questions on https://spectrum.chat/next-js next time, as per the issue template.
