### ISSUE TITLE
Strange behavior with i18next

### ISSUE THREAD

**Issue by markolofsen** [zeit/next.js#4690]
# Examples bug report
**warning.js:33 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.**

## Describe the bug
Strange behavior with i18next
 
## To Reproduce
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Install repo [https://github.com/markolofsen/nextjs-toolkit](https://github.com/markolofsen/nextjs-toolkit)
2. Open http://localhost:3000/
3. Check Firebug console

## System information
 - Mac Os
 - Chrome
 - Next js latest

## Additional context
```
warning.js:33 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at index.js:107.
    in Index (created by I18n)
    in I18n (created by Translate(Index))
    in Translate(Index) (created by WithStyles(Translate(Index)))
    in WithStyles(Translate(Index)) (at withRoot.js:34)
    in MuiThemeProvider (at withRoot.js:28)
    in WithRoot (created by App)
    in Container (created by App)
    in App
    in ErrorBoundary
```

**Comment by codinronan** [comment]
This isn't a bug in next; it is an issue with how you are using the `withi18next` function - and it is a *function* that takes a component and returns a component, it is not a decorator, but you are using it like one:

![image](https://user-images.githubusercontent.com/13020457/42070074-6dc45abc-7b1a-11e8-9820-1dc17d3964a5.png)

You need to use it like a HOC instead, as you've done with `withStyles` in the export. The issue is that the HOC is never wrapping the component with the translate context; the output of `withi18next` is getting thrown away, so the components that get generated underneath by i18next don't work right.

Either way it's not a Next issue.

**Comment by timneutkens** [comment]
Can you try using https://github.com/isaachinman/next-i18next
