### ISSUE TITLE
Memory leaks in the use of SSR

### ISSUE THREAD

**Issue by mvcruzata** [zeit/next.js#4741]
Hi, we have a system in which we set up our websites using SSR, with a flow over 2000 rpm in production environment. Actually, we are facing memory leaks issues by rendering react component throught SSR. We are looking for alternatives for handling SSR efficiently by avoiding possible memory leaks generated by the react compoenents to render. We are evaluating the use of Next.js as framework for SSR. Have you face similar memory leaks issues before? Does Next.js have mechanism to avoid those memory leaks? Thank you so much for your support.

**Comment by timneutkens** [comment]
We haven't had reports of memory leaks so far, the main thing to keep in mind when doing React SSR is that you have to explicitly set `NODE_ENV=production` on bootup otherwise React's server renderer will boot up in development mode.

As far as prevention goes, there's nothing specific we do in this area.

**Comment by timneutkens** [comment]
Feel free to post any other questions on https://spectrum.chat/next-js as that's where the whole community can see your question.
