### ISSUE TITLE
ISSUE IN LINK

### ISSUE THREAD

**Issue by mercurio-developing** [zeit/next.js#4773]
Hi guys, I need some help here. I don't quite understand this behavior. 

THESE WORK PERFECTLY:

/////  NAVBAR

     <Link as={"/inventory"}>
                  <a className="nav-item nav-link active">INVENTORY</a>
      </Link>

///////  INVENTORY PAGE

 static async getInitialProps(req) {
    return { coins: req.query.query };
  }

/////// CUSTOM SERVER EXPRESS

  server.get("/inventory", (req, res) => {
    Coin.find({}).then(coins => {
      return app.render(req, res, "/inventory", { query: coins });
    });
  });

BUT >>>  if I put  in the navbar:
      <Link href="/inventory" as={"/inventory"}>
                  <a className="nav-item nav-link active">INVENTORY</a>
      </Link>

The req.query is not coming anymore in the INVENTORY PAGE

Can I use AS="/inventory" as well?

I would like to understand this better.

Thank you guys!

https://github.com/mercurio-developing/next-shop-aws

**Comment by timneutkens** [comment]
`<Link>` does client side routing.

The correct way to use it is:

```
<Link href="/blog?id=hello-world" as="/blog/hello-world">
```

`href` => path inside the `pages` directory + querystring
`as` => path used in the browser

Fetching data should be done in `getInitialProps` to an external API, so that client side routing can fetch it. It's generally not recommended to fetch inside the custom server.
