### ISSUE TITLE
next export getting stuck

### ISSUE THREAD

**Issue by beforesecond** [zeit/next.js#5037]
**I can't deploy on production . Because next export stuck .
Please help me.
Thank you.**

# Bug report on Circleci

```
> Using external babel configuration
> Location: "/home/circleci/project/.babelrc"
> using build directory: /home/circleci/project/.next
  copying "static build" directory
> No "exportPathMap" found in "next.config.js". Generating map from "./pages"
> exporting path: /edit
> exporting path: /index
> exporting path: /login
> exporting path: /logout
> exporting path: /new
> exporting path: /view
> exporting path: /_error
> exporting path: /

Too long with no output (exceeded 10m0s)
```

**Comment by timneutkens** [comment]
I'm not sure what to do with this issue. You're not providing a reproduction and you're not following the issue template. It sounds similar to a previous issue that I believe is fixed on `next@canary` (beta). Either way, I'm going to close this. Please always follow the issue template + provide a clear reproduction, as it's impossible for us to help otherwise.
