### ISSUE TITLE
Next.js v7 Autoinject styles 

### ISSUE THREAD

**Issue by popugang** [zeit/next.js#5276]
My problem is that the general bundle styles in the head are not connected.
Why path in browser` _next` differs path in project folder` .next`
How to connect the styles that are in the .next / server / style.css and not use this 

![image](https://user-images.githubusercontent.com/19804652/45999666-f9a54300-c0ae-11e8-8a94-9058adbc3600.png)

**How i use styles** 

![image](https://user-images.githubusercontent.com/19804652/45999868-a2ec3900-c0af-11e8-9754-c49a298e7650.png)

**My config** 

![image](https://user-images.githubusercontent.com/19804652/45999898-b7c8cc80-c0af-11e8-94c7-89da3b2bb51a.png)

**Comment by timneutkens** [comment]
# ***Please follow the issue template*** 

and provide a reproducible GitHub repository.

**Comment by popugang** [comment]
@timneutkens you are digging your own grave without communicating with the community

**Comment by timneutkens** [comment]
We can't help you without a clear reproduction. You're disregarding the guidelines we give so that we can help with the issues you're experiencing.

The reproduction is needed so that we don't have to spend hours trying to reproduce an issue + so that we can add an exact test for the exact issue you're experiencing.
