### ISSUE TITLE
With-firebase-authentication example -- SSR: Is sending credentials in index.html response dangerous?

### ISSUE THREAD

**Issue by skitterm** [zeit/next.js#5304]
# Examples bug report

## Example name
With Firebase Authentication

## Describe the bug
This [example](https://github.com/zeit/next.js/blob/canary/examples/with-firebase-authentication/pages/index.js#L12) shows returning an authentication token from `getInitialProps`. When the page is rendered server-side, this means that the token will get sent as part of the HTML page response (as part of `NEXT_DATA`) to the browser. Is this a security issue, to have a token as part of the HTML page? Seems that if the request happened with HTTP, the token would be exposed in plain-text across the network. And it doesn't seem safe to have the token in the HTML page on the browser. 

Just curious if this is an issue/limitation with SSR and, if so, perhaps there should be some warning about it in the example's README.

**Comment by timneutkens** [comment]
@jthegedus

**Comment by lfades** [comment]
@skitterm I did a quick lookup and that's okay, the token from firebase is supposed to be used in the client. It's a JWT and those are supposed to not contain any sensitive information. If this information is enough consider closing the issue, otherwise ask for more, I'm currently implementing Firebase Auth in one app, thank you 🙏 .

**Comment by skitterm** [comment]
I agree that the token is meant to be used client-side, but having the token potentially transmitted over http lets any middleman see its content plain-text, and use it in their own requests as if they're the authenticated user. Seems like the better approach when the token is needed client-side is to read the cookie client-side for the token, so it's not transmitted over the wire and also isn't sitting on the HTML page.

**Comment by lfades** [comment]
Well, the token is not really being sent, only the entire payload, see [this line](https://github.com/zeit/next.js/blob/canary/examples/with-firebase-authentication/server.js#L44), maybe we should not send the entire thing ([this](https://firebase.google.com/docs/reference/admin/node/admin.auth.DecodedIdToken)) but since all those fields are public anyway, it's not necessary for the sake of the example.

**Comment by timneutkens** [comment]
Going to close this as the issue is stale.
