### ISSUE TITLE
`next init` as a separate module?

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#531]
I don't want `next init` to stagnate, be opinionated, etc. The solution is perhaps to remove it.

How would you all feel about making `next init` an optional, installable command that comes from a different package?

```
npm install -g next-init
```

It would expose a global bin `next-init`. The cool thing about making it a separate module is that we can iterate on it independently, and add more features frequently.

Some ideas for the future.

```
next-init --preact --glamor
```

```
next-init --inferno --styletron
```

If anyone would be interested in leading this project, please let me know as well

Another discussion I'll open later is to take the same approach for compiling a next app into static files, via `next-export`.

**Comment by impronunciable** [comment]
How about a yeoman script?

**Comment by rauchg** [comment]
I haven't looked at that yet, but if it satisfies our need to support "flags", and it's well supported, easy to use, easy to get started with, it sounds like a winner!

**Comment by arunoda** [comment]
@rauchg it support tags and many more cool features.

**Comment by ntwcklng** [comment]
@rauchg i would love to be part of this project, should i create a draft?

**Comment by rauchg** [comment]
@ntwcklng you're absolutely welcome to. `next-new` is a great name as well. Maybe it could even install a `nn` alias :D 

But as said above, it'd be interesting to compare pros/cons of `nn` as a `yo` extension vs standalone

**Comment by ntwcklng** [comment]
Awesome!
For me the standalone module would win the race. Its the standard-zeit-way - straightforward and lightweight:
```
$ npm install -g next-new
$ nn my-new-blog --glamor
> created my-new-blog (with: glamor)
> run `$ cd my-new-blog && npm start` to get startet
```

With Yeoman you have to install 2 global dependencies.

**Comment by ntwcklng** [comment]
Could look like this:
![nn](https://cloud.githubusercontent.com/assets/8714775/21580969/276ab134-d01b-11e6-92b0-ac014822acec.gif)

**Comment by ntwcklng** [comment]
Any other opinions? I would love to see that thing in production 😄

**Comment by timneutkens** [comment]
@ntwcklng that looks pretty neat 😄

**Comment by timneutkens** [comment]
@rauchg @arunoda As we all know Segment made create-next-app (https://open.segment.com/create-next-app) which is pretty neat. Maybe we should remove `next init` and leave this in userland?

**Comment by sergiodxa** [comment]
I'm with @timneutkens, create-next-app it's awesome, it's integrated with `yarn create` and allow the user to start from an example so it's possible to keep adding examples and CNA it's going to have more and more options.

**Comment by arunoda** [comment]
@timneutkens I like that idea. Yeah send a PR :)

**Comment by chabou** [comment]
Do you want to recommend `yarn create next-app my-project` or `create-next-app` in `next -h`? Or remove `init` command without any explaination about how to start a `next` project?

**Comment by timneutkens** [comment]
Lets just log out a message that it's deprecated and you can use `create-next-app`.

**Comment by ragingwind** [comment]
I'm interested in this issue. First of all, I love that using `create-next-app` for zero-configuration setup like `create-react-app` but It's not enough opened to folks who want to make own version of next app. As I know that `create-next-app` doesn't support templates(like [vue-cli](https://github.com/vuejs/vue-cli)) or generators in the outside world(like yeoman or [webpack](https://github.com/ev1stensberg/webpack-addons-demo)). 

How about using vue-cli template system. Conceptually, It's very similar to yo/yeoman-generator but rather than simple and straight in terms of using templates. For example, supporting github repo directly. It make `next init` to be more less opinionated in my point of view. I would like to make PoC version for this, any thought?

**Comment by timneutkens** [comment]
@ragingwind I like the idea 👍, though most people will just want to start off using one of the examples though, and create-next-app provides that. It also has a default similar to `next init`, which is fine. What you're proposing can obviously be an external tool though 👌 We're basically just removing bloat from the next codebase 👍

**Comment by ragingwind** [comment]
@timneutkens I see that the point of removing `init` from next. Have you guys decided to use `create-next-app` with [next.js example](https://github.com/zeit/next.js/tree/master/examples/) instead of `next init`. Then I'm concern that

- examples is great but It downloads only static files from the repo, which can't be combinable as a whole of an app.  For example, `next-init --preact --glamor`
- No template and prompting mean that there are no any custom configurations even project-name in package.json. The user need to fix every time as it is generated. It's so bothering to me

**Comment by timneutkens** [comment]
@ragingwind it's currently the only Next.js generator out there, both ways, `next init` was never documented, and the deprecation message is only for when people use it. It's still their decision to use `create-next-app` (or not) 😄 I'd love to see what you're proposing though, combining examples would be amazing 👌

**Comment by ragingwind** [comment]
@timneutkens I understand that this issue good for beginner :0 I will show off the another generator

**Comment by timneutkens** [comment]
@ragingwind 👍 💯

**Comment by ragingwind** [comment]
@timneutkens I've made a PoC version of next-init https://www.npmjs.com/package/next-init Have a look
