### ISSUE TITLE
State getting reset between shared modules

### ISSUE THREAD

**Issue by souporserious** [zeit/next.js#536]
I feel like this example is a little misleading: https://github.com/zeit/next.js/tree/01da6f47614041cac56587078bfc19d7cc28c238/examples/shared-modules

I was expecting the component to be able to keep its state between route transitions. But when I try the following it gets blown away with every Router transition.

![image](https://cloud.githubusercontent.com/assets/2762082/21498833/26fd4d40-cbe5-11e6-8d48-2ad59ca34cda.png)

Is this expected behavior or a bug?

**Comment by arunoda** [comment]
This is a bug. We need to fix this.

**Comment by arunoda** [comment]
Okay. I was confused. This is the intended behavior.
Here's our counter code:

```js
import React from 'react'

let count = 0

export default class Counter extends React.Component {
  add () {
    count += 1
    this.forceUpdate()
  }

  render () {
    return (
      <div>
        <p>Count is: {count}</p>
        <button onClick={() => this.add()}>Add</button>
      </div>
    )
  }
}
```

Basically, here we share the above module across pages. So, the example is to the point.

But in your case, you are trying to the share the react instance. It's not going to work because that's two different pages. It's not a bug or something unusual. That's how React works.

Basically, you need to use some kind of state management solution like Redux or Mobx.

**Comment by souporserious** [comment]
Sorry, I should have explained that better. That makes sense. Thank you for the quick reply!
