### ISSUE TITLE
Can you ensure that the demo works properly?

### ISSUE THREAD

**Issue by yangchongduo** [zeit/next.js#5371]
Can you ensure that the demo works properly?
Many demos can't run normally，Such as custom-server-koa

**Comment by yangchongduo** [comment]
Please be strict before releasing

**Comment by ptdede** [comment]
@yangchongduo for me it is working perfectly. I use `npx create-next-app --example custom-server-koa custom-server-koa-app` => `cd custom-server-koa-app` => BOOM. its running.

Instead of complaining or judging, please also provide screenshots or at least error code printed in console/shell/whatever that you found. So we can fix it together and make the open source community better and better.

**Comment by timneutkens** [comment]
Feel free to send a pull-request for any improvements to examples, they're mostly maintained by the community. We also have multiple issue templates that help us make it easier to hand off issues to new contributors. I'm going to close this per above comment of it working fine.
