### ISSUE TITLE
How to force hash-based routing.

### ISSUE THREAD

**Issue by trusktr** [zeit/next.js#5782]
How do I force router to use hash-based routing?

**Comment by timneutkens** [comment]
Please follow the issue template.

**Comment by trusktr** [comment]
I'm using mobile, looks like issue templates don't appear there.

Also parsing hashes myself to implement hash-based routing *completely* defeats the purpose of even using Next router.

So on older browsers you don't have hash based routing?

Or you do? And if you do, how to I tell Next to use that fallback?

And if there's no way to tell Next to use hashes for all routes, then this is a feature request and it'd be great to re-open this in that case.

**Comment by trusktr** [comment]
By the way, non-hashed routing does not work on AWS S3 or CloudFront without having to write a AWS Lambda function, because by default AWS does not serve index files for any path except for root `/`.

So if Next doesn't have a Hash routing, then by default it does not work on AWS static hosting.

**Comment by sergiodxa** [comment]
@trusktr old browsers will rely on normal link with page reload instead of being a SPA, thanks to SSR it will work as a normal web page.

About AWS S3 and CloudFront, the only way to use them with Next is made use of the static export feature, in that case you don't have dynamic routes, just static files you can drop in AWS S3 and let it serve them.

**Comment by trusktr** [comment]
In case maybe you misunderstood what I was talking about, I want to enable routing that works like legacy, where all paths are like follows:

```
example.com/#/
example.com/#/one/
example.com/#/one/two/
example.com/#/one/two/three/
example.com/#/posts/
example.com/#/posts/this-is-the-post-slug
example.com/#/users/
example.com/#/users/username
```

where _every single route_ is hash-based.

I'm not asking how to handle a single hash, I know how to do that.

I would be surprised if this option didn't exist in Next.js.

> it's up to you to parse them.

If you already knew what I meant when you said that, then that's the same as saying "don't use Next, forget about Next file system-based route structure, forget about SSR, just use plain React and make your own router".

So hoping maybe you didn't know what I meant. :)

**Comment by sergiodxa** [comment]
If you want to use hashbang URLs you can't use SSR, since `/#` and `/#/one` is the same route server side, so there is no way for the server to know what to render, it will need to send a basic template and let the client fill it, in that case I think using CRA with React Router and its `HashRouter` is a better option, that way you will have a single index.html and let the client decide what to render.

**Comment by trusktr** [comment]
The lack of this feature in Next makes it inflexible.

If I was using `Now`, things would be in better shape (though I had issues deploying even a Next website to there). I'm not going to be able to tell my org "hey, let's just switch from AWS to Now". They're not going to take that lightly.

My honest suggestion for Next authors is to make this _very necessary_ improvement, not even for supporting older browsers, but for supporting unfortunately-restricted server environments like AWS S3 and CloudFront (which is a widely-used hosting solution).

**Comment by trusktr** [comment]
Also note, other routers handle things like `onHashChange` _on top_ of the hash-based routing.

For example beside being able to have routes like

```
example.com/#/posts/
example.com/#/posts/this-is-the-post-slug
```

it is still possible to handle regular hashes (f.e. to scroll to part of an article):

```
example.com/#/posts/this-is-the-post-slug#some-heading
```
