### ISSUE TITLE
Hot Module Replacement for inner components

### ISSUE THREAD

**Issue by nagman** [zeit/next.js#5859]
I've read [here](https://zeit.co/blog/next6-1) that ZEIT removed the _keep-the-state-while-reloading-component_ stuff from Next.js for reliability reasons.

But for stuff as simple as CSS it would be great not to have the full reloading of the page at each modification of the inner components:

![5](https://user-images.githubusercontent.com/16116486/49803768-10277600-fd51-11e8-9977-21ad9fedc6ed.gif)

Or at least a full reload of the concerned component (not __all__ the components).
Because in the image provided, I'm editing the `button` component, not the whole page.
But the whole page refreshes, and all the components in it, not just the `button` component.

Or maybe am I the only one having this issue?
I'm using _@zeit/next-sass_ with SASS modules.
__next.config.js:__
```
const withSass = require('@zeit/next-sass');
module.exports = withSass({
	cssModules: true,
	cssLoaderOptions: {
		localIdentName: '[local]__[hash:base64:5]',
	},
	sassLoaderOptions: {
		includePaths: ['theme'],
		outputStyle: 'compressed',
	},
});
```

__EDIT:__ Just noticed that the burger menu doesn't reload. That's strange, it's like only my `main` component reloads (which is separate from the `header` in which the burger is).

**Comment by timneutkens** [comment]
next-css/next-sass has HMR built in. Next.js still has HMR, just not keeping the state. However next-css has some known issue, and the modules are maintained in another repository: https://github.com/zeit/next-plugins/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

When creating issues please make sure you follow the issue template so that maintainers/contributors get all the context needed to help you.
