### ISSUE TITLE
Implement Puppeteer for our test suite

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#5895]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently we're using https://npmjs.com/wd / chromedriver which fails at random on Azure Pipelines (Windows), to make the tests as reliable as possible.

## Describe the solution you'd like

@HaNdTriX already did some initial investigation / converting, however he doesn't have time to finish converting all tests. So if someone from the community wants to step in and contribute to these feel free to 🙏 it would be much appreciated. PR can be found here: https://github.com/zeit/next.js/pull/5561, however check below message under additional context.

## Additional context

The best way to do this would be to start small and progressively move tests towards the puppeteer implementation, considering we have a lot of tests.

**Comment by timneutkens** [comment]
@isaachinman so current I don't really mind chromedriver/wd anymore as it covers our cases, it just crashes on windows at random, if we could get rid of those random crashes our test suite would be pretty perfect for now 🤔

**Comment by isaachinman** [comment]
@timneutkens Ah okay, understood. Unfortunately I'm not a day-to-day Windows user so I can't really help with that. I don't have much experience with `chromedriver` but I have to say I was a bit surprised when running the test suite recently to see that it's not headless. I think it could be a lot faster if run headless.

**Comment by Janpot** [comment]
Seems like it's also spinning up a new chrome instance for each test. Might be faster if it could just open/close tabs within the same browser instance?

**Comment by isaachinman** [comment]
> spinning up a new chrome instance for each test

That's probably for the best - some of the tests here involve quite a lot and having a clean environment is important. That said, rendering a GUI is not important.

**Comment by timneutkens** [comment]
@isaachinman yeah my main concern here is that changing the tests a lot will be a massive effort for not that big returns. I really like puppeteer though.

We need to boot up a new window for every test imo because the tests are indeed very involved (some even update files etc) and we don't want residue state. Tabs might work because we run tests sequentially so that they don't conflict.

**Comment by ijjk** [comment]
I started playing around with finishing up where @HaNdTriX left off on his branch. The `should update styles correctly` test under `integration/basic` is finicky, and I haven't narrowed down why it fails off and on. 

Here's [the branch](https://github.com/ijjk/next.js/tree/migrate-jest-puppeteer) I was working off of if someone wants to take a look also. I've been running it with `yarn testonly` as coverage seems finicky also.

**Comment by isaachinman** [comment]
@timneutkens And how do you feel about changing the `wd` setup to run headless? If that's something you'd merge, I'd be happy to look into it. Just took a quick look through the `next-webdriver` stuff and am assuming it's a simple CLI flag (?).

**Comment by Janpot** [comment]
I tried to run it with the `[ 'headless', 'disable-gpu' ]` flags but that didn't seem to do anything. Didn't investigate it too much further though.

**Comment by HaNdTriX** [comment]
Hey 

First of all thank you guys for taking a shot at this.

## History

I started working on the puppeteer branch because 

- I had some free time
- I wanted to reduce the barrier for next.js contributions and
- I wanted to solve non deterministic test failures issues

While working on that task I realized that the non deterministic test failures were not caused by wd.
The test failures even got worse when using puppeteer. One problem I experienced was that it was pretty difficult to find the bottleneck, because there are so many packages and configurations involved in the process.

## Learnings

Here are some things that might cause test issues.

### 1. Synchronous file operations

Next uses synchronous file operations (e.g. `fs.readFileSync`) in tests as well in development. These methods block the main thread and **might** cause non deterministic failures. 

**Example:** https://github.com/zeit/next.js/blob/canary/test/lib/next-test-utils.js#L8

### 2. Process management

Running an integration test in next.js involves many different processes:

- Jest starts multible processes (main, worker, etc.)
- chromedriver/puppeteer starts many different processes (main, chrome, chrome-tab, chrome-tab-children, gpu, etc.)
- next starts also many processes (cli, server, webpack, etc.). Sometimes these processes are part of the jest process, sometimes not.

### 3. Timeouts

Some tests where using `await waitFor(5000/*ms*/)`. These timeouts:

- increase the time a tests need to run (the condition might be resolved after `100ms`)
- might fail because something needed longer than expected (e.g. next webpack garbage collector).

### 4. Webdriver

Sometimes the browser doesn't initialize properly. More info: https://github.com/zeit/next.js/blob/canary/test/lib/next-webdriver.js#L11-L12

### 5. Webpack

I just read the following blog post: https://nextjs.org/blog/webpack-memory/. 
I am not sure but might this has a positive impact on the tests?

**Comment by Janpot** [comment]
Another thing that could be on the table for added speed/stability is using a hosted solution to run the browser. Both [saucelabs](https://saucelabs.com/products/open-source-frameworks/selenium) and [browserstack](https://www.browserstack.com/automate) seem to have free programs for open source projects. And it looks like they both offer selenium webdriver interface.
https://www.browserstack.com/open-source
https://saucelabs.com/open-source

**Comment by ijjk** [comment]
We are no longer looking into using puppeteer and plan to keep using `wd` so that we can start testing other browsers such as IE
