### ISSUE TITLE
Firebase is retuning 404 for files in the /static folder

### ISSUE THREAD

**Issue by jzabala** [zeit/next.js#5944]
# Examples bug report

## Example name
with-firebase-hosting

## Describe the bug
I am getting 404 for assets in the /static folder when app is in firebase.

## To Reproduce
Clone this example https://github.com/jzabala/with-firebase-hosting-app. It has an image in the index. Try to serve it locally or deploy it to firebase.

## Expected behavior
I should see my image. It works with `npm run dev`

## Screenshots
![screen shot 2018-12-24 at 2 01 10 pm](https://user-images.githubusercontent.com/1315054/50404964-6a2e2f80-0784-11e9-927f-7a631fd23d5b.png)

## System information
 - OS: macOS
 - Browser: chrome
 - Version of Next.js: ^7.0.0

**Comment by oBusk** [comment]
Because `dist/functions` is deployed to Firebase hosting, the static directory is never deployed. Next never does anything with `static` when building, it just expects `./static` to be available when running. I'm not sure if that behaviour is super expected by users seeing how the documentation recommends putting images in `/static`. 

A workaround is to create a `script` in package.json
```
"postbuild-app": "cpx \"src/app/static/*\" \"dist/functions/static\" -C",
```
This script will run after building app into `dist/functions/next` and copy any content of `static` to `dist/functions/static` so that next will find it when running (inside `dist/functions`).

However this approach is not great and does not benefit from the usefullness of webpack like cachebusting and having full traceability where any static resource is used etc. Using webpack-loaders, you can import static files and get the href url to them to load them when needed. 

In next this can be done using next plugins. For example [`next-images`](https://github.com/twopluszero/next-images).

```bash
npm install next-images
```

```javascript
// src/app/next.config.js
const withImages = require('next-images');

module.exports = withImages({
  distDir: '../../dist/functions/next'
});
```

```javascript
// src/app/pages/index.js
import * as React from 'react';
import App from '../components/App';

import imgSrc from '../whatever/ethan-kent-1245767-unsplash.jpg';

export default () => (
  <App>
    <p>Index Page</p>
    <img src={imgSrc} />
  </App>
);
```
(Note that the image is put inside `whatever` rather than `static`)

With this solution, you don't need any extra script to move the static files, webpack will package the images so that they are deployed. This is a lot easier to maintain than keeping a directory of static files and loose strings to refer to them.

**Comment by jzabala** [comment]
Thank you very much for you detailed response @oBusk. It really helped me.
