### ISSUE TITLE
Router.push('/') is not working as expected

### ISSUE THREAD

**Issue by ktjd123** [zeit/next.js#5947]
# Bug report

## Describe the bug

```js
import React, { Component } from 'react';
import Router from 'next/router';

export default class _error extends Component {
  componentDidMount = () => {
    Router.push('/');
  };

  render() {
    return <div />;
  }
}
````

This is code inside _error.js. I was expected it would redirect to index.js page but nothing is happening.
The Weird Thing is When I use `Router.push('/error', '/');`, It pushes to index.js page. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Make any page. 
2. Router.push('/')

## Expected behavior
Push to index.js page

## System information
 - OS: macOS
 - Browser Chorme
 - Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
`Router.push('/')` will route to the `pages/index.js` file.

**Comment by ktjd123** [comment]
@timneutkens Yes. That is what I expected. but it's not routing to index.js page.

**Comment by ktjd123** [comment]
Oh when I test with safari, it routes to index.js page. I think it's chrome only problem.

my chrome version is chrome 71.

**Comment by ktjd123** [comment]
Checked it's fixed

**Comment by dmoli** [comment]
Hi everyone, some solution for that?

**Comment by LaylConway** [comment]
Same problem here, routing to "/" and "/index" don't work, but any other route does.

**Comment by ktjd123** [comment]
It's not currently happening to me right now, but when I had this problem this code worked. 
```js  
Router.push('/error', '/');
```

I'm not sure it's going to work in every page since I used it in _error.js page.

**Comment by LaylConway** [comment]
It works again after upgrading all packages

**Comment by ematipico** [comment]
I bumped to the same issue. The snipped provided by @ktjd123 worked.

`next` is able to change the url in the browser but somehow in doesn't trigger the `getInitialProps`

**Comment by bmamone** [comment]
Same here. I have the following:

When I'm at `/page/add` and use

`Router.push({ pathname: '/page', query: { p: object._id } }, `/page/${page._id}`)`

It won't work. It starts routing, triggers `onRouteChangeStart` then freezes.

If I change the `pathname` to any other page (even if doesn't exists'), e.g. `/banana`, it routes (if it doesn't exists it throws 404).

So, as any other use case works, I'm guessing the problem is related to being in /pageFile/subPageFile and routing to /pageFile/index again

**Comment by bmamone** [comment]
Same here. I have the following on `pages` directory:

- pages/page/index.js
- pages/page/add.js

When I'm at `/page/add` and use

`Router.push({ pathname: '/page', query: { p: object._id } }, /page/${page._id})`

It won't work. It starts routing, triggers `onRouteChangeStart` then freezes.

If I change the `pathname` to any other page (even if doesn't exists'), e.g. `/banana`, it routes (if it doesn't exists it throws 404).

So, as any other use case works, I'm guessing the problem is related to being in `/pageFile/AnySubPageFile` and routing to` /pageFile/index`.

**Comment by johntr** [comment]
> Same here. I have the following on `pages` directory:
> 
> * pages/page/index.js
> * pages/page/add.js
> 
> When I'm at `/page/add` and use
> 
> `` Router.push({ pathname: '/page', query: { p: object._id } }, `/page/${page._id}`) ``
> 
> It won't work. It starts routing, triggers `onRouteChangeStart` then freezes.
> 
> If I change the `pathname` to any other page (even if doesn't exists'), e.g. `/banana`, it routes (if it doesn't exists it throws 404).
> 
> So, as any other use case works, I'm guessing the problem is related to being in `/pageFile/AnySubPageFile` and routing to` /pageFile/index`.
> 
> EDIT: Forgot to mention, routing with `` window.location.href=`/page?p=${page._id}` `` works.

I am having the same issue. Is there a fix for this or can you just not use the Link component in this way?

**Comment by kylehotchkiss** [comment]
I also came across this with the following code:

```
componentDidMount() {
        const params = new URLSearchParams( location.search.slice(1) );
        const error = params.get('error');
        const token = params.get('token');

        if ( error ) {

        } else if ( token ) {
            console.log('Token found');
            Router.push('/dashboard');
        } 
    }
```

when i was making this, it would sometimes redirect with the hot reloading when i changed the code inside componentDidMount but didn't redirect on any hard page load. Can confirm the above `Router.push('/error', '/');` type of solution resolved it for me for now.

(next.js v8.0.4)

**Comment by amireldor** [comment]
Happening to me as well with next 8.1.0

**Comment by pr4xx** [comment]
Also started to fail for me with next 7.0.3. It worked flawlessly one or two weeks ago. I am not sure what changed since then. I did not update next.

**Comment by efleurine** [comment]
I have this behavior where the url in the browser change but getInitialProps and other React stuff are not being called so basically the page content stays the same.

http://localhost:3000/settings/store/thompson-electronics/5d10c73cc56e42a048c5d0df
http://localhost:3000/settings/store/valerio-canez-s.a./5d13c7b234a6e60fdca42c06

this happens when I am trying to switch between those 2 links which share the same page. If I click on the link while being on different page [not sharing the settings] things work normally.

**Comment by ematipico** [comment]
@timneutkens could you please reopen this? It's a real issue and we currently have it in production

**Comment by timneutkens** [comment]
@ematipico please create a new issue following the issue template with a clear and concise reproduction.

**Comment by yanivfranco** [comment]
I'm having this problem too!
I don't know how to repo this...but it seems that a specific route just not working...it triggers the router onRouteChangeStart  method.... but nothing happens. I get this when I use custom _app.js file.
Pushing not existing page works, and routes to 404 page. Wierd...any solutions guys?

**Comment by Timer** [comment]
Hi everyone! I'm going to lock this issue to prevent further "+1"s.

If you are experiencing this issue, **please open a new issue**. Thank you for your understanding!
