### ISSUE TITLE
Shallow routing still gets old query params

### ISSUE THREAD

**Issue by NicholasKuchiniski** [zeit/next.js#5997]
**To Reproduce**
- Create a page.
- Create an event that calls Router.push(newUrl, newUrl, { shallow: true });
- The new newUrl is the same page with updated query params.
- When the event is called, page re-renders, but props.url.query still has old query params.

**Expected behavior**

- props.url.query should have new query params

**System information**

- Version of Next.js: 7.0.2

**Comment by timneutkens** [comment]
Can you provide a reproduction repository?

**Comment by ivan-kleshnin** [comment]
For the interest of people facing the same issue (like me). I had this problem and the reason was that I passed `router` from `_app.js:App` through props (I attempted that to avoid `withRouter` wrapping). For some reason, `query` was sometimes outdated. When I switched back to getting `router` prop from `withRouter` the problem was fixed.
