### ISSUE TITLE
Incorrect Instructions for with-cookie-auth example

### ISSUE THREAD

**Issue by curran** [zeit/next.js#6096]
# Examples bug report

## Example name
with-cookie-auth

## Describe the bug
As a developer evaluating this example, I'm not able to run it locally.

The instructions state to install and run using:

```
npm install
npm run dev
```

However, these commands do not work, because there is no `package.json` in the directory https://github.com/zeit/next.js/tree/canary/examples/with-cookie-auth

## To Reproduce

Download the example [or clone the repo](https://github.com/zeit/next.js):

```bash
curl https://codeload.github.com/zeit/next.js/tar.gz/canary | tar -xz --strip=2 next.js-canary/examples/with-cookie-auth
cd with-cookie-auth
```

Install it and run:

```bash
npm install
npm run dev
```

## Expected behavior
The example should start.

## Screenshots
![image](https://user-images.githubusercontent.com/68416/51458332-d481c200-1d7a-11e9-82a8-2eb65bebff9e.png)

## System information
 - OS: Ubuntu
 - Version of Next.js: [e.g. 6.0.2]

## Additional context

Additionally, when navigating to the `api` directory, the command `npm run dev` (which is defined in `package.json`) does not run, yielding the error:

![image](https://user-images.githubusercontent.com/68416/51458402-127ee600-1d7b-11e9-9d77-04acf0859452.png)

The biggest problems with this example:
 * The instructions are not correct.
 * I was ultimately not able to start the API, as did not know the right commands to use.

**Comment by j0lv3r4** [comment]
Hey @curran 

I just submitted a pull request to fix this, but I'll explain what happened. 

The current folder structure of the example is set up as a [monorepo](https://github.com/zeit/next.js/pull/6101), and because currently is not possible to test a monorepo locally, further setup was needed to run the example locally. The pull request https://github.com/zeit/next.js/pull/6101 fixes that and includes the steps necessary to run it locally.

I hope this helps and I apologize for the confusion.

**Comment by curran** [comment]
@j0lv3r4 Thanks for the clarification and PR! Will review it.
