### ISSUE TITLE
[Material-UI] Using custom server in production mode does not attach MUI production classes

### ISSUE THREAD

**Issue by CalvinSundar** [zeit/next.js#6179]
# Bug report

## Describe the bug
when I was working with Material UI. the development build is working good. but when I was running production build with custom server in next js. It is not rendering the jss class correctly in production mode. It is working correctly when I was doing next build and next start(without custom server).

## To Reproduce

Clone Material UI with NextJS example from repo: 
https://github.com/mui-org/material-ui/tree/master/examples/nextjs

Create custom server.js
```
const express = require('express');
const next = require('next');
const dev = process.env.NEXT_ENV.trim() !== 'production';
const app = next({ dev });

app
  .prepare()
  .then(() => {
    const server = express();
    const handle = app.getRequestHandler();

    const port = process.env.PORT || 3000;

    server.get('*', (req, res) => handle(req, res));
    server.listen(port, err => {
      if (err) throw err;
      console.log(`Server is running on port ${port}`);
    });
  })
  .catch(ex => {
    console.error(ex.stack);
    process.exit(1);
  });
```
Run npm script:` set NODE_ENV=production && node server.js`

## Expected behavior
Next js with custom server should load the correct JSS class name in production mode(set NODE_ENV=production && node server.js ).

**Comment by timneutkens** [comment]
@oliviertassinari could you have a look 🙏

**Comment by oliviertassinari** [comment]
@timneutkens You can close the issue.

`const dev = process.env.NEXT_ENV.trim() !== 'production';`.

**Comment by Yzrsah** [comment]
@CalvinSundar 

Next and Material-UI (Branch Next) is tested and working with JSS and custom `server.js` with `NODE_ENV=production` and no build.

### To Reproduce:
- Clone the Next branch version of the Material-UI Next.js example: [Here](https://github.com/mui-org/material-ui/tree/next/examples/nextjs-next)
- Add custom server.js
- Start with `NODE_ENV=production && node server.js` script

### Outcome:
- JSS rendered correctly

---

@CalvinSundar Please provide a visual screenshot from DevTools showing incorrect JSS classes so we can understand if there's any issues.

@timneutkens The issue seems closable.

**Comment by timneutkens** [comment]
Thanks @Yzrsah
