### ISSUE TITLE
Next.js TypeScript monorepo example

### ISSUE THREAD

**Issue by steida** [zeit/next.js#6195]
Make an example from that brilliant article https://josephluck.co.uk/blog/next-typescript-monorepo

**Comment by josephluck** [comment]
I'll make a pr 😁

**Comment by steida** [comment]
I am not sure whether https://github.com/whitecolor/ts-node-dev is stable and safe enough.

**Comment by steida** [comment]
Hmm, this is the best I can do: ```"dev": "cd .. && yarn nodemon --watch api --exec yarn ts api/index.ts"```

**Comment by josephluck** [comment]
Yup, I use ts-node-dev and it's fine :-)

**Comment by josephluck** [comment]
I'm actually working on the deployment of a repo like this to serverless / lambda. Will take another week or so to finish up, but after that I'll be writing another post. If you set up your app this way, you don't need to worry about watching for file changes since serverless will handle that for you!

**Comment by NathanielHill** [comment]
I also plan on publishing a workspaces/monorepo demo soon, although without TypeScript.

**Comment by steida** [comment]
@josephluck The main problem is yarn workspace dependencies. Check https://github.com/zeit/now-builders/issues/188 Now 2 does not support Yarn workspace packages resolution like this https://github.com/zeit/now-builders/issues/188#issuecomment-460114836

Not sure whether it can be fixed in userland.

@rauchg TypeScript Yarn workspaces based monorepo with shared code Node.js example would be nice. As I see it, Now 2 does not support it yet. I experimented with it in https://github.com/este/este

**Comment by josephluck** [comment]
Yes, I have had the same experience. As far as I can tell, there's three options:

1. Make a new builder that supports workspaces out of the box
2. Publish workspaces to npm publicly 
3. Build projects locally and deploy to another serverless provider.

It's option 3 that I've gone for (deploying to aws via serverless), though I'd be keen to collaborate on a now builder that supports workspaces out of the box.

**Comment by steida** [comment]
@josephluck I would recommend to go with separated npm or yarn package.json files for now (2 haha). I have strange Yarn issues with workspaces, outdated does not work correctly and even yarn install sucks https://github.com/yarnpkg/yarn/issues/6995

And there will be yarn 2 soon. So to make things happen, separater package.json files is the must.

**Comment by josephluck** [comment]
@steida - workspace projects do indeed have separate package files, however, as you say, it's the shared code that's the problem. Really your only option if you wish to use now at the moment is to publish your packages to npm under an organisation.

**Comment by marcinczenko** [comment]
If I understand it well, this limitation is not specific to typescript, but specific to next builder. I am using now v2 in a number of monorepos, even in a private git repos. In a private repo publishing workspaces to public npm is not an option, but I am still able to build everything locally (via `yarn lerna build`) and publish everything from top level of the mono repo with just `now`. The point is that **I am not using Next in these cases but just CRA or gatsby based apps, which means I can build locally and then just use static builder.**

So looks like what we need is a version of the builder that accepts already built artefacts. So, we would like to do something like:

```
$ yarn next build
$ yarn now --prebuilt
```
`prebuilt` (or some other flag) would instruct the builder to use the output of the local `next build` rather than trying to bundle everything from scratch when deploying. We can already use `next build` to validate the build locally before requesting remote deployment, so this could be not so hard to achieve.

Sorry if I am mix something up and there is some other issue that is strictly typescript related.

**Comment by NathanielHill** [comment]
@timneutkens So, if whitelisted by `.nowignore` the shared package is uploaded to the build environment. Does that mean some logic to get `@now/next` to include those files would solve this?

**Comment by NathanielHill** [comment]
Okay, I'm assuming that the deployment is happening at the root of the repository. As in a large monorepo that defines multiple packages that are used to compose a single deployment.

Are you talking about a monorepo where packages within the monorepo are deployed individually?

**Comment by NathanielHill** [comment]
Ah, I see. Well that clearly presents some challenges. This whole time I was envisioning a monorepo that was deployed at the root.

**Comment by martpie** [comment]
Just throwing here my own TS + monorepo setup: https://github.com/martpie/monorepo-typescript-next-the-sane-way

@josephluck's is much more mature, but you might find a couple of interesting things.

**Comment by timneutkens** [comment]
Connor is working on making @now/next download the whole directory by default: https://github.com/zeit/now-builders/pull/200

**Comment by josephluck** [comment]
That's brilliant news! Amazing to see that this is being actioned so quickly.

**Comment by charliewilco** [comment]
shameless plug: i have a repo that's next, micro and typescript all deployed on now.

https://github.com/charliewilco/downwrite

**Comment by NathanielHill** [comment]
@charliewilco This issue is mainly about shared modules with yarn workspaces.

@steida Have you had any luck yet? Seems like this is working with `@now/next@canary` builder.

Should this issue be closed?

**Comment by steida** [comment]
@NathanielHill Everything works as expected so far. Good work, thank you.
