### ISSUE TITLE
with-dotenv not working when client side rendering process.env[const]

### ISSUE THREAD

**Issue by pkellner** [zeit/next.js#6229]
# Bug report

## Describe the bug
in with-dotenv example, when modifying the code to run client side (by adding a route to /about and back to / again), process.env["TEST"] works but const str="TEST;process.env[str] return undefined.

process.env behaves differently when a constant is passed as an indexer versus hard coding that constant

## To Reproduce
modifications made to with-dotenv and placed in this repo:  https://github.com/pkellner/with-dotenv-bug
Going back and forth between about and home page shows the problem.  On static page load of home, the environmental variable outputs as expected, but on linking to that page, undefined is returned.

Steps to reproduce the behavior, please provide code snippets or a repository:
download https://github.com/pkellner/with-dotenv-bug
npm i  {make sure nasty  bug stopping build from working is fixed https://t.co/VzjGl9JjGF }
npm run dev
go back and forth between / and /about

## Expected behavior
should show correct value in all three outputs both server and client side rendering

## System information
 - OS: macos and windows
 - Browser chrome
 - Version of Next.js:7.02

**Comment by Ephem** [comment]
The `dotenv-webpack`-plugin currently does not support accessing a variable dynamically like you are trying to do. See [this issue](https://github.com/mrsteele/dotenv-webpack/issues/139) and the related one for details.

This has to do with how the `dotenv-webpack`-plugin works. It inlines all env-variables at build time with `DefinePlugin` and does not resolve dynamic ones to avoid leaking sensitive values. The reason it works serverside is because the real `process.env` is available there. :)

I haven't tried them myself, but the Readme in the example mentions trying out these two if you need runtime support:

* [next-runtime-dotenv](https://github.com/tusbar/next-runtime-dotenv)
* Example [with-universal-configuration-runtime](https://github.com/zeit/next.js/tree/canary/examples/with-universal-configuration-runtime)

I hope that helps!

**Comment by timneutkens** [comment]
Great explanation @Ephem! Probably also good to note that it's best to start using https://github.com/zeit/next.js#build-time-configuration when Next.js 8 is released 👍
