### ISSUE TITLE
update next version from 7 to 8, can not resolve _document.js file？

### ISSUE THREAD

**Issue by forMine** [zeit/next.js#6399]
when I want to update next to version 8.0.2, I got this problem:

Can't resolve 'private-next-pages/_document.js' in ...(my project folder);

help me~

**Comment by abathz** [comment]
@forMine i got this problem too but in may project is can't resolve 'private-next-pages/_app.tsx'

**Comment by forMine** [comment]
> @forMine i got this problem too but in my project is can't resolve 'private-next-pages/_app.tsx'

I delete the webpack config about "config.resolve.alias" and this problem disappeard
but I got a new problem:
Cannot find module '../core-js/object/define-property'

**Comment by timneutkens** [comment]
Please follow the issue template and provide a clear and concise reproduction.

**Comment by nihgwu** [comment]
@forMine I think you have to change `config.resolve.alias = { 'xx': 'yy' }` to `config.resolve.alias = { ...config.resolve.alias, xx: 'yy' }`

**Comment by Vitaminaq** [comment]
Maybe webpack. resolve conflicts with the default configuration. I also configure webpack. resolve. alias and then can't resolve'private-next-pages/_document. tsx'. The solution is to downgrade the next version to 7.0.2 or to set alias without using webpack. resolve instead of using babel-plugin-module-resolver.
