### ISSUE TITLE
Add ES module entrypoint to be Pika compatible 

### ISSUE THREAD

**Issue by Pr0x1m4** [zeit/next.js#6515]
# Feature request

## Pika compatibility.
Pika, a new "bundler" to use/serve optimized ES modules over HTTP/2 doesnt seem to be able to add next as a dependency. This is because next does not currently list an ES module entrypoint.

[More Information on Pika](https://github.com/pikapkg/web) 
[Next package on Pika](https://www.pikapkg.com/packages/?q=next)
 
## Possible Solution
Add an ES module entrypoint to next to be able to work with Pika

## Additional context
An error I received trying to add next as a dependency under `pika`

`package.json`
```json
{
  "name": "with-pika",
  "version": "1.0.0",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "prepare": "pika-web",
    "start": "next start"
  },
  "dependencies": {
    "next": "latest",
    "react": "^16.7.0",
    "react-dom": "^16.7.0"
  },
  "license": "ISC",
  "@pika/web": {"webDependencies": ["next", "react", "react-dom"]},
  "devDependencies": {
    "@pika/web": "^0.2.0"
  }
}
```

`error from npm`
```bash
yarn install v1.12.3
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
$ pika-web
⠼ @pika/web installing...
✖ dependency "next" has no ES "module" entrypoint.

Tip: Find modern, web-ready packages at https://pikapkg.com/packages

Done in 0.67s.
```

**Comment by timneutkens** [comment]
Next.js actually is a compiler by itself, so to use Pika we'd have to integrate it into how Next.js works. We can't expose a single esmodule.

We'll be keeping an eye on it 👀 It's a really interesting bundler 👍

**Comment by dangodev** [comment]
Just ran across this issue searching for @pika/web info because I too am 👀 keeping an eye on it!

A little extra info: only the client-side-consumable modules like `next/head` or `next/router` would need to be in ESM (basically anything loaded in-browser).

The build & dev server utilities (`next build`, etc.) could remain untouched, in CommonJS. Probably would require a change, but might not be very much work at all!

My money is actually on @pika/web to replace webpack eventually. Because it offloads so much onto the browser, in all the right ways. On HTTP/2 it’s objectively better in just about every way. The only thing now preventing adoption is client-side npm packages written in CommonJS still.
