### ISSUE TITLE
Preloaded scripts warning

### ISSUE THREAD

**Issue by steida** [zeit/next.js#6517]
It's the same like https://github.com/zeit/next.js/issues/2022

```
The resource was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

I am not doing anything weird. Just Link prefetch. It seems it's probably ok, but it can be confusing so maybe docs can be updated.

https://github.com/GoogleChromeLabs/preload-webpack-plugin/issues/8#issuecomment-277105884

**Comment by pantharshit00** [comment]
I can confirm this. 

Chrome Version: 72.0.3626.121

Even official Zeit site has these warnings: 
![image](https://user-images.githubusercontent.com/22195362/53693044-1d885580-3dc0-11e9-99b9-8344a0577aad.png)


I think we should use link prefetch for these routing operations as these are not being immediately consumed by the user.

**Comment by developit** [comment]
Just confirming from the Chrome side here - the way Next is preloading is totally fine. We're hoping to turn off these warnings for resources preloaded with `priority=low` once that ships.

As a comparison point, if these resources were preloaded via a Service Worker, we wouldn't show any warnings even though the same amount of networking is being done.

**Comment by josephrexme** [comment]
I'm not using Next but I get these warnings. My explanation of the problem is that it preloads all my routes defined for react router since I use the [router-based code splitting](https://reactjs.org/docs/code-splitting.html#route-based-code-splitting). Can I have it only preload the ones specific to a page and perhaps prefetch the rest or do nothing at all?

**Comment by joaovieira** [comment]
I just noticed all of our prefetched links are being downloaded with High priority.

While `<NextScript>`s make sense to be preloaded as they'll all be needed for the current page, any link prefetched with `<Link prefetch>` is a hint that the page/bundle might be needed in the future. Couldn't we use [`<link rel="prefetch">`](https://developers.google.com/web/fundamentals/performance/resource-prioritization#prefetch) in that case? 

As is, prefetched bundles are being downloaded with High priority instead of Low, unnecessarily. Or am I missing something (e.g. Safari support)?

**Comment by Odrin** [comment]
Why is this closed? According to [this google article](https://developers.google.com/web/fundamentals/performance/resource-prioritization#prefetch) we should use `prefetch` instead of `preload`. At least this should be configurable. And `Link` prop name `prefetch` is very confusing at this point.

**Comment by trainto** [comment]
Firsit time I saw the warning, I thought I've must done something wrong. I tried to figure it out what caused this warning, and I ended up finding that messages also can be seen event nextjs.org site.
I think it should be handled to prevent spending hours for nothing like me.

**Comment by okeybond** [comment]
sorry, this is still an issue,

<img width="384" alt="Screenshot 2020-06-01 at 15 21 04" src="https://user-images.githubusercontent.com/48156152/83418632-d8682e80-a41b-11ea-9c11-655f45d249af.png">

**Comment by timneutkens** [comment]
https://github.com/vercel/next.js/issues/6517#issuecomment-469063892

**Comment by daveteu** [comment]
Still an issue today, flooded with the preloaded warnings.

**Comment by innocentdavid** [comment]
I got same issue when I tried to reload a [slug].js page

**Comment by miko866** [comment]
Same issue here when I tried navigating to a [slug].jsx page.
