### ISSUE TITLE
Where do Providers Go?

### ISSUE THREAD

**Issue by zachariahtimothy** [zeit/next.js#659]
Loving the idea of NextJS so far! One thing I am not getting is how I can wrap the root app component in a provider such as ApolloProvider or IntlProvider. I have tried in _document.js but it seems that <Main /> cannot be overwritten so the IntlProvider does not propagate down the component tree. 

I tried this in the Document render method:
````
<IntlProvider locale={locale}>
   <Main />
</IntlProvider>
````
Using: next@2.0.0-beta.13
Any ideas?

**Comment by iamjacks** [comment]
Maybe [this example](https://github.com/nmaro/apollo-next-example) will help? There's also some discussion at #387.

**Comment by nkzawa** [comment]
Also check [this example](https://github.com/zeit/next.js/tree/master/examples/with-styletron).

**Comment by ads1018** [comment]
@zachariahtimothy I'm running into the same issue trying to get Apollo to play nice with Next. The fact that we can't pass down context from `_document.js` is problematic. Passing it down on every individual page isn't very dry. @nkzawa @rauchg is there any change we can make to the API so that context doesn't get wiped when wrapping `<Main />`?

**Comment by nkzawa** [comment]
@ads1018 What we recommend is to wrap every page with provider.

@rauchg It seems many people wonder about this. I think we should a document about this topic.

**Comment by ads1018** [comment]
@nkzawa I think most of us understand that it's recommended we wrap every page with providers. The issue we're raising is that it makes more sense to wrap our app with a provider *once* at the root level (preferably in _document.js) as opposed to inside every page.

**Comment by zachariahtimothy** [comment]
Totally agreed @ads1018 .  I am a fan of the DRY principle so for my larger, enterprise app, adding multiple providers to every page is a total non-starter.

**Comment by rauchg** [comment]
Personally I 100% prefer _explicit wrapping_ over "nicer looking". It just scales better (in terms of understanding and the ability of others to work on your stuff), than hidden global files.

The only reason we have `_document` is that React can't control the entire markup, otherwise we'd be asking you to wrap everything :D

In my experience as well, you always _think_ that every part of your system abides by the same rules, but you end up finding later that it's not the case. 

When I set out to [clone HN](https://github.com/now-examples/next-news), it would have been very tempting to create a global layout in `_document` for everything.

![image](https://cloud.githubusercontent.com/assets/13041/21722108/1e199df2-d3e0-11e6-92af-efe19e714d2e.png)

After all every page seems to have some simple rules, like the navigation bar, background, etc.

Except that the login page is completely different

![image](https://cloud.githubusercontent.com/assets/13041/21722128/2ed596be-d3e0-11e6-95aa-43bb497ba9c4.png)

_<cue argument that it looks unpolished, but that's how it is>_

This, in my opinion, is a *strength of this system*. You're not constrained by artificial layout systems that are later hard to escape from.

This also applies to providers. We'll do our best to document it in the FAQ that we'll be putting together in the Wiki.

**Comment by ads1018** [comment]
Thanks for sharing. I have a better understanding of why you went this route now. Are providers purposefully getting ignored in _document.js in order to enforce this opinion? Otherwise, we could cater to both camps: those who prefer a global provider and those who prefer to explicitly include them on a per-page basis.

**Comment by rauchg** [comment]
Agreed. I think we should re-open an issue to explore / document the limitations of `<Document>` with regards to that

**Comment by sedubois** [comment]
@rauchg AFAIK your example above has another cost (from what I understood of @arunoda's [explanation](https://github.com/zeit/next.js/pull/301#issuecomment-263191563) about CommonsChunkPlugin): just because one page doesn't use some modules (like navigation in your example), it forces all other pages to have their own copy of those modules. 

If I have a [webapp](https://github.com/RelateNow/relate) which uses Apollo on 95% of its pages, it's indeed better if the 5% of static pages don't need to load Apollo, but it would also be better for Apollo to still load only once in the other pages.

It would be awesome if CommonsChunkPlugin could also extract the modules which aren't common to all pages but still common to several of them, would that be feasible?

**Comment by arunoda** [comment]
@sedubois yep. We need such a functionality. But currently, it's not possible.
So I created an issue here: https://github.com/zeit/next.js/issues/738

**Comment by jgautheron** [comment]
@zachariahtimothy I integrated `react-intl` with the help of `redux`, if you need an example, I'll post one gladly.

**Comment by zachariahtimothy** [comment]
That would be tremendous!

**Comment by jgautheron** [comment]
Here you go: https://github.com/jgautheron/nextjs2-react-intl

**Comment by sedubois** [comment]
I also just added i18n to my app if it helps: https://github.com/relatenow/relate
