### ISSUE TITLE
with-reasonml example - `not compatible with next@8

### ISSUE THREAD

**Issue by JakubMarkiewicz** [zeit/next.js#6806]
# Examples bug report

## Example name
with-reasonml

## Describe the bug
Both development and production builds not working on fresh cloned example using ` next@8 `.
```
The default export is not a React Component in page: "/"
Error: The default export is not a React Component in page: "/"
    at Object.renderToHTML (/home/kuba/personal/temp/with-reasonml-app/node_modules/next-server/dist/server/render.js:70:19)
```

## To Reproduce
1. Clone with-reasonml example
2. Install packages.
3. Fire dev or prod to see an error

## Expected behavior
App should be working as intended (` next@7.0.x ` is working) 

## System information
 - OS: Ubuntu 18.10
 - Version of Next.js: [e.g. 8.0.3]

**Comment by Enalmada** [comment]
I am using reasonml and stuck on Next 7 because of this.  I had the same trouble and tried to fix (https://github.com/zeit/next.js/issues/5929), but the workaround I believe is flawed and just addressing a symptom of the real problem.  I think the real problem is caused by something related to this issue https://github.com/zeit/next.js/pull/5857 but have no idea what to do to get nextjs 8 working with reason like 7 was. 

Someone please help!

**Comment by JakubMarkiewicz** [comment]
@Enalmada It's working on @8.1.x now.

**Comment by sync** [comment]
i don't think so

**Comment by sync** [comment]
It seems to be only possible to return a promise if you tell bucklescript to use es6.

See this for example:
https://github.com/sync/my-reason-next

**Comment by JakubMarkiewicz** [comment]
I also came across this problem last night but i think it deserves separate issue, previously app couldn't even be built.

**Comment by sync** [comment]
how about we update the sample ? https://github.com/zeit/next.js/pull/7254

**Comment by JakubMarkiewicz** [comment]
Great, it's merged now on canary, thanks :)
