### ISSUE TITLE
How to use webpack's resolve.modules feature for easier import statements?

### ISSUE THREAD

**Issue by SpencerCDixon** [zeit/next.js#714]
Was just curious if this is currently possible?

I have my `next.js.config` set up as:

```
const path = require('path');

module.exports = {
  webpack: (config, { dev }) => {
    config.resolve.modules.push(
      path.resolve(__dirname, './util')
    );

    return config;
  }
}
```
I am running **next 2.0.0-beta.16** and when I try to import from `util/myService.js` it just throws an error saying it can't find the thing I'm trying to import.

Am I missing something?  Or do I just need to use a babel plugin for this for now?

Having fun playing around with this lib!  Thank you for open sourcing it. :clinking_glasses:

**Comment by arunoda** [comment]
@SpencerCDixon we do support it.
In this case, you simply need to use `import 'myService.js'`. 

But it's not working for pages. It's only meant for NPM modules resolving. Not for page resolving. Due to our SSR nature, we need to implement this feature on service side as well. 

That's kind a hard and that's not in our current plan.

Here's something similar: https://github.com/zeit/next.js/issues/342#issuecomment-269897913

**Comment by SpencerCDixon** [comment]
Wow thanks for the quick response and duh that totally makes sense.  Getting late, time to stop working haha.  Thanks!
