### ISSUE TITLE
Next.js document.referrer is empty. Can't create a back button.

### ISSUE THREAD

**Issue by 4ortytwo** [zeit/next.js#7269]
# Bug report

Hello everyone!
I'm currently working on the back button for my app and really need someone's help with it.

## Describe the bug

This is a simple user flow:

I visit the home page with a list of products.
I open a single product page.
*1 - I click the 'BACK' button and go back with (Router.back()); <--- ok, everything is fine here, I'm back on the home page.

*2 - Now, I visit a single product page from a different site, I just copied and pasted the url while I was on FB, for example.

I am on a single product page and clicking the back button.
That sends me back to FB. <--- this is my problem.
I tried to access document.referrer to use its content for conditional redirection
(if (not my app's domain) redirect to home page, so that I don't spoil the user experience while they are in the app) but it is empty(it's just ""). I tried accessing it on any other site and it is filled with the actual referrer.

## System information
 - OS: [macOS 10.14.4]
 - Version of Next.js: [e.g. 7.0.2 ]

## Additional context

Have a good day, everyone!

**Comment by timneutkens** [comment]
Just from reading this, you implemented a `back button` inside of your UI, that shouldn't use `window.back()`, it should use a `<Link>` to the page you want to go to, otherwise sure you get the result that you saw, there's nothing Next.js can do here, it just calls `window.back()` when calling back on the router.
