### ISSUE TITLE
Serverless Next.js on AWS Lambda

### ISSUE THREAD

**Issue by FarhadG** [zeit/next.js#7560]
As I've been reading about Next.js' recent features around serverless, I have a few questions in ensuring it meets our needs. As I understand it, AWS Lambda has the following limitations and I’m unsure on how to resolve them using best practices with Next.js:

1. 52mb limit size with AWS Lambda. Although it would be hard to imagine our application going above this limit, I’m worried that with a large node_modules directory, this could, potentially, be an issue in the future. What are some ways to go around this?

2. Performance and cold starts. I understand that if the Lambda function is not periodically executed, the boot up time to execute the Lambda service can range between 600-2500ms. This is not acceptable for a user facing client application. What are some ways to mitigate this?

3. Hydrating redux state. Any best practices for rendering redux state as part of the initial payload?

4. CDN. Given that these templates are generated at runtime, are there any simple/scalable ways to offer them over CDN (e.g. Cloudfront)?

5. Intelligent template caching. We have cases where certain elements are hidden if the user is not logged in. We want these to be the only pages that are indexed by search engines (ie SEO). That said, if we cache our templates, how can we ensure that we don’t serve incorrect templates to these engines (e.g. ones that include sensitive data for users that are logged in in any given page).

**Comment by bhurlow** [comment]
@FarhadG here are some answers to your questions at least from my specific perspective / experience

1. Using Webpack to inline all node_module dependencies into a single file does a lot to reduce to overall bundle size. Next.js will create a bundle per page so the size per lambda is much smaller than a whole app

2. This has never been an issue for us in practice. Actually in our case we think the cold start time is totally acceptable for client facing applications since it happens so seldom. Have heard of some people using a ping checker to keep their lambda awake

3. We hydrate redux using the result of `getInitialProps()`

4. Use the `assetPrefix` for CDN stuff, see here: https://github.com/zeit/next.js#cdn-support-with-asset-prefix. 

5. The next.js page templates are executed to produce the page HTML, assuming the SEO bots are not logged in (let's hope), they would get the rendered result of a regular not-logged-in user

**Comment by bhurlow** [comment]
also @FarhadG https://github.com/zeit/next.js/tree/canary/examples/with-redux

**Comment by FarhadG** [comment]
Thank you for the informative response, @bhurlow
