### ISSUE TITLE
worker-loader set cdn by assetPrefix can not build cdn path only "/"?

### ISSUE THREAD

**Issue by unrealyan** [zeit/next.js#7589]
const withLess = require('@zeit/next-less')
const path = require('path')
const withCSS = require('@zeit/next-css')
const webpack = require('webpack')
const withWorkers = require('@zeit/next-workers')

const assetPrefix = process.env.CDN === 'production' ? "http://cdn.XXX.cn/" : (process.env.CDN === 'test' ? "http://cdn.t.XXX.cn/" : "")

const withBundleAnalyzer = require("@zeit/next-bundle-analyzer");

module.exports = withBundleAnalyzer(withWorkers(withCSS({
    distDir:"_next",
    assetPrefix,
    // postcssLoaderOptions: {
    //     // parser: "true",
    //     config: {
    //         ctx: {
    //             theme: JSON.stringify(process.env.REACT_APP_THEME)
    //         }
    //     }
    // },
    // cssModules: true,
    analyzeServer: ['server', 'both'].includes(process.env.BUNDLE_ANALYZE),
    analyzeBrowser: ['browser', 'both'].includes(process.env.BUNDLE_ANALYZE),
    bundleAnalyzerConfig: {
        server: {
            analyzerMode: 'static',
            reportFilename: '../bundles/server.html'
        },
        browser: {
            analyzerMode: 'static',
            reportFilename: '../bundles/client.html'
        }
    },
    webpack(config, options) {
        options
        // config.output.publicPath = assetPrefix
        config.resolve.alias = {
            styles: path.resolve(__dirname, './styles'),
            static: path.resolve(__dirname, './static'),
            components: path.resolve(__dirname, './components'),
            combinations: path.resolve(__dirname, './combinations'),
            workers: path.resolve(__dirname, './workers'),
            api: path.resolve(__dirname, './api'),
            utils: path.resolve(__dirname, './utils'),
            ...(config.resolve.alias || {})
        }
        config.output.globalObject = `(typeof self !== 'undefined' ? self : this)`;
        const originalEntry = config.entry
        config.entry = async () => {
            const entries = await originalEntry()
            console.log(entries['main.js'], "entries")
            if (
                entries['main.js'] &&
                !entries['main.js'].includes('./polyfills.js')
            ) {
                entries['main.js'].unshift('./polyfills.js')
            }

            return entries
        }

        // config.plugins.push(
        //     new webpack.ProvidePlugin({
        //         'Swiper': 'swiper',
        //     })
        // )

        return config
    },

    // workerLoaderOptions: { publicPath:`${assetPrefix}/_next/` },
    // lessLoaderOptions: {
    //     javascriptEnabled: true,
    //     // theme antd here
    //     modifyVars: {
    //         // '@primary-color': '#ffdb15',
    //         // "@link-color": '#ffdb15',
    //     }
    // },
})))`![image](https://user-images.githubusercontent.com/5870143/59574913-a87d2980-90eb-11e9-93e3-5623b6ea8d28.png)

**Comment by robertistok** [comment]
Hello @unrealyan!

Please describe your problem more clearly, it is really hard to understand what is going on and how to reproduce your issue. You can use the template down below for filing a bug report.



# Bug report

## Describe the bug

A clear and concise description of what the bug is.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior

A clear and concise description of what you expected to happen.

## Screenshots

If applicable, add screenshots to help explain your problem.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2]

## Additional context

Add any other context about the problem here.
