### ISSUE TITLE
Add __source to JSX transformation for better DX

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#764]
https://www.npmjs.com/package/babel-plugin-transform-react-jsx-source
https://github.com/zeit/next.js/blob/dbecc2a701a79b2d32d9b1ef176b7952953435cc/server/build/babel/preset.js

h/t @gaearon for the pro-tip

**Comment by gaearon** [comment]
(Only in DEV) ;-)

**Comment by rauchg** [comment]
#devmodegate

**Comment by arunoda** [comment]
@rauchg how do we identify whether we are on the dev mode or not?
If we are doing to add this our babel preset, we need a way to pass that.

CRA is doing that with an NODE_ENV. Seems like we are not depending on NODE_ENV for the build time. I think we should set it while doing `next build` and `next start`.

If so, this is so eazy to do. Otherwise, we could add it directly to the webpack config.

**Comment by timneutkens** [comment]
This is incredibly nice 😄
