### ISSUE TITLE
Vue.js Support?

### ISSUE THREAD

**Issue by sebastianmacias** [zeit/next.js#77]
Would you plan to support vue.js as an alternative to react?

**Comment by jiyinyiyong** [comment]
Maybe we should start it from the Vue side @yyx990803 @defcc

**Comment by chrisvfritz** [comment]
I'm actually checking out this project for inspiration as we think about how to improve the SSR experience with Vue. 🙂  I think next.js is probably better off staying focused on React, but it's likely we'll be stealing some ideas.

**Comment by jiyinyiyong** [comment]
Vue2 it now much more similar to React because of the heavy use of virtual DOM, except for some stateful code to initialize a Vue app, you can read the [docs](https://vuejs.org/guide/ssr.html) and some of my repos since I was working on building static sites with Vue2 in the past weeks:
https://github.com/coffee-js/vue-coffee-workflow
https://github.com/ElemeFE/vue-pages-workflow

**Comment by impronunciable** [comment]
We have the idea of allowing the use of different renderers. The first that we had in mind were preact and inferno because those try to be as close as they can to react but it would be great to opem the game to frameworks like vue too

This is the issue/thread on topic #20

**Comment by chrisvfritz** [comment]
@impronunciable Sounds rad. 😄  I can foresee a few differences that would make a custom renderer on its own insufficient, but when/if you get to the point of exploring Vue integration, we'd be happy to collaborate.

**Comment by jimt** [comment]
[Nuxt](https://github.com/nuxt/nuxt.js) has appeared for Vue. It could be cool if bits were cross-pollinated back into Next.

**Comment by obiwarn** [comment]
Given the current momentum of vue on Github (40 000 stars) it seems it could be the successor of react (50 000 stars). So: yes please. Vue is awesome!

**Comment by zhaoyao91** [comment]
@obiwarn one reason for the high number of stars of vue is that vue is created by chinese people and it has great chinese docs, so it appeals to many chinese, and, you know, the population of China is so large.
Vue is good, right, but I don't think react will be defeated by vue. (IMO, vue is much like a template sugar for react).

**Comment by FrancosLab** [comment]
@zhaoyao91 Not completely sure if that first sentence should be taken seriously lol, Vue definitely has seen good usage and support from Chinese companies but I don't think that's necessarily what drives the Vue community. 

Even if Vue doesn't "defeat" react, which shouldnt matter anyway, because both are tools that do a similar job while accomplishing a different DX, Vue is still a good framework for the front-end, and saying it's simply "template sugar for react" is a huge understatement. 

Nonetheless, Nuxt.js is awesome but would definitely would love to see Vue support in Next.js.

Next.js tagline could eventually become "Framework for server-rendered Javascript apps"

**Comment by zhaoyao91** [comment]
@FrancosLab sorry if my words lead to some misunderstanding :(. With the first sentene, which seems fail to be funny, I just want to express that there are many Chinese programmers who stick to Chinese docs and don't like to read any English docs, and it's not a good phenomenon. "template sugar for react" is indeed an understatement, sorry, I should say it offers a template layer compared with react.

BTW, both react and vue are good, hope them compete and evolve into better stages.

Now let's turn back to this issue. As I see nuxt is much like a vue version of next. if it will continuously follow the next.js way, do we really need to support vue in next.js?

**Comment by Atinux** [comment]
Nuxt.js started as a copy of next.js for vue.js. Actually, even with the version `0.9.7`, nuxt can do everything that next.js does.

With the time, we started to add more features and differentiate each other while keeping the same philosophy.

Few of the features
- Generate static application server-rendered on build time (see https://nuxtjs.org/guide#static-generated)
- Possibility to create dynamic routes via the filesystem API
- [Custom layouts](https://nuxtjs.org/guide/views#layouts)
- Middleware (coming this week)
- [Store integration](https://nuxtjs.org/guide/vuex-store) (Vuex) 
- Using [nuxt.js programmatically](https://nuxtjs.org/api/nuxt) (I believe next.js was inspired by us for this one, see [Guillermo tweet](https://twitter.com/rauchg/status/799445113982291968))

I really love next.js and the team behind zeit and we will keep improving nuxt.js the maximum we can.

**Comment by impronunciable** [comment]
Since [nuxt.js](https://nuxtjs.org) it's a strong project and next opened the game for other renderers I think I can close this one. It will be interesting to see a next example with vue as the component renderer but nuxt it's a pretty good place to redirect to :)

**Comment by adrianmcli** [comment]
Nuxt.js seems to have some AMAZING docs. I think we can do a little better with Next.js on this front. Should I make a new issue for this? If we decide to get some revamped docs, I would love to contribute to that.

**Comment by sedubois** [comment]
@adrianmcli I think that would be amazing 👍 And once it's up it could also host a proper gallery of examples together with a link to a live demo on Now for each of them

**Comment by adrianmcli** [comment]
It goes without saying that these docs should be built on top of Next.js 😝  I'll see if I have some time later this week, I could get the ball rolling on this.

**Comment by sedubois** [comment]
🎉🎉

**Comment by rauchg** [comment]
In what ways are the docs lacking @adrianmcli? I usually have a harder time with custom docs websites than GitHub. Is it just me?

**Comment by adrianmcli** [comment]
@rauchg the content of the current README is great, but its presentation leaves something to be desired.

To me, the most important thing with large docs is quick access to the TOC (typically via a persistent side-nav) so you have a good sense of context and where you are in the document. It also provides the user with more confidence in jumping around. The current TOC is starting to get long because of how much information we have to convey, and it makes it a little unwieldy.

Overall, the Nuxt.js docs feel more structured and organized. The trade-off is that not all the information is on one page which will make it hard to grep/cmd+f.

**Comment by egoist** [comment]
In case you are interested, I made [unvue](https://github.com/egoist/unvue) which is similar to Next.js/Nuxt.js but without using file system as the router API, you can control all the things, and it's totally fine if you want to use it to build your own Nuxt.js on the top of it.
