### ISSUE TITLE
nested routes/sub routes

### ISSUE THREAD

**Issue by sarbbottam** [zeit/next.js#78]
Something similar to https://react-router.now.sh/route-config ?

An example would be of helpful.

**Comment by nodegin** [comment]
please check issue #59
https://github.com/zeit/next.js/issues/59

**Comment by impronunciable** [comment]
We have the idea of allowing the use of different renderers. The first that we had in mind were `preact` and `inferno` because those try to be as close as they can to `react` but it would be great to opem the game to frameworks like vue too

This is the issue/thread on topic https://github.com/zeit/next.js/issues/20
