### ISSUE TITLE
Deprecate automatic insertion of <a> for <Link>

### ISSUE THREAD

**Issue by rauchg** [zeit/next.js#796]
It's an anti-pattern. I'd like `<Link>` to only be an abstract higher-order component that decorates whatever is inside

**Comment by tpreusse** [comment]
Currently when using `styled-components` one needs a pretty odd setup:
```
import NextLink from 'next/prefetch'
import styled from 'styled-components'

const Link = ({children, className, ...props}) => (
  <NextLink {...props}><a className={className}>{children}</a></NextLink>
)

export default styled(Link)`
  color: tomato;
`
```

Using a `styled.a` (or anything else that maps `href` to an `a`) inside `NextLink` is not possible because it will fail the `child.type` test. Maybe remove all the magic and checking completely and add a warning in some other way? Maybe in the `onClick` handler?

**Comment by timneutkens** [comment]
@tpreusse please see https://github.com/zeit/next.js/issues/816
