### ISSUE TITLE
async generator vs syntax transform

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#851]
I don't know much about these things, but was wondering if there's a reason to prefer async generator/regenerator vs. something like [fast-async](https://github.com/MatAtBread/fast-async) which _claims_ to be 3-4 times faster?

**Comment by timneutkens** [comment]
Interesting. I'll try to benchmark changing this.

**Comment by timneutkens** [comment]
Apparently fast-async doesn't support calling await on normal functions that don't return a Promise. So if you, for example make a component which has a `static getInitialProps` instead of `static async getInitialProps` it will fail. Also, we have to drop the es2015 preset to implement fast-async, since it conflicts with babel-plugin-transform-runtime 😢 Also looked into [kneden](https://github.com/babel/kneden) but that one is unmaintained from the looks of it.

**Comment by timneutkens** [comment]
If there is something else we can look into please let me know 👍 😄

**Comment by sedubois** [comment]
Thanks for looking that up. Would be good to give the feedback over there

**Comment by sedubois** [comment]
@timneutkens I opened an issue over there and there are suggestions on how to fix your concerns: https://github.com/MatAtBread/fast-async/issues/32#issuecomment-276014312

**Comment by TooTallNate** [comment]
> So if you, for example make a component which has a `static getInitialProps` instead of `static async getInitialProps` it will fail.

To implement this properly we just need to wrap the getInitialProps return value with `Promise.resolve()`. (something like `await Promise.resolve(this.getInitialProps())`). It seems weird to me to rely on the parser for that behavior.

**Comment by timneutkens** [comment]
@TooTallNate Fair point. Will have a look into that 👍

**Comment by timneutkens** [comment]
Going to close this as the fast-async functionality seems to be going to go into babel 7, which we use now for Next.js.
