### ISSUE TITLE
Represent full HTML tree in a page

### ISSUE THREAD

**Issue by matthewmueller** [zeit/next.js#86]
I've also been exploring this too. Definitely think this is the right direction forward. One simplification that I think can be made is to represent the entire HTML tree in the page, so instead of this:

``` js
export default () => <div>
  <Head>
    <meta content='my meta' />
  </Head>
  <h1>I can haz meta tags</h1>
</div>
```

With side-effect and DOM-reaching craziness, you could do something like this:

``` js
export default () => (
  <html>
     <head>
       <meta content='my meta' />
     </head>
     <body>
       <h1>I can haz meta tags</h1>
     </body>
  </html>
)
```

Implementation goes like this:
- On the server, the whole tree will be rendered.
- On the client, the `html` component reaches into the children, finds the first child in `body` and returns that.

**Comment by ddibiase** [comment]
I've also been experimenting with representing the whole DOM in memory and rendering on page load for the better part of a year. Seeing some pretty incredible speed and performance as a result. This is definitely the right direction and you guys have done some stellar work so far!

We originally tied our solution to React but moved away to make it more framework agnostic (that being difficult because of the JSX dependency). Matter of fact our project is called Nex, very similar to Next.js but a solving a slightly different problem.

Kudos for a fantastic initial release.

**Comment by mmmeff** [comment]
This is related to both #50 and #75

**Comment by timneutkens** [comment]
@matthewmueller can this be closed in favor of `_document.js`?

**Comment by timneutkens** [comment]
Closing. If needed you can re-open ❤️
