### ISSUE TITLE
Duplicate viewport tag

### ISSUE THREAD

**Issue by Dremora** [zeit/next.js#8654]
# Bug report

## Describe the bug

viewport tag gets duplicated in the browser (there's no custom viewport tag provided).

## To Reproduce

This occurs on our site, but I've noticed that nextns.org has the same issue, so the instructions are for it:

1. Go to https://nextjs.org
2. Wait for the page to load
3. Inspect the element tree
4. Search for `"viewport"`, you'll see two occurrences

## Expected behavior

There should only be one.

## Screenshots

![image](https://user-images.githubusercontent.com/242202/64430115-773f4480-d0af-11e9-99fd-0b8be4ad6d73.png)

## System information

- OS: macOS
- Browser (if applies): Chrome
- Version of Next.js: 9.0.5

**Comment by Janpot** [comment]
@Dremora It seems like the provided page https://nextjs.org doesn't show the issue (anymore?).

In my case, I had a duplicate viewport tag because I defined mine in `_document.js` instead of `_app.js`. It also had a `key` property. Moving it to `_app.js` and removing the `key` property solved the issue for me.

**Comment by Timer** [comment]
Solved by https://github.com/zeit/next.js/pull/8960
