### ISSUE TITLE
Static assets are not prefetched

### ISSUE THREAD

**Issue by sedubois** [zeit/next.js#869]
My next.js proto uses next/prefetch, which allows to load pages even when connectivity drops. However, my image stored in `/static` is not cached and will thus fail to load. Even if connectivity stays, it also means that the images will flash as they get re-loaded every time the user navigates to the page.

**Comment by timneutkens** [comment]
Hi @sedubois, could you provide an example? ❤️

**Comment by sedubois** [comment]
Sure, always the same ;) https://relate.now.sh. Just load the page, then kill your network, go to About then back home (Relate): image has disappeared.

**Comment by arunoda** [comment]
@sedubois `next/prefetch` also does not prefetch images. It's only the JS code related (NPM modules, your code, etc). We never run the page.

**Comment by sedubois** [comment]
I think it would make sense to prefetch those assets too. After all, they don't change at all, and the whole aim is to have an instantaneous page load.

**Comment by arunoda** [comment]
You are proposing a whole new feature which could (and should be) lives outside of next.js core. You could use `next/prefetch` to load JS code and write some other logic to load images, data and etc.

I'm gonna close this issue since this is what we are going to do with Next. (At least we don't have it in the short term plan)

But this is a important topic. So, I you could start another issue to discuss about this further, but not a core library in Next.js.

I'll help to tackle Next.js stuff if you (or someone) is going to do that.

**Comment by timneutkens** [comment]
Related to https://github.com/zeit/next.js/issues/861

**Comment by sedubois** [comment]
Ok thanks I'll be looking forward to @impronunciable's example as I don't know how to do this right now 😊

**Comment by timneutkens** [comment]
Looks like there was an example added in the comments already @sedubois

**Comment by kristojorg** [comment]
@sedubois I have a site with photo galleries that I want to prefetch if possible. Maybe we could do this by converting static images to datauri via webpack (even when they are large)... I believe if we did this next prefetch would load the images!

What do you think?

**Comment by sedubois** [comment]
@kristojorg that sounds like a clever workaround 👍 but clearly there would need to be a better solution... my own app is about video/audio, so probably data URIs simply wouldn't be feasible.
