### ISSUE TITLE
Link broken when import css.

### ISSUE THREAD

**Issue by Nkeys** [zeit/next.js#8751]
# Bug report

## Describe the bug

This is the homepage in with-next-css example:
```javascript
import '../style.css'

export default () => <div className='example'>O Hai world!</div>
```

and I add another page: test.js
```javascript
import Link from 'next/link';

export default () => (
    <Link href='/'>
        <a>Home</a>
    </Link>
);
```

I try to go to home page(/) from test page(/test) through the link.
But the link is not work.

And then I comment the import-css-statement in home page:
```javascript
//import '../style.css'

export default () => <div className='example'>O Hai world!</div>
```

The link in test page can work!
So I think this is a bug.

## System information
- Version of Next.js: 9.0.5

**Comment by huv1k** [comment]
Hey @Nkeys, this bug is tracked [here](https://github.com/zeit/next-plugins/issues/282). We are right now implementing out of box solution for CSS in Next.js. You can read more about it [here](https://github.com/zeit/next.js/issues/8626), this is going to fix this problem and improve the overall developer experience.
