### ISSUE TITLE
How to configure a webpack alias 

### ISSUE THREAD

**Issue by thisbejim** [zeit/next.js#877]
I'd like to configure some webpack aliases to point to some of my folders (not to a lib in node_modules).

Here is a simple example:
```
var path = require('path');

module.exports = {
  webpack: function (config) {
    config.resolve.alias = {
      'components': path.resolve('./components'),
    };
    return config
  }
}
```

However, if I try to import a component in a page e.g:
```
import { NavBar } from 'components';
```

I get the following error:`Error: Cannot find module 'components'`

Any idea how to get next to play nice with an alias like this?

**Comment by arunoda** [comment]
This is bit tricky and you need more support from us because or SSR.
We've a ongoing PR here: https://github.com/zeit/next.js/pull/767 which add a alias functionality.

**Comment by flyingbuddha** [comment]
I'm looking for the same answer. I've checked out your suggestion @arunoda, but it didn't seem to resolve the problem.

**Comment by arunoda** [comment]
Now we do this like this:

* For the client side, we can always use webpack alias.
* But for the server side, we can use module-alias npm package as we use [here](https://github.com/zeit/next.js/blob/master/examples/using-preact/server.js#L7).

**Comment by benjaminjackman** [comment]
@arunoda  my use case is a bit closer to @thisbejim than the example used there. Rather than override certain things in production or development, i just want to be able refer to my components with `components/....` rather than some combination of `../../../components` is the suggested way to do that still to create a `server.js` file but then drop the `if(!dev)` line?

**Comment by chuyik** [comment]
Do I have to create a `server.js` to achieve this?

**Comment by andfelzapata** [comment]
The best option is to go with [babel-plugin-module-alias](https://www.npmjs.com/package/babel-plugin-module-alias)

**Comment by zentuit** [comment]
Has anyone gotten this to work?  I cannot get this aliasing stuff to work so I can eliminate the horrible paths in the imports, ie 
`import { someFunction } from 'lib/util'` 
rather than 
`import { someFunction }  from '../../lib/util'` 

I have tried babel-plugin-module-alias, babel-plugin-webpack-alias, setting webpack resolve.modules all to no avail.

**Comment by thisbejim** [comment]
I've been using module-alias successfully, just make sure you add the changes from their documentation to your .babelrc file.

**Comment by zentuit** [comment]
Found my issue, everything is working great now. Thanks!

**Comment by timneutkens** [comment]
There's an example for doing this now https://github.com/zeit/next.js/tree/master/examples/with-absolute-imports

**Comment by timneutkens** [comment]
@zentuit no worries 😄 👍
