### ISSUE TITLE
Move from gulp to fly

### ISSUE THREAD

**Issue by timneutkens** [zeit/next.js#884]
https://github.com/flyjs/fly

Mentioned by @rauchg here: https://github.com/zeit/next.js/pull/435

**Comment by arunoda** [comment]
I am down with anything that works. But I personally prefer simply to use shell scripts (may be with shelljs) along with NPM scripts.

**Comment by lukeed** [comment]
@arunoda As do I. IMO, everything a repo _can do_ (re: builds, test) should be easily described by an npm script...and its definition shouldn't extend beyond the viewport. Pointless at that point.

I'm finishing up Fly 2.0 right now, and initial benchmarks show that it's 3 to 8x faster than Gulp. And, its `flyfile.js` syntax is much simpler & cleaner than Gulp's -- we're chaining methods (extremely minimal wrappers around any API) directly instead of asking you to write 1,001 `pipe()`s on the page. 😆
