### ISSUE TITLE
next/link should navigate the document when component fails to load due to build ID mismatch

### ISSUE THREAD

**Issue by bryanrsmith** [zeit/next.js#995]
Users browsing a Next site during a deployment can get hit with an error page when the build ID changes and a page component fails to load. It'd be cool to detect this condition in next/link (or maybe within the router?) and navigate the document to the target location so we get a full page load and the user is seamlessly migrated to the new build.

**Comment by timneutkens** [comment]
@bryanrsmith Do you mean these steps to reproduce?

Steps to reproduce:

1. `next build`
2. `next start`
3. Open webbrowser and go to running application
4. `next build`

This would generate a new BUILD_ID. Since the previous BUILD_ID was used in the asset urls and clicking a `<Link>` won't replace the assets.

**Comment by bryanrsmith** [comment]
Yes, exactly.

**Comment by arunoda** [comment]
Yep. I think in this case, we should do a reload.
